### ISSUE TITLE
Add ENS Support to MyMeta

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1000]
### What would you like to be added?

Currently we display an ethereum address as part of a user's MyMeta profile. It would be nice to support ENS addresses as well since many of the prominent DAO participants have them.

We could set up a system for verification of ownership and whatnot, but the only side-effect of putting someone else's ENS address as your own is transfers intended for you go to them.

Alternatively we could display their reverse record which is unique for a given a address. The disadvantage is they might wish to use a different name for a particular organization.

### Why is this needed?

ENS addresses are prettier, more expressive, & less error prone.

**Comment by alalonde** [comment]
Closing this in favor of #1176
