### ISSUE TITLE
MegaMenu - Styling enhancements

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#1003]
After a few iterations, the MetaMenu is almost there when it comes to its look & feel 🙌

Just a few more smaller changes, and it will be perfect!

Please use the below image for visual reference:
![megamenu-finetune.png](https://images.zenhubusercontent.com/603d32d6edb5330e5cd0dd54/16a6138f-ae14-42d5-b415-4e224aae90c3)

To do:

1. Make the logo vertically centered (relative to the header).
2. Set the `font-weight` for top-level links to `700`
3. Set the `color` for active/expanded top-level link to `var(--chakra-colors-cyan-300)`
4. Make the opened menus horizontally centered relative to the viewport.

Let me know if there's any questions or concerns and we'll figure it out together!

**Comment by LarrySimiyu** [comment]
@davort I can take a look at this :)

**Comment by davort** [comment]
Hi @LarrySimiyu - that's great! Let me know if you'd need anything else re: design before you begin 😊

**Comment by vidvidvid** [comment]
@davort some of the stuff is already fixed, but i'll make sure to check what else is missing and include the solutions in #1104

**Comment by vidvidvid** [comment]
@LarrySimiyu unless you plan to deliver this anytime soon? :)

**Comment by LarrySimiyu** [comment]
@vidvidvid @davort so sorry I got caught up with some major family stuff past month and job applications. I apologize for my lack of communication since picking this ticket up. Won't happen again. @vidvidvid Thank you for picking this up.

**Comment by vidvidvid** [comment]
@LarrySimiyu np, life happens - if possible just let us know you about it next time :)

**Comment by vidvidvid** [comment]
Solved in #1104
