### ISSUE TITLE
View profile button on mobile redirects to wrong url.

### ISSUE THREAD

**Issue by firattale** [MetaFam/TheGame#1020]
### What happened?

I realized that clicking view profile button redirects to shortened version of the wallet address, which has couple of dots and it redirects to 404 page.

### What did you expect to happen?

It should redirect to my profile page with correct address.

### How can we reproduce the problem (as minimally as possible)?

Open Metagame in your mobile device or mobile mode on your desktop browser, connect your wallet, and click view profile
<img width="350" alt="Screenshot 2022-01-05 at 13 20 17" src="https://user-images.githubusercontent.com/34514974/148217144-43d5e496-348d-4b21-aa07-f035c7906f2c.png">
<img width="567" alt="Screenshot 2022-01-05 at 13 24 23" src="https://user-images.githubusercontent.com/34514974/148217189-bc3420c0-504d-4765-929b-65488e0ca5b4.png">
.

**Comment by dysbulic** [comment]
This should be fixed in the `feat/glaze-lookup` branch which adds a `getURLFor(player)` function to generate the player URL.

**Comment by firattale** [comment]
I think this is for users like me who doesnt have any username. it was occuring because of this code snippet.
`export const formatAddress = (address = ''): string =>
  `${address.slice(0, 6)}...${address.slice(-4)}`;
`
@dysbulic

**Comment by vidvidvid** [comment]
@dysbulic @firattale any update on that?

**Comment by firattale** [comment]
I guess @dysbulic merged this branch recently, did it happening still @vidvidvid ?

**Comment by firattale** [comment]
Yeah it seems like it is working, I am closing this issue.
