### ISSUE TITLE
[Quests] Completions via discord props channel 

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1023]
### What would you like to be added?

Some quests are completed simply by doing them but others need to be accounted for through #did-a-thing or by adding initiatives. We need to figure out what this looks like. For smaller quests, the creator of the quest could click "complete quest" & there could be a bot @player who completed the quest in a hidden #give-props channel where XP Fairies then verify & reward quest completions.

### Why is this needed?

Essential feature for the questing mechanism

**Comment by alalonde** [comment]
Seems like this needs a bit more precise definition. Can you or @peth-yursick give a step-by-step example of the desired questing workflow, including this Discord integration?
