### ISSUE TITLE
[Quests] Improved filtering + Roles

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1024]
### What would you like to be added?

**Quest filtering by roles/domains** 
In order to do this, we need to add another field to quests that contains [all of the possible roles](https://forum.metagame.wtf/t/the-4-domains-of-metagame-an-organizational-structure-v0-2/687).
For now I think we could add just some basic ones that cover most areas:
- Innkeeping
- Writing
- Designing
- Building
- Headhunting
- Art
- Shilling

Evergreen quests appearing separately from the rest & other ways of making it easier for people to choose among 100 quests.
Update the filter design to match the `/community/players` filters and the rest of them.

### Why is this needed?

Essential feature for MVP https://miro.com/app/board/o9J_ldTAEnQ=/

**Comment by vidvidvid** [comment]
@peth-yursick

**Comment by peth-yursick** [comment]
I'd only add these 3:
- Bridgebuilding
  - All about fostering connections and enabling the flow of people & resources between different organizations.
- Rainmaking
  - Making sure value is recognized & project tokens get bought or liquidity added by long term holders.
- Videomaking
  - As the name suggest - it's about production of videos no matter the kind; educational, entertaining or both.

**Comment by vidvidvid** [comment]
@peth-yursick thanks, will be added! by the way, could we perhaps also add these to the setup wizard?

**Comment by peth-yursick** [comment]
👌
we could but they were intentionally left out so that people need to join through one of the basic roles before they can take on these higher level ones
