### ISSUE TITLE
Show selected role in profile

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1026]
### What would you like to be added?

We have added role selection to the setup profile flow, but it's currently not shown anywhere. 

### Why is this needed?

So folks have a visual of their own profile details

**Comment by alalonde** [comment]
@davort Any recommendations on where we should show this?

**Comment by davort** [comment]
@alalonde Can we do something like this, for now? On player's own profile, stack it on top of the "Verify with BrightID" button
![PlayerRole-tinified](https://user-images.githubusercontent.com/1573304/148551968-e9085d38-147d-4411-995d-d8a3edaca974.png).
