### ISSUE TITLE
Redirect to 404 when player doesn't exist

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1030]
Working upon #1013
We should updating wherever we display 404 errors with a redirect to this page.
For example, when a player is not found in `/player/<username>`
https://test.metagame.wtf/player/thisplayerdoesnotexist

**Comment by firattale** [comment]
I can take this since it is related to 404 page.

**Comment by firattale** [comment]
@dan13ram this PR https://github.com/MetaFam/TheGame/pull/1033 closes this issue, I also realized we had same problem for guild page and quest completed page too.
