### ISSUE TITLE
Add button to reset profile layout to default

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1035]
### What would you like to be added?

Improve upon the profile layout introduced in #1012 and allow players to reset their layout to default with a button click.

### Why is this needed?

Quote from @vidvidvid 
>   if i attempted to reset layout I assumed i'd get the default layout, but the layout changed to the last saved version. Would it make sense to add another button for resetting the layout to its default values?

**Comment by LouieRichardson99** [comment]
I will start work on this.

**Comment by dan13ram** [comment]
> There is also no "cancel" button to discard current changes. I added something and didn't like it, and had to refresh to "discard" the changes

@alalonde There should be a "Reset" button right ? Didn't that reset your change?

**Comment by vidvidvid** [comment]
Maybe cancelling should reset and exit the editing mode?

**Comment by vidvidvid** [comment]
since there has been no reported progress on this, i'll be fixing this in #1104
since there is already a cancel button, do we agree we add a button to revert to the default layout or should we just close the issue?
@dan13ram @alalonde ?

**Comment by vidvidvid** [comment]
@LouieRichardson99 i assume you've abandoned the issue?

**Comment by alalonde** [comment]
> @alalonde There should be a "Reset" button right ? Didn't that reset your change?

Ah, to me, "reset" means to reset your saved configuration to the default. But "cancel" should revert any unsaved changes.

**Comment by vidvidvid** [comment]
Solved in #1104
