### ISSUE TITLE
Implement dynamic resizing for profile layout sections

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1036]
### What would you like to be added?

Dynamically measure the size of profile sections and update the `layouts` of `react-grid-layouts`
Improves upon #1012 

### Why is this needed?

`react-grid-layouts` by default only supports fixed widths and heights for sections, and consequently default profiles of many players has a lot of empty spaces. 

How it is atm:
<img width="1792" alt="Screenshot 2022-01-05 at 16 22 24" src="https://user-images.githubusercontent.com/35112939/148245060-204c1b8c-61fb-4c36-8cdf-8b669010d5e3.png">

How it should be:
<img width="1792" alt="Screenshot 2022-01-05 at 16 24 27" src="https://user-images.githubusercontent.com/35112939/148245107-8c3778f8-a197-4111-bd16-7ac1e9ebb8c9.png">

**Comment by dysbulic** [comment]
Bear in mind that the height of the player hero is variable once the page is loaded dependent on the status of the "show more" toggle.

#943 adds `white-space: pre-wrap` to the description text, so it can span several lines.
