### ISSUE TITLE
Convert the Discord bot to ESM using discordx

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1038]
### What would you like to be added?

The library currently used as the basis for the Discord bot, [`@typeit/discord`](https://github.com/OwenCalvin/discord.ts), has been abandoned and is no longer maintained.

The recommended alternative is [`discordx`](https://discord-ts.js.org).

### Why is this needed?

`node-fetch` can no longer be imported using a `require` function as of v3. It is solely supporting ESM (ECMAScript Modules).

There are [instructions](//github.com/node-fetch/node-fetch/issues/1279#issuecomment-915062146) describing how to convert a project to ESM in the `node-fetch` repository.

This would also be an opportunity to do the migration to slash commands (#514).

**Comment by vidvidvid** [comment]
related #953
