### ISSUE TITLE
Remove storybook from design system

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1043]
### What would you like to be added?

Actually I'd like storybook to be removed 🔥 

### Why is this needed?

We are maintaining certain dependabot updates, which pertain only to the storybook which is not being used. In case we ever decide to make use of it, we need to set it up in such a way that we can get value out of it and consistently keep on updating it.

**Comment by firattale** [comment]
this PR https://github.com/MetaFam/TheGame/pull/1044 closes this issue.
