### ISSUE TITLE
Next iteration of landing page + missing links

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1047]
### What would you like to be added?

Let's gather ideas for the next iteration for the landing page here. I'm opening the issue mainly because I noticed that the links are missing or wrong.

### Add missing links to various parts of the landing page:

`The wiki` link:
<img width="434" alt="Screenshot 2022-01-15 at 19 04 23" src="https://user-images.githubusercontent.com/35112939/149632823-9a2ba64b-b791-46a1-b927-913cc315470e.png">

the final buttons lead to nowhere:
<img width="1171" alt="Screenshot 2022-01-15 at 19 13 29" src="https://user-images.githubusercontent.com/35112939/149633048-ab6ed91e-8c3f-4735-9957-103f1511f7b4.png">

### Enable navigating through the 'slides' by pressing arrow buttons

`scroll-behavior: smooth`
`← ↑` : previous slide
`→ ↓` : next slide

### Play around with some `threejs` animations

@luxumbra @tommymaher15 ideas?

### Why is this needed?

Links are missing + we should make the landing page epic

### Text corrections

[alec's comments:](https://github.com/MetaFam/TheGame/pull/1018#issuecomment-1012397835)

> "Metagame is any approach to a game that transcends or operates outside of the prescribed rules of the game, uses external factors to affect the game, or goes beyond the supposed limits or environment set by the game."

What game? This doesn't really mean anything to me. Seems like this should be a bit more accessible

> "A revolution is happening online; will you join or miss out?"

Should be a comma not a semicolon

> Guilds: "For those who want to: Help finding tools, frameworks & funds accessible. Help getting value-aligned contributors & adopters. Become a part of the "new world" puzzle. "

Get help, Get help, Become

---
Address @pvblic-vniversal-friend 's [comment](https://github.com/MetaFam/TheGame/pull/1018#issuecomment-1012497015) about the words _nao_ and _moar_?
<img width="429" alt="Screenshot 2022-01-15 at 19 41 50" src="https://user-images.githubusercontent.com/35112939/149634043-2271dc21-a630-4082-93cf-4bb6a2a2808d.png">

**Comment by tommymaher15** [comment]
I was exploring the idea a while back but maybe a 3d animation for the first slide: Like a metagame Logo that was 3d? would love to hear others thoughts on this if its a good idea :)

**Comment by luxumbra** [comment]
> I was exploring the idea a while back but maybe a 3d animation for the first slide: Like a metagame Logo that was 3d? would love to hear others thoughts on this if its a good idea :)

Pretty much what I was thinking for the first section. I was asking if any of the 3d artists have created a 3d mg logo and Misanth had started one but never got to finishing it due to GPU burnout.

**Comment by luxumbra** [comment]
> Let's gather ideas for the next iteration for the landing page here. I'm opening the issue mainly because I noticed that the links are missing or wrong.

I have been thinking about it and I quite like peths idea to have a kind of Neo/Rabbit hole scene (wake up Neo) that the user scrolls through, reading text like it's on a old skool monitor. Screen glitches and a hand beckons for the user to jump in. I also thought about (& bought) an Octopus  that would feature in the flow but not sure. We definitely want a logo with a field of stars behind it or something as a first section.

**Comment by tommymaher15** [comment]
That would be awesome. I was looking at some tv glitch effects using three.js too this could be useful:

https://codesandbox.io/s/y3j31r13zz

Thats a general idea but there are tonnes of different examples out there that could work better. 

What about the flow of the page? Will we be going down the route of slide transitions or scrolling through?

**Comment by vidvidvid** [comment]
> What about the flow of the page? Will we be going down the route of slide transitions or scrolling through?

We could make support for both, but most pages that I looked at are mainly done by scrolling.

**Comment by tommymaher15** [comment]
Awesome. I wasn't sure which was happening. Exciting nonetheless!

**Comment by jb0gie** [comment]
ooooooo

**Comment by jb0gie** [comment]
the landing page: 
how about a medium sized area...[land, plane, floor] the ( easter eggs )
big old MG🐙 vaporwave text in the sky with an OCTO to boot
and the super dope model being shown in the [cord server](https://cdn.discordapp.com/attachments/914108129455775755/937077489312870460/metagame_logo__scene.png)
