### ISSUE TITLE
Publish the Kubernetes configuration for MetaGame's Ceramic node

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1060]
### What would you like to be added?

Our Ceramic mainnet node, `ceramic.metagame.wtf`, is hosted on Google's cloud infrastructure using Kubernetes.

The deployment configuration is file-based, and those files are currently held by @polimyl who developed them.

They should be published on GitHub, most likely in their own repository since they're independent of MyMeta and interested parties will likely only want to look at them.

### Why is this needed?

There are several reasons publishing these configurations would be useful:

* Allow other developers to review them for potential issues
* Allow other developers to learn from them
* 3Box has [Terraform scripts for deployment to Amazon Web Services](//github.com/ceramicnetwork/terraform-aws-ceramic) and another developer released a [Helm chart](//gitlab.com/minds/ceramic-helm-chart), but there's not a public K8s configuration to my knowledge

Additionally, this new repository should be added to the [SourceCred configuration](//github.com/MetaFam/XP/blob/master/config/plugins/sourcecred/github/config.json) so as to garner XP.

**Comment by polimyl** [comment]
files have been published in [MetaFam/infrastructure](https://github.com/MetaFam/infrastructure)

**Comment by dysbulic** [comment]
Gud'n'dun.

**Comment by dysbulic** [comment]
Gud'n'dun.
