### ISSUE TITLE
Split the Google Cloud Run GitHub Action into separate jobs

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1062]
### What would you like to be added?

Currently the cloud deployment GitHub action is a single [job](//docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs) broken into about a dozen steps. The steps in a job execute serially whereas multiple jobs will run in parallel.

The [`needs`](//docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds) keyword should be used to make sure that containers are built before they are deployed & that the backend starts before Hasura and Hasura before the frontend.

### Why is this needed?

It takes about half an hour for an instance to deploy if all the containers need to be rebuilt.

The existing structure could likely be half an order of magnitude faster if properly parallelized.

**Comment by Rexben001** [comment]
I can work on this @dysbulic

**Comment by dysbulic** [comment]
@Rexben001, the GitHub deployment action has undergone significant revision in the [`feat/glaze-lookup` branch](//github.com/MetaFam/TheGame/blob/feat/glaze-lookup/.github/workflows/gcp-deploy.yaml), and that is hopefully going to get merged in the next couple days.

In any case, you should work from that Action rather than the one that's in `develop`.

So far as ordering, the important thing to remember is the backend has to start before Hasura will start, and Hasura has to be running for the frontend to *build* (not start, build).

All of the teardown and image removal tasks could be in parallel, as could the building of the backend and Hasura.

**Comment by dysbulic** [comment]
@Rexben001, I went ahead and did this in #1078 because I needed to move the seeding step & the decomposition into jobs was relatively straightforward.
