### ISSUE TITLE
BrightId not working

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1068]
App shows that BrightId is linked, but the UI still shows unverified.

**Comment by firattale** [comment]
I saw the same issue, but as I see from their website, you need to verify via their zoom meeting.

https://brightid.gitbook.io/brightid/getting-verified

https://meet.brightid.org/#/

**Comment by dysbulic** [comment]
> I saw the same issue, but as I see from their website, you need to verify via their zoom meeting.

@firattale, even if you're verified, once you connect the site in BrightId the verify button doesn't change to verified.
