### ISSUE TITLE
[MetaMenu] - Disclaimer in the Invest section

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1074]
### What would you like to be added?

The "Invest" section of the metamenu should feature a disclaimer saying something like "We offer no prospects of financial return, invest for good feels only."

### Why is this needed?

To avoid any legal ramifications of MetaGame offering investments or Seeds being labeled a security.

**Comment by mquellhorst** [comment]
The word Invest makes it tricky.
Lets change it now to contribute or patron for now

**Comment by peth-yursick** [comment]
> The word Invest makes it tricky.
> Lets change it now to contribute or patron for now

We talked about this on the champions ring a few weeks ago, the problem with "contribute" is that "contribute" already exists. We also talked about turning it into something like "give", but then its like "contribute, "give"... "Give" would work if we stuck with "learn" & "earn". The reason it shouldn't be MetaGame specific is because the section is supposed to also include things like Giveth grants..
Tenfinney said having it say "invest" is not a problem as long as we explain that you shouldn't expect a financial return - which really is the case with donating to grants 🤷‍♂️

**Comment by mquellhorst** [comment]
I'ld say if nobody is sure but some people feel it's risky we either seek legal advice or take the safe route

**Comment by peth-yursick** [comment]
> I'ld say if nobody is sure but some people feel it's risky we either seek legal advice or take the safe route

Tenfinney pretty much is legal advice & he said the disclaimer solves the problem..
But.. Simply merging the category into "contribute" by adding "Seed" under "Quests" might also be a good solution 🤷‍♂️
![image](https://user-images.githubusercontent.com/55857222/153280589-dbb48998-ffac-474c-9298-f271f0b799b7.png)

**Comment by davort** [comment]
> The "Invest" section of the metamenu should feature a disclaimer saying something like "We offer no prospects of financial return, invest for good feels only."
IMHO should be fairly easy to add in design—somebody please correct me if I'm wrong and it's a bitch to add in code. If that shields us from legal ramifications, I'd say it's super simple and let's go for it!

**Comment by davort** [comment]
> > But.. Simply merging the category into "contribute" by adding "Seed" under "Quests" might also be a good solution 🤷‍♂️ !

@peth-yursick Just so I'm sure I understood the idea—did you think merge "Contribute" and "Invest", so that all 4 sections from "Invest" get added to "Contribute", and "Contribute" then contains seven (7) sections in total?

**Before**
```
CONTRIBUTE
- Roles
- Raids
- Quests
                          
INVEST
- Become a Patron
- Buy Seeds
- Plant Seeds
- Support Grants
```
**After**
```
CONTRIBUTE
- Roles
- Raids
- Quests
- Become a Patron
- Buy Seeds
- Plant Seeds
- Support Grants
```

**Comment by vidvidvid** [comment]
I'll take this, it's an ez fix :)

**Comment by vidvidvid** [comment]
@davort @peth-yursick is that ok? (the icon colors and positioning seems a bit odd)
<img width="1168" alt="Screenshot 2022-02-10 at 09 03 29" src="https://user-images.githubusercontent.com/35112939/153363557-9fc3edc1-d496-4bf6-9832-ab4ede8da0c4.png">

**Comment by peth-yursick** [comment]
> @peth-yursick Just so I'm sure I understood the idea—did you think merge "Contribute" and "Invest", so that all 4 sections from "Invest" get added to "Contribute", and "Contribute" then contains seven (7) sections in total?

I meant merge but so that we only end up with "Roles", "Quests", "Raids", & "Seed" - everything under "Invest" is getting merged into a single page with #925 except for "support grants" which we don't have. The idea with "support grants" was to integrate Giveth directly, but we can do that later.

**Comment by vidvidvid** [comment]
ahhh ok, i'll contact cris for this.

**Comment by peth-yursick** [comment]
Since all the links in the invest section are currently broken, I'd say feel free to just merge & link to this https://meta-game.notion.site/Seeds-3a301b30f9394751b77b2450f7ae2329
