### ISSUE TITLE
Users connecting for the first time should be directed to the profile setup wizard

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1097]
### What happened?

When a user connects for the first time an account should be created for them in Hasura & they should be directed to the profile setup wizard.

Currently that does not happen.

### What did you expect to happen?

New users should be directed to the profile wizard, they aren't.

### How can we reproduce the problem (as minimally as possible)?

Sign in to the site with an ETH account that isn't in the system.

**Comment by alalonde** [comment]
This is broken on prod as well.

**Comment by dysbulic** [comment]
> This is broken on prod as well.

@alalonde, did this ever work?

I'm leaning toward pulling down the Ceramic profile in the browser for new MyMeta users so that I only request they make a profile if they haven't elsewhere. Also new users won't be cached yet, so we run the risk of overwriting an existing profile (#1132) if we don't check.

What I don't know how to do is how to tell when a user is new to MyMeta. I switched up `/auth-webhook` *(where users are created)* to return a status of 201 instead of 200 when a user is created. I've not been able to find any evidence of who calls that endpoint though.

Is it called by Hasura internally & passed the bearer token sent to the GraphQL endpoint by the browser?

Maybe I'll get a non-zero `affected_rows` only for situations where a user was created.

I added a reentrancy check to prevent multiple calls to `createPlayer` because if they're on a profile page when they log in there's four or five calls in quick succession & some were making it into `createPlayer` and failing the uniqueness check on ETH address trying to create the same account multiple times. *(This was the reason for #1098.)* This means only one call will know a new user was created & I guess I'll have to put the logic to push them to the wizard in the `useUser` hook… Except any query might be the one to cause the creation of a new user, not just `useUser`…

I could always just check their profile & determine if it's empty (`createdAt === updatedAt`?). If they skip out of the profile creation process without entering anything, I could touch `updatedAt` to keep them from being asked again…

**Comment by alalonde** [comment]
> What I don't know how to do is how to tell when a user is new to MyMeta. I switched up /auth-webhook (where users are created) to return a status of 201 instead of 200 when a user is created. I've not been able to find any evidence of who calls that endpoint though.

Yes, I believe this is called by Hasura.

> I could always just check their profile & determine if it's empty (createdAt === updatedAt?). If they skip out of the profile creation process without entering anything, I could touch updatedAt to keep them from being asked again…

Something like this seems like the better way of doing it, as it is not so transitory. If a user has connected an account but not created a username (since that is required and I believe the first step) and not explicitly exited out of the setup wizard, we will always redirect them to the setup wizard.
