### ISSUE TITLE
Borked edit skills selection

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1117]
### What happened?

![skills_bug](https://user-images.githubusercontent.com/35112939/152969866-7e53b235-5997-4815-a0e7-ecc0050f0db3.gif)

### What did you expect to happen?

Larger height of the skills dropdown

### How can we reproduce the problem (as minimally as possible)?

go to https://test.metagame.wtf/, your profile, edit skills 

### Is there anything else we need to know?

the dropdown is displayed properly here: https://test.metagame.wtf/profile/setup/skills

**Comment by vidvidvid** [comment]
looks like it's a problem of `overflow: auto` on the parent element:
<img width="1460" alt="Screenshot 2022-02-08 at 11 35 58" src="https://user-images.githubusercontent.com/35112939/152970400-5ea91c72-f2d7-44fc-9564-71f980cea922.png">

**Comment by dysbulic** [comment]
@vidvidvid, I'm in the process of significantly revamping all the profile editing panes as part of the addition of Jotai. I can make sure this is fixed in those changes.

**Comment by vidvidvid** [comment]
@dysbulic great! i'll assign you the issue then, pls make sure to close it in the upcoming pr

**Comment by dysbulic** [comment]
This has been done for a while.
