### ISSUE TITLE
Landing page is borked

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1128]
### What happened?

Huge backgrounds: https://test.metagame.wtf/landing

### What did you expect to happen?

Normal sizes of slides.

### How can we reproduce the problem (as minimally as possible)?

https://test.metagame.wtf/landing

### Is there anything else we need to know?

Looks like removing `min-height: 100%;` from parent components of slides solves the problem.

**Comment by Anosh21** [comment]
Hey, @vidvidvid I would like to work on this issue.
