### ISSUE TITLE
First-time users may accidentally overwrite their existing Ceramic profile

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1132]
### What happened?

When a user logs in for the first time, rows are created for them in the `player` and `profile` tables, and their id is queued for retrieval of their Ceramic profile.

If, as #1097 suggests, we were to forward these users to the profile setup wizard, any values they enter will overwrite existing Ceramic profile settings that they made elsewhere (like [self.id](//self.id) or the old 3Box Hub).

To avoid this I should probably load their Ceramic profile into Jotai when they connect their wallet.

This would also allow me to forward users to the profile wizard based on whether they have a Ceramic profile rather than if they have a MyMeta account.

It should only be necessary for new MyMeta users since other users should be in the cache. I'm still a little fuzzy on how to determine if a MyMeta user is new. I switched `/auth-webhook` to return a HTTP 201 if a user was created and 200 otherwise *(following the HTTP standard)*, but I don't know who is calling the endpoint and where to check the status.

### What did you expect to happen?

Silently overwriting values that a user potentially cares about is bad behavior.

### How can we reproduce the problem (as minimally as possible)?

1. Create an account on [self.id](//self.id)
2. Log into [MyMeta](//test.metagame.wtf/me)
3. Edit your profile
4. View the profile on self.id or wait for MyMeta's cache to update

**Comment by dan13ram** [comment]
@dysbulic Please check the Note in https://hasura.io/docs/latest/graphql/core/auth/authentication/webhook.html#failure

We must only return `200` or `401`. The 201 was causing problems, which was why new users couldn't login.

Would it be possible to retrieve Ceramic profiles (for new users alone) in the backend during the auth-webhook itself without adding it to the queue?

> I don't know who is calling the endpoint and where to check the status.

I believe the auth webhook is called internally by hasura for all graphql requests, and it is not possible to check it manually.

**Comment by dysbulic** [comment]
> Would it be possible to retrieve Ceramic profiles (for new users alone) in the backend during the auth-webhook itself without adding it to the queue?

That's an idea. [Bottleneck has priorities](//github.com/SGrondin/bottleneck#job-options), so I should be able to wait for the new user's profile to cache in `auth-webhook` without affecting performance too adversely.

I also reopened #1114 for [reasons explained there](//github.com/MetaFam/TheGame/issues/1114#issuecomment-1047094020).
