### ISSUE TITLE
[MyMeta] Capacity instead of time availability

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1138]
Worth discussing but I think it would be better if people's availability was expressed in % rather than hours.
It should be easier for people to put in an estimate & be realistic about how much they can commit.

Instead of:
- Availability: 4 hours
It would display:
- Capacity: 90%, maybe marked in red to signal the person is stretched thin.

Other than that single place to display it, it would be great if people were made to allocate these percentages to the guilds that they're a part of. It would then also give a realistic overview of how much someone is actually contributing to guilds that they're members of beyond "member of".
The "membership" screen in profile creation could have an input field next to every guild where player should type in % of their time that they have allocated to the project.

**Comment by alalonde** [comment]
Picking this up as I am currently defining the new data models for ComposeDB.

"Capacity" doesn't seem quite right as its meaning seems non-obvious. Capacity of what? Your total waking hours? Your weekly time allocated to "work"? What is "work" even in the age of DAOs?  

This is an interesting idea. I think the ability to indicate someone's "level of involvement" in a particular guild is a separate thing. IMO Representing this as a percentage of the full "capacity" seems a bit odd especially in the weird world of DAOs, where people are typically fluidly moving in and out of different organizations at different levels of commitment.

If we do decide to move away from "Available hours" the new metric should make minimal assumptions about one's work habits / schedule / work-life balance.

**Comment by peth-yursick** [comment]
Good point, lets just close this 🤷‍♂️
