### ISSUE TITLE
[MyMeta] Add DAO info to guild pages

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1142]
Right now, there are no links to guild's DAO even if they have one.

I think we should add a fiield for a link to "your DAO", "your multisig" &/or "your treasury" to the guild application form. 
Every guild that has a DAO on DAOHaus or a multisig, should also have a link on their profile connected to it.

**Comment by alalonde** [comment]
Yeah, already there have been questions during guild onboarding about e.g. "which DAO"? 

1. Would it make sense to specify the network alongside the current DAO contract address? Or is mainnet a reasonable default
2. Seems like there is a large enough diversity of org structures between DAOs that having specific fields for "multisig" and "treasury" may not suffice? What if we just added the ability to add multiple DAOs, and for each of them they could add a `label`, `contractAddress`, `network`, and maybe `url`?

**Comment by peth-yursick** [comment]
> Would it make sense to specify the network alongside the current DAO contract address? Or is mainnet a reasonable default

Probably yes, there is a decent number of DAOs on xDAI & other networks, with more & more coming up as mainnet is increasingly unfeasible for most..



> Seems like there is a large enough diversity of org structures between DAOs that having specific fields for "multisig" and "treasury" may not suffice? What if we just added the ability to add multiple DAOs, and for each of them they could add a `label`, `contractAddress`, `network`, and maybe `url`?

Yeah, I was thinking just have an "address" field & the explanation could be "put in an address to your DAO, multisig or whatever" but having multiple fields works even better.

**Comment by alalonde** [comment]
So, shall we add a new block to the guild page? "DAO Information" ? Which is only visible if they have at least one address added?

Then something like 

<label>: <contractAddress> <network-label>

for each DAO which would render e.g.

DAO: [0xasdf23asdf23h32h43h43h434](https://app.daohaus.club/dao/0x1/0x0372f3696fa7dc99801f435fd6737e57818239f2) mainnet

and if a "URL" is provided it would link to that URL instead of daohaus

Current page (test env) for reference: 
<img width="983" alt="image" src="https://user-images.githubusercontent.com/1402582/155066346-2626f964-f08f-4cb6-9ba1-d22a557a7219.png">

**Comment by peth-yursick** [comment]
> So, shall we add a new block to the guild page? "DAO Information" ? Which is only visible if they have at least one address added?
> 
> Then something like
> 
> `<label>: <contractAddress> <network-label>`
> 
> for each DAO which would render e.g.
> 
> DAO: [0x0372f3696fa7dc99801f435fd6737e57818239f2](https://app.daohaus.club/dao/0x1/0x0372f3696fa7dc99801f435fd6737e57818239f2) mainnet Treasury: [0xbd6fa666fbb6fdeb4fc5eb36cdd5c87b069b24c1](https://gnosis-safe.com/...) xdai
> 
> and if a "URL" is provided it would link to that URL instead of daohaus
> 
> Current page (test env) for reference: <img alt="image" width="983" src="https://user-images.githubusercontent.com/1402582/155066346-2626f964-f08f-4cb6-9ba1-d22a557a7219.png">

My first thought was that it could just be added to the "links" section but yeah, might be better to have a whole block for it.
Could specify whether they have a DAO or a multisig instead of just have a link (esp. if they have both) & later could be pulling in data such as "treasury size"
