### ISSUE TITLE
Enable upgrades to the extended Ceramic profile schema

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1144]
### What would you like to be added?

There is a script [`packages/utils/bin/create-model.mjs`](//github.com/MetaFam/TheGame/blob/develop/packages/utils/bin/create-model.mjs) which reads a [JSON5 JSON Schema](//github.com/MetaFam/TheGame/blob/develop/packages/utils/schema/extended-profile.json5) and generates a Ceramic stream using that schema to determine valid updates.

Currently this program is only capable of creating a new stream. This would orphan any profiles created using the previous [stream identifier](//github.com/MetaFam/TheGame/blob/develop/packages/utils/src/ExtendedProfileModel.json) leaving them unable to be retrieved.

The program needs to be changed to perform an update to the metadata for the existing stream to substitute in a new schema.

### Why is this needed?

There are several potential alterations to the profile being considered. For example, I would like to relax the requirements on usernames to allow capital letters and dots in them.

**Comment by peth-yursick** [comment]
is this still relevant after moving to composedb?

**Comment by dysbulic** [comment]
@peth-yursick, the principles still hold, but with ComposeDB there's no way to update models. Whatever we deploy to production we're pretty much stuck with.
