### ISSUE TITLE
Use Docker's buildx to generate the container images

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1159]
### What would you like to be added?

#1076 suggests using Cloud Native Buildpacks to generate our container images for Hasura development and Cloud Run test instances. Buildpacks is of unknown complexity and it may take some time before a developer can take the time to figure out how to leverage it.

Docker's [`buildx` command](//github.com/docker/buildx#readme) is a successor to the `build` command. It includes a [`bake`](//github.com/marketplace/actions/docker-setup-buildx) subcommand that is reportedly like `docker-compose build`, but with more advanced caching and running in parallel. It can use a `docker-compose.yaml` and seems to process the one in MyMeta's root without error.

It is possible to use the existing `docker-compose` command by specifying environment variables which direct `docker-compose` to use the `docker` CLI and the `docker` CLI to use the BuildKit container image generation runtime which is what backs `buildx`. I added a `yarn docker:debug` command to [the `feat/docker-buildx` branch](//github.com/MetaFam/TheGame/tree/feat/docker-buildx) that executes in that manner, but it doesn't have the same number of cache hits as running `docker buildx bake` whose output I don't know how to execute.

Additionally, there is [a GitHub Action](//github.com/marketplace/actions/docker-setup-buildx) for using `buildx` to generate container images.

### Why is this needed?

Building the Docker images takes quite a while. Up to half an hour for the Cloud Run deployments, but also 5–10 minutes for developers working locally. Speeding this up, as mentioned in #1076, could equate to significantly less time spent waiting.

**Comment by Seroxdesign** [comment]
Outdated
