### ISSUE TITLE
Fixing the onboarding flow 1/3

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1164]
### What would you like to be added?

The "join metagame" button on the new landing page should lead directly into MyMeta profile creation flow & into discord.

##Currently
Right now, there isn't a "create profile" anywhere inside MetaGame. The first screen when connecting the wallet is the players list & opening your (inexistent) profile gives you module editing only.
Clicking "join" on the landing page takes you to [the wiki join page ](https://wiki.metagame.wtf/docs/enter-metagame/join-metagame)

##How it could be better
~~The "join" button on the landing page should take people to the MyMeta creation flow which currently doesn't have an opening screen, only the first step, which is "name".~~
Has an opening screen now, just needs more text.

### MVP
- there needs to be a page that says something like "you are about to create a mymeta profile, connect your wallet & click next", if you don't have a wallet yet, go here to install metamask.
- after the profile is created...
  - there could be a selection screen where the player chooses "dashboard" or "discord"
  - the player could automatically be redirected to the dashboard, with a popup message about the next step, which is joining discord, reading the welcome doc & taking up a quest or joining a conversation on discord (until we have intro quests, welcome page, open roles etc. all integrated in MetaOS)
- there should be the newsletter subscription step somewhere in here

Note: this is still only for "players" but we also have "guilds" & "patrons & the "guild join" & "Seeds" pages.
So we need to figure out what we want to do about that. Should the "whom is it for" section with cards on the landing page have 3 different links? Should they have different flows with eg. "for guilds" leading directly into "guild/join" or should they all begin with the profile creation? All up for discussion..

### Why is this needed?

Right now, MyMeta profiles are completely disjointed from the landing page, which leads into the wiki.
A long time ago, we discussed how creating the profile should be the first thing people do before trying to join the community.
This was held back until the whole profile creation flow is directly integrated with ceramic because going to self.id was breaking the UX.
Now, we have it 🤷‍♂️

We also now have the guild signup page as well as the Seeds page.

**Comment by dan13ram** [comment]
This is related to #1097

**Comment by tenfinney** [comment]
@dysbulic and I added a "Roster" button linking to [my.metagame.wtf/players](//my.metagame.wtf/players) which we are endeavoring to rename to players.metagame.wtf. 

[my.metagame.wtf/me](//my.metagame.wtf/me) will take the user to the site root at [my.metagame.wtf](//my.metagame.wtf)

We also added the MegaMenu to the **Game On!** page

![Screenshot_2022-02-28_13-13-11](https://user-images.githubusercontent.com/32429716/156059572-f8a790b1-af87-4e3b-9882-7439c988a221.png)

**Comment by tenfinney** [comment]
> there needs to be a page that says something like "you are about to create a mymeta profile, connect your wallet & click next", if you don't have a wallet yet, go here to install metamask.

This is [test.metagame.wtf/join](//test.metagame.wtf/join).

> there could be a selection screen where the player chooses "dashboard" or "discord"
>⋮ 
> there should be the newsletter subscription step somewhere in here

[Discord](//discord.gg/metagame) is "Play", [dashboard](//my.metagame.wtf/dashboard) is "Explore", the [Player's leaderboard](//my.metagame.wtf/players) is "Roster", & [Substack](//metagame.substack.com/?utm_source=discover_search) is "Substack" .

> Note: this is still only for "players" but we also have "guilds" & "patrons & the "guild join" & "Seeds" pages.

This is handled by the addition of the MegaMenu to the page.
