### ISSUE TITLE
[MetaOS] Displaying only mainnet Seeds

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1165]
### What happened?

When I switched network to Polygon, it still says 0 Seeds

### What did you expect to happen?

Didn't really expect it but was hoping the number would switch

### How can we reproduce the problem (as minimally as possible)?

![image](https://user-images.githubusercontent.com/55857222/155411917-1dfef677-8c5d-4c8a-a820-827350ed81bf.png)

**Comment by dysbulic** [comment]
They get chastised when they switch chains because if they save to anything other than the mainnet they're profile entry won't appear in MyMeta.

A preferable alternative might be to put a chain icon next to the SEED icon in the MegaMenu, and allow them to click on it to change it.
