### ISSUE TITLE
[MetaOS] Rename xdai chain to gnosis chain

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1170]
### What would you like to be added?

Replace ALL occurrences of names/logos/images/icons of "xdai chain" with "gnosis chain".

### Why is this needed?

xDai chain was recently renamed to Gnosis Chain. 
Read more: https://www.xdaichain.com/about-gc/news-and-information/xdai-gnosis-merger-ama

**Comment by HHH-GH** [comment]
Ahoy,

1. Would a search and replace through all the files be enough to find all the places that need to be changed? 
2. Are new logos/images/icons available, or would they need to be made?

I *think* I could do this work.

**Comment by HHH-GH** [comment]
I'll take this one.

I won't get on to it immediately, but if I don't see any objections/suggestions by the time I do get on to it I will proceed as follows:

1. Go through all the files that mention 'xdai' as per https://github.com/MetaFam/TheGame/search?p=1&q=xdai
2. Text updates/icon updates for things that appear on the frontend as text or icons.
3. No updates for things involved in the backend

At a quick glance, on the frontend there are just a few text updates, plus a new SVG icon and component to be created.

On the backend, I'm seeing stuff like `daoHausXdaiGraphqlURL` in [packages/backend/src/config.ts](https://github.com/MetaFam/TheGame/blob/306f7f0dd600d42ced90841f05c548000ba1093f/packages/backend/src/config.ts) - I'm not planning to touch any of that.

**Comment by dysbulic** [comment]
> On the backend, I'm seeing stuff like `daoHausXdaiGraphqlURL` in [`packages/backend/src/config.ts`](https://github.com/MetaFam/TheGame/blob/306f7f0dd600d42ced90841f05c548000ba1093f/packages/backend/src/config.ts#L61-L64) — I'm not planning to touch any of that.

I would think it's safe to change this to `daoHausGnosisGraphqlURL` and the associated environment variable to `$DAOHAUS_GNOSIS_GRAPHQL_URL` since the name of the chain housing the DAOHaus DAOs is Gnosis.

**Comment by dysbulic** [comment]
Another option is to write the DAOHaus Graphs as a single indexed object:

```typescript
  daoHausGraphQLURL: {
    mainnet: parseEnv(
      process.env.DAOHAUS_GRAPHQL_URL,
      'https://api.thegraph.com/subgraphs/name/odyssy-automaton/daohaus',
    ),
    polygon: parseEnv(
      process.env.DAOHAUS_POLYGON_GRAPHQL_URL,
      'https://api.thegraph.com/subgraphs/name/odyssy-automaton/daohaus-matic',
    ),
    gnosis: parseEnv(
      process.env.DAOHAUS_GNOSIS_GRAPHQL_URL,
      'https://api.thegraph.com/subgraphs/name/odyssy-automaton/daohaus-xdai',
    ),
  },
```

Then, if the GraphQL structure is the same, they could be easily iterated over, and adding new ones is simpler as well.

**Comment by HHH-GH** [comment]
I'll take a look to see how that all comes together, thanks. (Will probably do the easy frontend bits first)
