### ISSUE TITLE
[MyMeta] DAO memberships formatting "broken"

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1187]
### What happened?

With the latest change to the DAO membership section, it looks like its no longer aligned left & looks weird.
Continuing from discord:
![image](https://user-images.githubusercontent.com/55857222/157112395-53ad3311-eebf-4a22-9a18-cb8c07b69fe6.png)

### What did you expect to happen?

For it to stay the same

### How can we reproduce the problem (as minimally as possible)?

By going to the profile

**Comment by dysbulic** [comment]
Fixed by #1181.
