### ISSUE TITLE
[MyMeta] Profile Creation Flow Fixes & Updates

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1196]
I was showcasing MyMeta to the Seed Fund people yesterday & noticed some things off...
This issue includes things that should obviously be fixed but also some changes that are my personal suggestions which can be disregarded.

As usual, actually writing these things down turned out a lot more small issues than expected.
Should this issue be split into multiple?

Either way, I'm marking with "🚨" those that I think are crucial & urgent for the MyMeta product launch that was supposed to be this week but imo should be postponed at least a few days until some of these are solved.
But obviously, the more we can finish, the better.

- [x] 🚨 The progress bar is using the old logo, should be updated to [the new](https://discord.com/channels/629411177947987986/760181556765130752/952971204317294632)
- [x] 🚨 The progress bar indicator is already at 30% on step 1
- [x] I'd change "connect to progress" to "connect to continue" which sounds smoother imo.
- [x] I think it should say "Name" or at least "Nickname". Imo "Username" makes no sense as its not used to log in & also sounds kind of lame & we're trying to move away from this paradigm of people being just "users". For the sentence below, I'd write something more friendly-sounding like "Hey! What's your name? 🙃". And the field name should be changed accordingly.
- [x] When using uppercase, which isn't allowed, [the error isn't always clear](https://user-images.githubusercontent.com/55857222/158350508-e0284680-b334-49c0-9699-fed53198dd28.png)
- [x] Also, could we allow people use uppercase letters in their name?
- [x] 🚨🚨🚨 There is no "bio" step at all, for people to describe themselves.
- [x] Color Disposition
    - [x] The color disposition screen... Is called "color disposition" but the boxes aren't about colors. There's an issue about #1135 revisiting the quiz & whether it should remain about these descriptive words or actually go to colors, but until its resolved maybe it would be best to name the screen just "Personality Type".
    - [x] 🚨 On the colors disposition screen, the boxes [aren't all the same size](https://user-images.githubusercontent.com/55857222/158352504-4480b7e2-a8d4-4e27-ac42-84d2946bbce0.png)..
    - [x] 🎨 Maybe its just me, but I also think the drop shadow on icons takes away from the overall design & makes icons appear to be floating. Thoughts @davort?
    - [x] I'd change the text to "Please select what defines you. [Wtf is this](https://medium.com/human-parts/the-mtg-color-wheel-c9700a7cf36d)? Not sure what type you are? Take [a quick exam](https://dysbulic.github.io/5-color-radar/#/explore/) or [a longer quiz](https://dysbulic.github.io/5-color-radar/#/test/).
- [ ] The timezone screen let's you type but typing doesn't search or filter, doesn't seem to be doing anything. We should either make it search or not allow people to type at all.
- [ ] Roles, the role selection screen has multiple problems:
    - [x] 🚨 Upper row boxes are taller than bottom row
    - [x] 🚨 The content in the boxes isn't middle aligned (there's a bigger margin on the left, becomes more obvious after the "make primary" & "make secondary" buttons appear on the selected role cards)
    - [ ] 🎨 Secondary role appears below the primary role, which makes sense on mobile but doesn't look good & makes people scroll on desktop. If that was because player can choose as many secondary as they like, maybe it should be limited to 3 secondary or the "primary" indicator should be directly below the primary role card with others going to the right.
    - [x] 🎨 As far as I remember, the "Press Start" font was removed from everywhere else @davort?
    - [x] 🎨 The buttons should maybe be updated, [eg. black on hover on "make primary"](https://user-images.githubusercontent.com/55857222/158359560-c6e382db-f047-4308-bc30-f7310278bf15.png). Dave said he'll revisit this whole screen & how it should look on desktop.
    - [x] 🚨 I [updated the role descriptions](https://pastebin.com/mg9LLm5e) so they are more similar in size & less MetaGame-specific.
- [x] 🎨 Memberships screen.. Right now, this only pulls data from DAOhaus & discord servers of the guilds that the player is member of. **Since its 100% automatic, maybe unnecessary to have it as a step?** On the other hand, it would be cool to let people add their own things. We'll need a design for this, but my suggestion is to allow people to type in whatever they want, just add a big ass "NOT VERIFIED" indicator. There could also be a sentence saying something like "Your DAOhaus & guild memberships are automatic. You are free to add others but they will appear as "NOT VERIFIED". If you want them to be verified, try getting the project to [join MetaGame](https://my.metagame.wtf/join/guild).
- [x] 🚨 Player Type screen shouldn't be here at all since player types are no longer displayed on profiles after their usecase was replaced with colors.
- [x] Pronouns, it felt kind of cringe showing this step to investors yesterday & tbh I'd remove it from the creation flow to have it as an optional thing for people to add when editing their profile, as most people really don't care about this & makes them go err...
- [x] The final step of the creation flow takes the [progress bar to the end of section 3](https://user-images.githubusercontent.com/55857222/158363839-5594b39c-eac1-41eb-8ff7-0fd7daceba52.png). Section 4 is completely unused. Imo, we should just get rid of it & have the creation flow contain only 3 sections.

**Comment by pvblick-vniversal-friend** [comment]
Some issues that I have experienced by testing MyMeta:

- [ ] **Cannot change profile information:** I cannot change my display name and other basic profile info. Whenever I do and save the changes, each time I refresh the page the information revert back to a state before the changes. For example my display name is Test and I cannot change it. I wne and redid the new profile wizard but it still stays this way.
I had made the profile before even the Ceramic integration so I guess this is what might be causing the issue. Re-doing the wizzard doesn't really change the information. It seems like it has been hardcoded into my IDX.

**Comment by vidvidvid** [comment]
@peth-yursick 
> Player Type screen shouldn't be here at all since player types are no longer displayed on profiles after their usecase was replaced with colors.

It hasn't been replaced, it's just hidden by default. But i removed the step 👍

**Comment by luxumbra** [comment]
@vidvidvid what branch are you guys using?

**Comment by vidvidvid** [comment]
ohhh damn sorry @luxumbra i forgot to send it to you. it's this one: https://github.com/MetaFam/TheGame/tree/fix/ui-content-improvements

**Comment by luxumbra** [comment]
thank you

**Comment by peth-yursick** [comment]
> Some issues that I have experienced by testing MyMeta:
> 
>     * [ ]  🚨 **Cannot change profile information:** I cannot change my display name and other basic profile info. Whenever I do and save the changes, each time I refresh the page the information revert back to a state before the changes. For example my display name is Test and I cannot change it. I wne and redid the new profile wizard but it still stays this way.
>       I had made the profile before even the Ceramic integration so I guess this is what might be causing the issue. Re-doing the wizzard doesn't really change the information. It seems like it has been hardcoded into my IDX.
> 
>     * [ ]   **The "Embed URL" block isn't working:** I tried putting various links (homepages, social media accounts etc) but none of the URLs I have put thus far work. I am left out with an empty blank box.

Embed URL works for me but confirming changing the name doesn't work for me either..
Same seems to be true for rearranging blocks in the layout. Seems to work after you click save, back to default after refresh @dan13ram 

> Nope, there are still some cases where it's used - for example in some titles. I can remove it completely tho. 4 ever.

Up to @davort I guess. The role select screen will need to be designed for desktop as afaik the current desktop version was made according to the mobile version design.

**Comment by peth-yursick** [comment]
> Something I have noticed is the lack of open graph data for https://metagame.wtf when pasting the url in social apps, now the root domain is pointing to the new landing page. Could we also add this to the list? I'll do it if someone can point me in the right direction. Which brings me to...

I don't get this bit. Isn't the root domain supposed to point to the new landing page?

But it reminds me that pasting the link into social apps always brings up this old logo & default description no matter what page is shared..
![image](https://user-images.githubusercontent.com/55857222/158806230-dbbb0b6a-9f74-46a3-a3b6-66392ba96e7e.png)

**Comment by luxumbra** [comment]
> I don't get this bit. Isn't the root domain supposed to point to the new landing page?

Yes it should but it was still going to the wiki until yesterday and www wasn't going anywhere. Both are fixed now and going to the new landing page.  

> But it reminds me that pasting the link into social apps always brings up this old logo & default description no matter what page is shared..

And that is what i was on about with the Open Graph tags. We need to get them updated. I have asked @vidvidvid to direct me to where they live.

**Comment by davort** [comment]
Apologies for the wait. Here are my thoughts on matters where I was asked to chime in;
> 🎨 Maybe its just me, but I also think the drop shadow on icons takes away from the overall design & makes icons appear to be floating. Thoughts @davort?

I would agree that the shadow doesn't make the design any better, and therefore should be removed 👍

. . .

>  🎨 As far as I remember, the "Press Start" font was removed from everywhere else @davort?

Not quite from everywhere. We agreed—albeit only "verbally"—to retain it in the onboarding screens. If there are good reasons to remove it altogether, we can do that. Perhaps with the new logo and landing page, "Press Start" doesn't make for the best fit any longer, as it did with the previous version of the website. 

Should we decide to replace it with Exo2, I would recommend these properties for the headlines:
`
font-size: var(--chakra-fontSizes-5xl);
font-weight: 700;
letter-spacing: 0.025em;
` 

Here's how that would look like, compared to current setup:
![font-comparison](https://user-images.githubusercontent.com/1573304/159114472-e56720a2-d8a7-4307-8175-dd57165d1389.png)

**Comment by peth-yursick** [comment]
> Here's how that would look like, compared to current setup:

It actually already looks like that already.. Maybe just less bold? Also love it without shadows.
![image](https://user-images.githubusercontent.com/55857222/159118807-ba181b3b-16fd-490d-9bde-22a07b76359c.png)
As far as I've seen, its not currently in any of the profile setup screen except for these "primary role" & "secondary roles" bits 
![image](https://user-images.githubusercontent.com/55857222/159118788-14fc6d02-5ca6-4db8-947f-be05bcdea9c2.png)

**Comment by davort** [comment]
### Re: buttons
> 🎨 The buttons should maybe be updated, [eg. black on hover on "make primary"](https://user-images.githubusercontent.com/55857222/158359560-c6e382db-f047-4308-bc30-f7310278bf15.png). Dave said he'll revisit this whole screen & how it should look on desktop.

I have styled the "Secondary button" component and all its variants (sizes, states, with/without icons). 
Please find these styles here: https://www.figma.com/file/PQALIZcBBJHqEmisXSJIbu/MetaGame-UI-Pattern-Library?node-id=304%3A41

I will style the Primary button in the same file, linked above, ASAP.

**Comment by davort** [comment]
> > Here's how that would look like, compared to current setup:
> 
> It actually already looks like that already.. Maybe just less bold? Also love it without shadows.

Let's have the headings as I suggested in https://github.com/MetaFam/TheGame/issues/1196#issuecomment-1072971208 and icons without shadows.

. . .

> ..."primary role" & "secondary roles" bits (which also happens to be the page that would benefit most from some design touchups)

Perhaps we can just retain the mobile layout and do something like this?
![selected roles](https://user-images.githubusercontent.com/1573304/159131377-5e52e3bb-eeac-45d4-b14e-1ae0206f10ef.png)

The whole array of layouts for different breakpoints is available on this Figma link: https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=8804%3A27021

**Comment by davort** [comment]
> 🎨 Memberships screen..

In the interest of keeping onboarding simple, I'd suggest having this as a **Profile page feature** instead. So, after the onboarding is over, and thus outside of scope for this push. If you agree with that, let's turn this into a separate ticket, and have approach solving it in a bit more structured manner.

> Since its 100% automatic, maybe unnecessary to have it as a step?

Agreed on this one!

**Comment by peth-yursick** [comment]
Great, thank you!

> Perhaps we can just retain the mobile layout and do something like this?

I liked it much better with descriptions & big emojis we could later replace with cool illustrations. 
But guess there's simple way to not require users to scroll down for "next" but still retain bigger graphics & descriptions? Maybe only allow 1 primary & 2 secondary?
Either way probably good enough for now 🤷‍♂️

**Comment by davort** [comment]
> Great, thank you!
> 
> > Perhaps we can just retain the mobile layout and do something like this?
> 
> I liked it much better with descriptions & big emojis we could later replace with cool illustrations. But guess there's simple way to not require users to scroll down for "next" but still retain bigger graphics & descriptions? Maybe only allow 1 primary & 2 secondary? Either way probably good enough for now 🤷‍♂️

Sure there is – put it in a "sticky"—a.k.a. "fixed"—footer, so that it's always in view, while the content scrolls underneath it 😊 Same way we do it for mobile!

But please, in that case let's also make those cards look like they do in the original design: https://www.figma.com/file/rK3YRbHlUNme7PGb3kFjS3/Meta-Game-(Copy)?node-id=8235%3A43441

Example:
![fixed footer Next btn](https://user-images.githubusercontent.com/1573304/159134234-cd133a19-5fe0-46f7-baac-1d932ec220e8.png)

**Comment by vidvidvid** [comment]
o/ i fixed the last couple of issues - made the role cards smaller, fixed the hover on make primary/secondary role, renamed membership step, renamed some stuff that still had to be renamed, removed shadows from player type icons. pls check if everything's fine @davort @peth-yursick once the branch gets deployed! (in 15 mins or so)

**Comment by vidvidvid** [comment]
will be available here: https://the-game-git-fix-ui-content-improvements-metafam.vercel.app/

**Comment by vidvidvid** [comment]
merged the PR - the changes should be reflected on https://test.metagame.wtf/ very soon. imo we can close this issue and have it as a reference when we open any new issues that might stem from this list & discussion.

**Comment by davort** [comment]
Nice job @vidvidvid !
I just noticed these two details on the Role Selection step:
![CleanShot 2022-03-20 at 21 10 29](https://user-images.githubusercontent.com/1573304/159184096-a58bcd9f-c5cd-4f04-9a61-1765159d2229.png)

- legacy typeface
- image wouldn't load for me (Patrons)

Other than that, really nice!

**Comment by vidvidvid** [comment]
@davort that's really weird, since I wrote the migration which @peth-yursick suggested with new descriptions and Patron being renamed to Fundster. i will check it.

**Comment by peth-yursick** [comment]
Name seems to still only allow lowercase:
![image](https://user-images.githubusercontent.com/55857222/159239920-5002e735-4d05-44a6-82c8-55b715c74f6a.png)

> @davort that's really weird, since I wrote the migration which @peth-yursick suggested with new descriptions and Patron being renamed to Fundster. i will check it.

Yeah, looks like all old descriptions.. Btw the reason I renamed Patron to Funder is because selecting these will be used to set your roles on discord as well, so it made more sense for people to be able to signal they're interested in being a Funder than actually select it without 8pSeeds.
Also still goes beneath & pushes "next" button to scroll..



> Sure there is – put it in a "sticky"—a.k.a. "fixed"—footer, so that it's always in view, while the content scrolls underneath it 😊 Same way we do it for mobile!

I like this solution, would also make the button fixed on the same position on every screen vs. now, where it moves up or down depending on content on each screen.

**Comment by vidvidvid** [comment]
@peth-yursick you named it `Fundster` in the doc. So what do you want it to be called now - Funder of Fundster?

**Comment by peth-yursick** [comment]
> @peth-yursick you named it `Fundster` in the doc.

Yes, Patron became Fundster for that reason

**Comment by vidvidvid** [comment]
@peth-yursick but you're naming him `Funder` in your previous comment. so i'd like a confirmation which one you want :) `FundSTer` or `Funder`

**Comment by pvblick-vniversal-friend** [comment]
### Does changing "Page Background" do anything at all?
