### ISSUE TITLE
Display current season label dynamically

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1209]
### What happened?

Currently, the current season is calculated on the backend, but the label is hardcoded on the frontend, such that it still displays "Season V" even though we're in Season 6.

### What did you expect to happen?

It says "Season 6"

### How can we reproduce the problem (as minimally as possible)?

https://metagame.wtf/community/players

**Comment by dysbulic** [comment]
There are unicode Roman numerals through 12 & I think we ought to keep using them.

Ⅰ, Ⅱ, Ⅲ, Ⅳ, Ⅴ, Ⅵ, Ⅶ, Ⅷ, Ⅸ, Ⅹ, Ⅺ, & Ⅻ.

**Comment by arsenijesavic** [comment]
@dysbulic I picked this issue as the first contribution but I just saw that you already changed it, however, it still not calculating season on the backend. I am currently familiarizing myself with the repo, but I could not find a way to retrieve the season number from the backend?
