### ISSUE TITLE
[MyMeta] Fix dashboard issues

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1224]
- Watch tab shows nothing
![Screenshot from 2022-03-30 21:18:21](https://user-images.githubusercontent.com/10012209/160876943-6215640d-ef65-40e6-93e6-aa6b1ed1e32e.png)

- Don't show XP if there's nothing to display
![Screenshot from 2022-03-30 21:18:29](https://user-images.githubusercontent.com/10012209/160877018-908de5c9-68ac-41fa-9e07-1687edf803ae.png)

**Comment by alalonde** [comment]
@arsenijesavic Turns out that the Youtube API Key didn't have enough whitelisted HTTP Referers. I added entries for metagame.wtf and our a.run.app GCP PR deployments
