### ISSUE TITLE
[MyMeta] Custom colors, transparency & blur

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1229]
### What would you like to be added?

Primarily, the ability for people to change the color scheme on their profiles.

But also, as people are allowed to change the background image (#443) & the color scheme of the boxes, it would be good to also allow them to set custom transparency & blur levels for the boxes.
I have no idea how complicated that is, so maybe just completely ignore the idea & I'll open a separate issue at some point in the future.

### Why is this needed?

From the beginning the idea was to make MyMeta really as customizable as possible so people can really personalize it to their own taste, but it would also help guilds as it would be more "whitelabelable".

**Comment by dysbulic** [comment]
Currently most of the theming is on the components being inserted and explicitly refers to certain colors.

Switching to a more general expressions of colors, as described in #1157, would make themability easier.

**Comment by dysbulic** [comment]
The work of extracting the theme information is underway in #1418.
