### ISSUE TITLE
[MyMeta] Profile verification & connection

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1231]
### What would you like to be added?

Basic self.id profiles have the ability to verify other accounts such as Twitter & Github but we don't.
It would be great to have this "connect your other profiles" also in the creation flow, maybe as the final step?

### Why is this needed?

Its important for people to be able to connect their other profiles, firstly so that they can actually be contacted as MyMeta offers no way to get in touch with someone but also to prevent impostor scammer attacks.
Its a basic feature of self.id & we should probably have it too.

**Comment by dysbulic** [comment]
When connecting an account. a user creates an artifact in the target system containing their DID (i.e. a gist on GitHub or a tweet on Twitter.)

[IdentityLink](//github.com/ceramicstudio/identitylink-services/) is a set of serverless functions that checks those artifacts and creates a signed attestation that it viewed them. These serve as the basis for verifying account ownership.

The copy of IdentityLink running for [self.id](//self.id) only currently works for GitHub. If we want to add account verification to our system & support other account types, we'd need to be running IdentityLink ourselves.

Setting this up, and, hopefully investigating running it on Google's infrastructure so we don't have multiple providers to worry about, is no small talk.

**Comment by peth-yursick** [comment]
> The copy of IdentityLink running for [self.id](//self.id) only currently works for GitHub. If we want to add account verification to our system & support other account types, we'd need to be running IdentityLink ourselves.
> 
> Setting this up, and, hopefully investigating running it on Google's infrastructure so we don't have multiple providers to worry about, is no small talk.

Would be awesome to at least have github & twitter, don't really care about others that self.id doesn't support out of the box tho discord would be cool. But you're saying it only works for github & not for twitter?
Even just linking to self.id for that step temporarily would work, as long as there's *some* way to get to it as there is currently none..

**Comment by Seroxdesign** [comment]
Closed because outdated.

**Comment by peth-yursick** [comment]
sounds good, merged useful part of the idea into #1512
