### ISSUE TITLE
[MyMeta] Moving stats to another card

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1232]
We started with having player cards in the aspect ratio of business cards or playing cards but adding more & more info to player cards is making them longer & longer.
An example:
![image](https://user-images.githubusercontent.com/55857222/162431576-4ef135aa-d009-44f7-b822-1fd1ca4c888f.png)

I'm not a designer so maybe I'm completely wrong here but imo this makes them look ugly & confusing as to what's actually the most important info about someone..

My suggestion would be to have:
- Avatar
- Name
- Bio
- Links to other profiles
- Colors (merge from separate)
in the main card and move everything else into a new "Stats" or "Other info" card below.

**Comment by Seroxdesign** [comment]
What a shame how much the development deviated from the design on this one.
