### ISSUE TITLE
[MyMeta] Upgrade the single page profile edit - design

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1233]
The single page edit was built without any design work & currently seems like the weakest part of the profiles in terms of the design:
![image](https://user-images.githubusercontent.com/55857222/162518428-94721d69-0880-4bff-978d-f83e3845f835.png)

I posted this in the designers guild but also opening an issue here to make sure we don't forget.
Correct me if I'm wrong but should be a good first issue once the design is ready?

**Comment by alalonde** [comment]
Changing this will likely be a part of the ComposeDB upgrade, since we will probably be saving fields individually (or at least corresponding to the ComposeDB model).

**Comment by davort** [comment]
Hey @alalonde - how fast have you come with implementing the designs? Figma file: https://www.figma.com/file/EiHj37NB69lYus4bGliHRb/Edit-profile?node-id=0-1

**Comment by alalonde** [comment]
Nothing yet. I'm still focusing on getting the `composedb` branch back to feature parity. There were a lot of changes there and it still requires much testing. Unfortunately we probably don't want to tackle this until that branch has been merged, as there would be a lot of conflicts.

**Comment by davort** [comment]
@alalonde - do you think you are close to being able to get back to this issue?

**Comment by alalonde** [comment]
Sero will be doing the development for this; See the [linked issue](https://github.com/MetaFam/TheGame/issues/1546) which represents that portion of work

**Comment by alalonde** [comment]
Dave's latest https://www.figma.com/file/EiHj37NB69lYus4bGliHRb/Edit-profile?type=design&node-id=13-403
