### ISSUE TITLE
[Landing Page]: Add links to our major properties to the front page

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1236]
### What would you like to be added?

Currently, [metagame.wtf](//metagame.wtf) is geared entirely to first time visitors. Returning users who have already seen the slideshow have to click three or four times at least to get to our staple services.

I would like to remove the text "Follow Us" from the right-hand side of the front page (you don't have to explain the Twitter icon, people know it), and add three icons linking to [a user's personal profile](//metagame.wtf/me), [the leaderboard](//metagame.wtf/players/), & [the dashboard](//metagame.wtf/dashboard).

We'd need to decide on icons to represent each of these, but having a logo for them wouldn't be a bad idea in general.

### Why is this needed?

It takes too long to get anywhere in the site without typing, and many users don't have the URLs memorized anyhow.

**Comment by dysbulic** [comment]
Another feature you might add while doing this is to add [`Tooltip`](https://chakra-ui.com/docs/components/overlay/tooltip)s to the icons. Something like: `<Tooltip label='Dashboard' hasArrow placement='left'>…`.

**Comment by ChariotDigital** [comment]
I'm going to take a crack at this as my first issue, ill keep you all updated!

**Comment by luxumbra** [comment]
Thanks for picking this up @ChariotDigital. I like @dysbulic's suggestion of adding `Tooltip` 👍🏻

**Comment by vance4243** [comment]
I would like to add, that I could not find a way to get back to the Dashboard, once I went to any subpage, except writing /dashboard in the url. I would propose to link to https://metagame.wtf/dashboard on the Meta Symbol on the upper left hand side, as a start. (Instead of the landing page)

**Comment by dysbulic** [comment]
> I would propose to link to https://metagame.wtf/dashboard on the Meta Symbol on the upper left hand side, as a start.

The dashboard isn't really central enough to the application to be the destination of the home page link, in my opinion. Since you're linking to the dashboard from the landing page, users will be able to get to it with two clicks.

Currently when a user is authenticated there's a link to the dashboard under the menu you get by clicking on your profile icon. This was because several aspects of the dashboard are customized to a logged in user.

**Comment by dysbulic** [comment]
> Considering @dysbulic said that you don't have to explain the Twitter icon, we don't want these on the social icons correct?

@ChariotDigital, I'd probably put them on everything for consistency sake. I was moreso meaning we don't need the "Follow Us" text. It won't hurt to give people some extraneous info about the links. It's possible someone won't recognize GitHub or Discord.

Also, if you use `Box`es rather than `span`s, does it render correctly? It's better to keep it all Chakra-based if that's possible.

**Comment by ChariotDigital** [comment]
Thanks, @luxumbra @dysbulic This is my first time using Chakra so I wasnt aware of `<Box>`. I'll add those into the PR

**Comment by alalonde** [comment]
This was taken care of with #1291
