### ISSUE TITLE
[Guilds] Guild member sync is broken

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1239]
### What happened?

I approved TEC's guild application, which should have triggered a sync where we associate their members from Discord with our players.  This did not happen.

### What did you expect to happen?

 A sync

### How can we reproduce the problem (as minimally as possible)?

Go to https://metagame.wtf/guild/TEC. You can also trigger a sync through the hasura console.

**Comment by alalonde** [comment]
This seems to still be an issue, at least with the TEC:

```
Apr 26 10:46:52 AM  DiscordAPIError: Missing Access    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)    at async GuildManager.fetch (/app/node_modules/discord.js/src/managers/GuildManager.js:288:20)    at async syncGuildMembers (/app/packages/backend/dist/handlers/triggers/syncDiscordGuildMembers.js:69:26)    at async syncDiscordGuildMembers (/app/packages/backend/dist/handlers/triggers/syncDiscordGuildMembers.js:13:13)    at async triggerHandler (/app/packages/backend/dist/handlers/triggers/handler.js:22:9) {
Apr 26 10:46:52 AM    method: 'get',
Apr 26 10:46:52 AM    path: '/guilds/810180621930070088?with_counts=true',
Apr 26 10:46:52 AM    code: 50001,
Apr 26 10:46:52 AM    httpStatus: 403,
Apr 26 10:46:52 AM    requestData: { json: undefined, files: [] }
Apr 26 10:46:52 AM  }
```

**Comment by alalonde** [comment]
The issue here is permissions. If the "membership" role is greater than the bot's own role in the server, we don't have visibility into that role for any of the server's members.

**Comment by peth-yursick** [comment]
> The issue here is permissions. If the "membership" role is greater than the bot's own role in the server, we don't have visibility of that role for any of the server's members.

And guessing its the same for admins? Making it impossible for admins to actually edit the guild pages?

**Comment by alalonde** [comment]
> > The issue here is permissions. If the "membership" role is greater than the bot's own role in the server, we don't have visibility of that role for any of the server's members.
> 
> And guessing its the same for admins? Making it impossible for admins to actually edit the guild pages?

No, actually. All of that data (besides the selected Discord roles) are only saved in our DB.  This is always a moving target though and should be re-tested.

**Comment by peth-yursick** [comment]
> > > The issue here is permissions. If the "membership" role is greater than the bot's own role in the server, we don't have visibility of that role for any of the server's members.
> > 
> > 
> > And guessing its the same for admins? Making it impossible for admins to actually edit the guild pages?
> 
> No, actually. All of that data (besides the selected Discord roles) are only saved in our DB. This is always a moving target though and should be re-tested.

Gotcha. So the guilds that connected their discords should already be able to edit their profiles themselves?

**Comment by alalonde** [comment]
Yes, that’s right

**Comment by alalonde** [comment]
Looking into this again; seeing this error now

```
 Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
Dec 1 05:00:50 PM      at Timeout._onTimeout (/app/node_modules/discord.js/src/managers/GuildMemberManager.js:454:16)
Dec 1 05:00:50 PM      at listOnTimeout (node:internal/timers:559:17)
Dec 1 05:00:50 PM      at processTimers (node:internal/timers:502:7) {
Dec 1 05:00:50 PM    [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
Dec 1 05:00:50 PM  }
```

**Comment by peth-yursick** [comment]
> Looking into this again; seeing this error now
> 
> ```
>  Error [GUILD_MEMBERS_TIMEOUT]: Members didn't arrive in time.
> Dec 1 05:00:50 PM      at Timeout._onTimeout (/app/node_modules/discord.js/src/managers/GuildMemberManager.js:454:16)
> Dec 1 05:00:50 PM      at listOnTimeout (node:internal/timers:559:17)
> Dec 1 05:00:50 PM      at processTimers (node:internal/timers:502:7) {
> Dec 1 05:00:50 PM    [Symbol(code)]: 'GUILD_MEMBERS_TIMEOUT'
> Dec 1 05:00:50 PM  }
> ```

"members didnt arrive in time" 🤣
Is it throwing that for every guild? Might it have to do with the fact a lot of them never asked their members to create profiles?

**Comment by dysbulic** [comment]
#1517 adds better errors to the Discord and SourceCred syncing tasks. It now outputs:

```
Error syncing Discord guild memberships: Failed to sync 6 guilds:
Error: Quest Chains: Guild Quest Chains has no membership roles.
Error: CRΞ8R DAO: Guild CRΞ8R DAO has no membership roles.
Error: Giveth: Unknown Guild
Error: GRDN (🌎, 🌍, 🌏): Guild GRDN (🌎, 🌍, 🌏) has no membership roles.
Error: dOrg: Guild dOrg has no membership roles.
Error: Token Engineering Commons: Unknown Guild
```

So, TEC is failing because their guild id is invalid. *(How that happens, I don't know. Any ideas @alalonde?)*

The "members didn't arrive in time" error is a transient timeout.

**Comment by Seroxdesign** [comment]
Duplicate issue.
