### ISSUE TITLE
Podcasts mention, add link to podcasts

### ISSUE THREAD

**Issue by tommycomma** [MetaFam/TheGame#1253]
### What would you like to be added?

[https://metagame.wtf/#what-do](url)
On this page, where it mentions Podcasts.. I suggest we add a link direct to our podcasts.

for example, 
[https://anchor.fm/metagame](url)

### Why is this needed?

Ease of access.  Marketing.  Added avenues to the rabbitholes.

**Comment by peth-yursick** [comment]
an issue for https://github.com/MetaFam/metagame-wiki/ but fixed! Thank you
