### ISSUE TITLE
Metagame.wtf: Players - After I came back from a player's profile, my filter was gone.

### ISSUE THREAD

**Issue by vance4243** [MetaFam/TheGame#1267]
### What happened?

On the https://metagame.wtf/players page: I sorted the players by Username (A-Z), scrolled down and clicked on a profile. When I went back to the list of players, my filter was gone and I was put to the beginning of the page.

### What did you expect to happen?

Continue scrolling through the sorted Players from where I stopped.

### How can we reproduce the problem (as minimally as possible)?

1. Got to https://metagame.wtf/players.
2. Sort by Username (A-Z).
3. Scroll down and click on a profile.
4. Go back to list of Players

### Browser and operating system used (if applicable)

Firefox, Win 11

**Comment by vance4243** [comment]
When I open the Timezone filter and try to click on some Timezone in the lower part, the Player underneath the menu gets opened.

**Comment by alalonde** [comment]
Yes, the solution to this is to update the URL when filters are applied; essentially storing the filter state in the the URL. This way back/forward functionality works as expected
