### ISSUE TITLE
metagame.wtf/start: My Firefox doesnt render the "Back to top" mechanic properly

### ISSUE THREAD

**Issue by vance4243** [MetaFam/TheGame#1277]
### What happened?

On the metagame.wtf/#start page scrolling only works on the edges and there are some render issues as seen in the attached image
![startpage](https://user-images.githubusercontent.com/96993195/170837268-0757158e-ed1f-483c-b0ca-e45514a19058.png)
.

### What did you expect to happen?

No big pink Arrow, Button border only around a well aligned "Back to top" Button.
No scrolling issues.

### How can we reproduce the problem (as minimally as possible)?

1. open metagame.wtf
2. Try scrolling down.

### Is there anything else we need to know?

Maybe the problem has to do with my Firefox Version (100.0.2) with is currently the latest.
Changing the size of my browser window changes the position of "Back to top".

### Browser and operating system used (if applicable)

Win 11, Firefox

**Comment by alalonde** [comment]
This is a regression; I saw and fixed this at some point before: https://github.com/MetaFam/TheGame/commit/56e6c8a9e01f0fa39f93965543610d237058c366
