### ISSUE TITLE
[Quests] More info & formatting of quest completions via give-props

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1286]
### What would you like to be added?

Some ideas for improving on the quest completion bridging to give props...
- Adding "effort" field to the submissions
- Adding "impact" field for quest givers to add when accepting a quest submission
- Bridge both of those fields as well as the "attachment" field to discord
- Format like in didathing

### Why is this needed?

It would make the quests more legible & aligned with how people currently post quest completions in #didathing.
People in #didathing generally get more XP than in #give-props. Assuming this is because things in didathing have more info attached to them that make it easier to understand as well as the emoji numbers to click, this would solve both.

**Comment by alalonde** [comment]
So after a submission it accepted, you want to use the "didathing" post template for the post to #give-props?

**Comment by peth-yursick** [comment]
> So after a submission it accepted, you want to use the "didathing" post template for the post to #give-props?

Should be a part of the submission imo, adding more boxes to the submission form
Might be easier for quest giver to determine the impact, then again, the impact depends on the person who completes it - eg. impact of a Playbook is totally dependent on the writer, not the fact its a playbook..

**Comment by Innkeeping** [comment]
did-a-thing and give-props are no longer used.
