### ISSUE TITLE
[MyMeta] Guild profile images not queried & page format not aligned with player profiles

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1287]
Guild profiles don't seem to be pulling in guild avatars. Not sure if this is true only of discord-based guilds or affecting some others as well but seems that for discord-based ones it doesn't work for sure.

Other than that, it would be good if guild profiles were formatted in the same way as player profiles.
Right now, guild page boxes may be hardcoded like player ones were before.

Player profiles:
![image](https://user-images.githubusercontent.com/55857222/171993075-5cb6a761-720a-4d11-bdcc-80a3ca955d7a.png)
Guild profiles:
![image](https://user-images.githubusercontent.com/55857222/171993098-d2b48d79-a7f3-4430-a702-93b1e8169b1a.png)

**Comment by alalonde** [comment]
I think the issue here is that we are just hot-linking to guilds' logo images, so we have no recourse if e.g. the filename changes, the URL changes, etc. The Discord ones mostly do work, e.g. Opolis, Bloom

**Comment by dan13ram** [comment]
Reopening since there is still the issue of Guild Logos, which is fixed in #1367

**Comment by peth-yursick** [comment]
> Reopening since there is still the issue of Guild Logos, which is fixed in #1367

Didn't get this last bit "its still the issue, which is fixed"? 😂
I planned on manually uploading all guild logos to hasura today along with adding more links & info to each guild page and create a few of the missing guild pages (Atlantis World, Ark, Safary, rnDAO, YapDAO, Liminal Village, DAOhaus, Ethernaut DAO)..
Would be awesome to not have to do each of these steps manually
