### ISSUE TITLE
[Dashboard] Quests appearing on the dashboard

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1310]
### What would you like to be added?

Right now, I have 15 quests live. If I want to check if anyone applied for quest completions, I need to go under quests & open each of them separately to see..
- If a user has posted a quest, there should be a block on the dashboard displaying applicants for quest completions.
- If a user has accepted or completed a quest, there should be a block on the dashboard displaying quests.
Longer term, there should probably be some kind of a notifications aka "journal" system but I think adding a block to the already existing dashboard is a good enough solution for now.

### Why is this needed?

So it stops being cumbersome & it becomes more likely that people will notice whats going on with their quests.

**Comment by alalonde** [comment]
Not sure if the dashboard is the right spot for this. It is a pretty squished layout that needs to show a fair amount of data.

I am thinking of adding a separate page  `/quests/activity` with the following potential two blocks of content:

1. (if you have created at least one quest)
### Your quests
- <quest name> <proposal-by> 

2. (if you have submitted at least one proposal
### Your quest proposals
- <quest name>

**Comment by luxumbra** [comment]
> I am thinking of adding a separate page /quests/activity with the following potential two blocks of content:

I agree it deserves a page to itself but can see the usefulness of having a block on the dashboard to give a summary of that info.  For some, i'd say it is more helpful to a user to see quests than the current leaderboard and prolly needs to be a block you can add if you want it. 

@peth-yursick what are your thoughts?

**Comment by alalonde** [comment]
OK, turns out we already have a "Completed Quests" block that a player can add to their profile page. 

Really, here we want two new types of Dashboard blocks:
- Created Quests
- Completed Quests

We could pretty easily repurpose the current "Completed Quests" block to go on the dashboard (without the current filtering for only accepted quests).

**Comment by peth-yursick** [comment]
Hey @alalonde, this included "quests I proposed to" not just "quests I posted", right?

**Comment by alalonde** [comment]
Yes, there are two different blocks
