### ISSUE TITLE
[Quests] Integrate miro raids board directly into MetaOS

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1312]
### What would you like to be added?

Right now, clicking "raids" takes people into the wiki page called "raids" which has a miro board integrated.
Instead of doing this, the miro board should be integrated to open directly under the megamenu in full size.
Also, there's [a new miro board](https://miro.com/welcomeonboard/WlF4cXNhMXFsRUJvNmE1a0ExZnYzRkc1NFBUUmhoS3pyWVA2bGlHM3pja0w2bWxSU2NWUzFzZ2l0d2J4c1hGMnwzMDc0NDU3MzQ2NzQ4MzczNDYz?share_link_id=49268017545) for season 7 (wiki page is still on season 4 or 5 😬)

Note: this would still be a temporary solution until #642 is completed. If you are able to do #642 instead, would probably be worth doing that.

### Why is this needed?

Right now there's an unnecessary extra step which makes it load slower & look uglier.
The UX could be significantly improved by implementing this simple change.

**Comment by HHH-GH** [comment]
@peth-yursick   I'm looking at this one - some quick questions

**Currently it's like this:**  
- Contribute > Raids goes to https://wiki.metagame.wtf/docs/enter-metagame/navigation-board

**It should be like this:**  
- Contribute > Raids goes to https://metagame.wtf/raids
- And on that .wtf/raids page the Miro board is embedded

**Also**  
What happens to the old page at https://wiki.metagame.wtf/docs/enter-metagame/navigation-board?

**Comment by peth-yursick** [comment]
Omg thank you, this is probably the highest difficulty to impact ratio issue, it pains me its been open for so long & hard to tell how many newbies were turned away by our seasons outdated raids page 😅

Sounds good!
I'll remove the old page along with a bunch of other pages next week when updating the wiki for the 1.0 launch.

**Comment by HHH-GH** [comment]
I had a quick browse of the code - shouldn't be tough to finish.

Is there going to be a new Miro board for Season 8? 

Drop the link if yes, otherwise I'll use the [Season 7 board](https://miro.com/app/live-embed/o9J_l7FjYfU=/).

**Comment by peth-yursick** [comment]
Yeah sounds good, I'll just rename & update it when we enter Phase 8 so we dont have to replace this link every season..
