### ISSUE TITLE
New guilds conversion/signup page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1340]
Need someone to build the new guilds conversion/signup page so we can evolve from the [current one](https://my.metagame.wtf/join/guild) with an ugly block of text into a [new, prettier & more enticing version](https://www.figma.com/proto/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=5853%3A4465&scaling=scale-down&page-id=5836%3A3265).

If anyone is interested in working on it, pls comment here & I'll assign you.

Infographic exported as an image to make it easier:
![Group 1005](https://user-images.githubusercontent.com/55857222/193263081-c12059a4-ac08-44b8-b9a2-496f37a2302e.png)

**Comment by HHH-GH** [comment]
Taking this one ✌

(Although I might need some help if we need to get into some GraphQL)
