### ISSUE TITLE
Build the Patrons conversion page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1341]
Need someone to build the [Patrons conversion page](https://www.figma.com/proto/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=5883%3A4038&scaling=scale-down&page-id=5836%3A3265).

Previously inexistent, the patrons page should help us funnel & convert new patrons.

Infographic exported as image to make it easier:
![Group 1004](https://user-images.githubusercontent.com/55857222/193263147-bb24176a-8a2b-4c66-b7ab-70ee1a6c4c2e.png)

If anyone is interested in working on it, pls comment & I'll assign you :).

**Comment by kon-rad** [comment]
hey I'm interested in taking this on!

**Comment by peth-yursick** [comment]
> hey I'm interested in taking this on!

Hey, great to hear! I have assigned you to this issue but lets also connect on discord. What's your handle there?

**Comment by kon-rad** [comment]
I messaged you on discord

**Comment by alalonde** [comment]
@kon-rad pSeed price is now available through a graphql query https://github.com/MetaFam/TheGame/pull/1364
