### ISSUE TITLE
[Dashboard] Persist dashboard layout changes to hasura

### ISSUE THREAD

**Issue by dan13ram** [MetaFam/TheGame#1347]
### What would you like to be added?

We need to store the json object that represents the current user's dashboard in their player row on our database. 

This can be implemented in a similar manner to how the player's profile layout is persisted in the database.

### Why is this needed?

Currently the dashboard layout is stored in the local storage, and is lost if user deletes local storage or tries to access their dashboard on another browser. Thus, we should persist it so the user sees the same dashboard when logging in from any device.

**Comment by dan13ram** [comment]
@peth-yursick this is already in production. Is there anything missing or can we close this ?

**Comment by luxumbra** [comment]
I don't know when it happened but the dashboard is broken on mobile to the point it is unusable. I have been trying to debug and fix all morning but no luck so far. The XP block is getting an infinitely growing height from somewhere.

![image](https://user-images.githubusercontent.com/780350/194707165-e4e856b7-f7c2-45ad-afb2-56640194e0c9.png)

![image](https://user-images.githubusercontent.com/780350/194707148-213b9f84-065d-47eb-b191-ce6cd5f21d73.png)
![image](https://user-images.githubusercontent.com/780350/194707157-34ccd5b8-cee8-4c93-99a7-21d3bebb417e.png)
