### ISSUE TITLE
[Dashboard] Make the newsletter newsfeed also pull in images

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1354]
### What would you like to be added?

Would be cool if somebody made it so the images from newsletters also appear on this content feed (currently its just titles, as shown below)

![image](https://user-images.githubusercontent.com/55857222/193421234-ca5db1a2-9a60-4d11-b2ac-32acde97f50e.png)

Bonus points for also styling the scrollbar like it is on the landing page, check code or ask Luxumbra how its done if you're not sure.

### Why is this needed?

Because these images exist & adding some graphics to the dashboard would make it all look nicer

**Comment by luxumbra** [comment]
> Bonus points for also styling the scrollbar like it is on the landing page, check code or ask Luxumbra how its done if you're not sure.

That is already happening. :) 

![image](https://user-images.githubusercontent.com/780350/194590929-0a3633a7-b584-41d6-897b-bcdc85bafe85.png)

**Comment by luxumbra** [comment]
I've pushed a branch for this and made a PR #1372 (currently draft)
