### ISSUE TITLE
[MetaOS] Account dropdown styling

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1356]
Would be nice if the account dropdown menu was styled in the same way other menus.
Currently: 
![image](https://user-images.githubusercontent.com/55857222/193421184-155fa825-8ce4-41b5-b4df-3b3773a85a6a.png)
Other menus:
![image](https://user-images.githubusercontent.com/55857222/193421196-83c00fb5-1026-41ec-9495-0a9407038db2.png)

**Comment by luxumbra** [comment]
I can't connect on my local build rn but have applied the styles for this. Just need to get my build running to test it. @peth-yursick
