### ISSUE TITLE
Calculate $ amounts & add to the patrons leaderboard

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1361]
### What would you like to be added?

Besides the total number of pSeeds, patron cards should also be displaying the $ value of those pSeeds.

The dollar value of a pSeed is derived by summing up total value of all tokens [inside the pool](https://app.balancer.fi/#/pool/0x0b09dea16768f0799065c475be02919503cb2a3500020000000000000000001a) & dividing it by the total number of [pSeeds](https://polygonscan.com/token/0x8a8fcd351ed553fc75aecbc566a32f94471f302e).

### Why is this needed?

To make it understandable how much $ money is required for each ranked league & allow the patrons conversion page (#1341) to pull in that data for league/perk unlock requirements.

**Comment by peth-yursick** [comment]
@alalonde interested in taking this one (simplified version of #1201) while @kon-rad is building the patrons conversion page?

**Comment by alalonde** [comment]
Looks like we can look up the relevant data from the [balancer polygon TheGraph](https://thegraph.com/hosted-service/subgraph/balancer-labs/balancer-polygon-v2).

**Comment by dan13ram** [comment]
Reopening since this issue also requires the pSEED value in USD to be displayed on the frontend.
