### ISSUE TITLE
Changing default layouts (MyMeta & the dashboard)

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1365]
This is an issue about changing the default block layout on MyMeta profiles & the dashboard.

Currently on MyMeta:
![image](https://user-images.githubusercontent.com/55857222/194313996-3d0f38d8-fe8c-475d-ac46-933a280e2b37.png)
I think this should be the default:
![image](https://user-images.githubusercontent.com/55857222/194314626-dc92c1b1-0d9b-44a9-b5e6-287d900e760c.png)

The reason is that it looks more balanced by default + I think DAO memberships are more relevant than they appear like this on the bottom right block.

On the dashboard I'm not sure what the current default layout is because I can't check other people's, but I think it should be centered on the news/content & imo this looks most balanced as its symmetrical with the biggest block in the middle.
![image](https://user-images.githubusercontent.com/55857222/194315040-46c89029-75cb-4b08-ac06-0a08ee0a11da.png)

**Comment by dan13ram** [comment]
@peth-yursick the dashboard default layout has already been changed to what you've suggested above. Can make the change for profile layout too in my next PR
