### ISSUE TITLE
The 1.0 Breaking Issues

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1376]
As everyone was in charge of their own bits, we forgot about the most important bits, the connecting bits 🥲

To make the onboarding flow actually flow, people need to go:
- Landing page > onboarding game > mymeta profile creation > engaged octo path > path selection > etc

But!
- We forgot to update the damn links, lol
- Onboarding game is sending people to discord instead of "profile creation start screen"
- Profile creation end screen is sending people to discord instead of "engaged octo path"

👆 These 2 fixes are super important & super critical.

I will add another two, **optional** ones. Also pretty game-breaking but harder to fix:
- Quest cards are still displaying full quest description, no matter how long (not critical)
- Actual quests, when open, are **no longer displaying quest descriptions** (**critical**)
![image](https://user-images.githubusercontent.com/55857222/194723103-d5dbfd90-3ba9-4f87-9b86-06023584fa6d.png)
![image](https://user-images.githubusercontent.com/55857222/194723210-0944cd16-0326-48eb-93ec-6c8cfec39365.png)

**Comment by luxumbra** [comment]
> * Onboarding game is sending people to discord instead of "profile creation start screen"
> * Profile creation end screen is sending people to discord instead of "engaged octo path"

I am currently working on a fix for these. I've added the updated links and copy to the relevant places but am not able to test becaue my build is not working.

**Comment by luxumbra** [comment]
> * Quest cards are still displaying full quest description, no matter how long (not critical)
> * Actual quests, when open, are **no longer displaying quest descriptions** (**critical**)

These should be fixed now. Was merged into develop this morning https://github.com/MetaFam/TheGame/pull/1391
