### ISSUE TITLE
[Guilds] Making links more prominent

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1408]
As I was going through all twitter profiles of guilds so I can manually create guild pages & update existing ones before the launch, I've noticed a lot of them are using Linktree - some even as their default link..

Thinking:
If we make the link buttons bigger/more prominent, we could try to get these guilds to replace their Linktrees with their guild profiles in their bios. As a bonus, it would make profiles less bare as a lot of them dont have much yet.

Initial design:
![image](https://user-images.githubusercontent.com/55857222/195534576-836ddae2-08c8-431c-9463-11ede24a9db5.png)

Thoughts? @davort @alalonde

**Comment by davort** [comment]
1. I'd suggest combining the two. These icons represent brands and as such are instantly recognizable. The brain "gets" them faster than words. 
2. The styling is too strong. The CTA—primary button—should be reserved for that one main action we'd prefer the user to do here (JOIN). A secondary or tertiary button style could work well in this context. Even though I'd suggest not styling these as buttons at all. Buttons are typically reserved for actions, and not for hyperlinks that just take you somewhere. 
3. How much do we want to promote hyperlinks that will "take the user away" from this page? Will they ever remember to come back?

How about these?
![image](https://user-images.githubusercontent.com/1573304/196773270-3c443d65-ab09-44b0-a66c-29bb76b642d2.png)
![image](https://user-images.githubusercontent.com/1573304/196773312-a1f55efc-e9b8-4843-af32-f17315a6766a.png)

**Comment by alalonde** [comment]
I like them both, with a slight preference to the former as being more "linky"

**Comment by davort** [comment]
Same for me. Here's a variant with links and filled icons (instead of outlined)
![image](https://user-images.githubusercontent.com/1573304/196871780-f858e749-6ecb-453a-954e-83ac3848a002.png)

What other social links or networks might we need icons for, so that I can prepare them?

**Comment by peth-yursick** [comment]
> I'd suggest combining the two. These icons represent brands and as such are instantly recognizable. The brain "gets" them faster than words.

Great point, we should def keep the icons..


> 2\. The CTA—primary button—should be reserved for that one main action we'd prefer the user to do here (JOIN).

Actually I was even going to suggest we remove the "join" button, or at least disable for guilds that don't have any information on the onboarding or a questchain. Sometimes its not at all clear where the join button should lead, some projects send people to their website, some to discord etc..

> How much do we want to promote hyperlinks that will "take the user away" from this page? Will they ever remember to come back?

Doesnt matter imo, the goal is not to keep the user on the website but to help them find what they are looking for. If that something is another guild's website, so be it.. 🤷‍♂️
If we get guilds to replace their Linktrees with guild pages, then users proceeding to their website will be their concern as well, the guild pages should probably be more useful to guilds than us tho not sure thats possible.

> How about these?

Tbh I think neither yours nor my options get us anywhere near being able to pitch them on replacing Linktree. Links look more linky but kind of ugly having full links eg. "github.com/HausDAO/daohaus-app/daohaus.club" instead of just eg. "our Github". We could make it more obvious they're links by adding the outbound icon?

For reference:

The buttons are a shitload bigger, there's a little animation & the outbound icon appearing on hover
https://linktr.ee/atlantisworld
https://linktr.ee/Project_Ark
I mean, at the end of the day, Linktree only has one purpose, it does it great & we're not really competing with it as guild pages are meant to be much more than just a bunch of links, but still think these things should at least be considered..

**Comment by davort** [comment]
This is great added context—e.g. I had no idea that Linktree was an actual website/service :). Makes sense to try offering the same functionality in guild profiles, for the reasons you described.

Re: outbound icon - if all links will have them, then better go without IMHO. Perhaps just on hover?
![image](https://user-images.githubusercontent.com/1573304/196898418-448e876b-6c94-4036-9add-28103cdf39b3.png)

So, the default state might look like this?
![image](https://user-images.githubusercontent.com/1573304/196899093-6081c75c-c42a-464e-afe6-6c8d6af759e4.png)

**Comment by peth-yursick** [comment]
> Re: outbound icon - if all links will have them, then better go without IMHO. Perhaps just on hover?

Yeah, on hover sounds like a good idea. Doesn't look bad with them displayed the whole time as it looks more symmetrical but yeah.. 🤷‍♂️

> So, the default state might look like this?

Much better! Might just be worth making them stand out a bit more? Not a punch in the face like in my mockup but maybe a thin border, or have them turn full color like the ones on MyMeta or something
![image](https://user-images.githubusercontent.com/55857222/196901642-e49febf8-0a89-4a9c-bcd2-3ccf7fb8304a.png)
Idk, just spitballin' here..

**Comment by peth-yursick** [comment]
> I had no idea that Linktree was an actual website/service

Yep!
Also wanted to share this https://techcrunch.com/2022/03/16/linktree-link-in-bio-series-c-valuation/
Pretty interesting, eh? They basically made hundreds of millions based off the fact Twitter & Instagram only allow you to embed 1 link into your profile 😂

**Comment by luxumbra** [comment]
> Re: outbound icon - if all links will have them, then better go without IMHO. Perhaps just on hover?

imho the links look better with the outbound icon on hover.

**Comment by davort** [comment]
> > Re: outbound icon - if all links will have them, then better go without IMHO. Perhaps just on hover?
> 
> imho the links look better with the outbound icon on hover.

That's a great idea @luxumbra 👍
