### ISSUE TITLE
[MetaOS] Members-only features

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1409]
### What would you like to be added?

Thought it would make sense to start discussing the gating & members-only features now that we are starting to have some that could be defined as such.

Here's two we could start with:
- Limiting the player list to top 56, indicate total number of players (#871) & total number of profiles. Gate the use of search & filtering. Afaik no freelancing or social media platform allows you to use search without registering. As we onboarding more players & guilds who will onboard their players, search & filtering becomes more useful.
- We already have custom backgrounds enabled with #443, I think this is a perfect example of a feature that could be members-only as its not crucial for the use of profiles.

Other ideas:
- Custom roles
- Custom skills
- More than 2 custom blocks on the profile
- Champions Path questchain
- High value quests
- Bridgebuilding raid board

### Why is this needed?

This would help convert people into players or patrons, would also help us get more patrons in general as it would be easier to answer the question of making money as a project.

**Comment by Seroxdesign** [comment]
This will be included with the SEED issue and turned into a project in Github
