### ISSUE TITLE
[MetaOS] Adding join links to players, patrons & guilds pages

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1411]
Right now, the only way to get to the "join" pages is if you go down the landing page & go through the onboarding game.
I think it would make sense to have additional places pointing there & I think it makes most sense to have the players, patrons & guilds leaderboard loop back there.
Here's what I mean.
Currently:
![image](https://user-images.githubusercontent.com/55857222/195817071-344f0ca7-13c2-4646-aae8-4dd9ac44d9f4.png)
After this issue:
(check the new design by Dave below)

The same thing would need to be done on [players](https://my.metagame.wtf/players), [patrons](https://metagame.wtf/patrons) & [guilds](https://metagame.wtf/guilds) pages

[Link to the figma file](https://www.figma.com/file/hAmFBkfNhI7D4HMZ0jOVRV/Upgrade-callout?node-id=0%3A1)

Patrons page should be linking here https://metagame.wtf/community/join/patrons
Guilds page should be linking here https://metagame.wtf/join/guild
Players page should be linking here https://metagame.wtf/play/paths/engaged-octos-path (until the player signup page is made)

**Comment by peth-yursick** [comment]
Got this pretty high on the priorities list as rn theres no way to navigate to these joining pages anywhere once you're inside MetaGame..
Is this good enough to get implemented or did you want to make it look nicer @davort?

**Comment by davort** [comment]
@peth-yursick Where would the button "SURE!" take you for each of these 3 examples?

**Comment by peth-yursick** [comment]
> @peth-yursick Where would the button "SURE!" take you for each of these 3 examples?

For patrons, it would take them to https://metagame.wtf/community/join/patrons
For guilds, to https://metagame.wtf/join/guild
And for players the page doesn't exist yet, so it would only take them directly to https://metagame.wtf/play/paths/engaged-octos-path

**Comment by davort** [comment]
Starting with the presumption that people read/scan the page from top to bottom, positioning this CTA text at the very top should ensure that users notice it, without being overbearing. A text link instead of a button makes more sense here, and thanks to the styling, jumps out nicely IMHO. 

This would require us to move the search bar into the "sort& filter" container, in order to keep it truly clean. Hopefully that wouldn't be too much extra work?
![image](https://user-images.githubusercontent.com/1573304/196916020-05d6d2b2-4950-4975-9d68-8fdad46a62da.png)

**Comment by peth-yursick** [comment]
Simple beats it, thank you!
It looked good with a box on the patrons page but you're right - it would just be too much on players page with filters & everything + patron & guild pages will also have filtering... 🤷‍♂️
Maybe the only thing would be to use these gradients like on the landing page instead of just pink?
![image](https://user-images.githubusercontent.com/55857222/196926357-17ec2400-5d12-4f50-a21d-fd027b16712f.png)

**Comment by davort** [comment]
But... the colored text on the landing page, those aren't links or anything, but instead just emphasized parts, no? Now it feels like we're entering the area of over-optimization. Let's just keep it simple and clear - links can be uniquely distinguishable by this "light magenta" color _and the underline_ → recommended for good accessibility.

**Comment by davort** [comment]
The final designs are here: https://www.figma.com/file/hAmFBkfNhI7D4HMZ0jOVRV/Upgrade-callout?node-id=0%3A1
Guess we need to find a builder now? 😊

**Comment by dnh33** [comment]
Builder here, taking a look

**Comment by peth-yursick** [comment]
> Builder here, taking a look

Hey, any luck?

**Comment by luxumbra** [comment]
@dnh33 if you need a hand getting up and running, let us know. Hop in the [Discord](https://discord.gg/fC9tw6cz) or shout here and we'll get you sorted.

**Comment by HHH-GH** [comment]
I've done the easy parts of this—the patrons page, and the guilds page. 

The hard part is going to be the players page. I'd like some design assistance to see how it should look on small screens.

There are two main questions, plus some screenshots 

On big screens, the search box is to be moved into the filters box. ([See the design on Figma here](https://www.figma.com/file/hAmFBkfNhI7D4HMZ0jOVRV/Upgrade-prompt?node-id=0%3A1&t=fkKY6nUvOC9FkbFz-0))

As the screen narrows, the filter boxes wrap on to two lines. 

**Question 1**. With the search box moved into the filters box, I'd assume that as the screen narrows, the filter boxes would be grouped in a column on the right side, with the search by itself on the left side?

Eventually, the filter boxes are hidden altogether. They can be revealed again by clicking a Filter and Sort link.

**Question 2**. What would the design look like at this point? (Same as current, with the search box showing? More like the new design, with the search box somewhere with the filter links?)

Screenshots of the current design:

**1—Filter boxes wrapping on to several lines**

![image](https://user-images.githubusercontent.com/92962228/205493210-872ed28f-c15f-4186-83f2-1b72002aae2d.png)

**2a—Filter boxes hidden**

![image](https://user-images.githubusercontent.com/92962228/205493257-0f464108-dd17-49b8-8de8-9722f8cc4e34.png)

**2b—Filter boxes revealed again**

![image](https://user-images.githubusercontent.com/92962228/205493292-2af0db1d-2f1d-426f-a2e8-7953f92334ab.png)


An easy fix would be to move the CTA under the filters box.

---

p.s. is it just me, or are the filter dropdowns cut off when expanded?

![image](https://user-images.githubusercontent.com/92962228/205493580-28c2e432-fb0f-44d6-a958-c983780856e6.png)
