### ISSUE TITLE
Finishing the Patrons signup page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1412]
As these changes were only requested after @kon-rad was already mid-way through, there wasn't enough time to implement them before the launch.

The remaining 2 things:
- Automating ranked league $ requirements
   - With the help of #1361
- Updating the tiles to the new design
   - Old & new design side by side:
   - ![image](https://user-images.githubusercontent.com/55857222/195819380-81165b6e-67d3-4fe8-89cf-5ec69f25f376.png)
   - [Link to the figma file](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=5836%3A3265)

**Comment by kon-rad** [comment]
I will take this one on, will be starting Monday, if that's alright.
