### ISSUE TITLE
Updating the Seeds page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1413]
It was built a while ago, there's a bunch of it out of date by now..

Things to change:
- [x] Add the new illustration & maybe put it below the intro paragraph instead of side-by-side?
- [x] These two blocks should be completely removed. First one because the Seed Fund time has passed & the second one because there is no easy way for keeping the FAQ up to date, add more questions etc; + makes it symmetrical after removing Seed Fund.
   - ![image](https://user-images.githubusercontent.com/55857222/195832820-eea06484-e8b2-4868-9f1a-3c7382364260.png)
- [x] "Become a Patron" block text should be updated.
   - Instead of everything written on there right now, it should say this:
      - Though some use cases exist, they're not meaningfully contributing to the treasury yet & the rest are just ideas. Main reasons you'd want to become a patron right now:
      - Because you love the idea of MetaGame & want to see it succeed.
      - You want to become a part of MetaGame but don't have time to actively contribute.
      - Interested? Go [through here](https://metagame.wtf/join/patron).
- [x] "Get Ranked" block text should also be updated
   - Instead of current text, it should say this:
      - As you might know already both players & patrons have leaderboards & ranked leagues as well as perks (which will all be finalized at the end of _Phase I_, ~June 2023:
      - 🥉 Bronze Founder or Funder
      - 🥈 Silver Founder or Funder
      - 🥇 Golden Founder or Funder
      - 🔘 Platinum Founder or Funder
      - 💎 Diamond Founder or Funder
      - You may check the full list of [patron perks](https://metagame.wtf/join/patron) here & know the one for players will be similar. All feedback welcome.
- [x] Blocks themselves as well as the pop-ups should be transparent blur like the rest of the blocks & popups on the platform
- [x] Lastly, idk why it says SEED everywhere all caps instead of Seed. Would be good to replace everywhere, including page tab

**Comment by HHH-GH** [comment]
Hey peth,

Is the new illustration for Seeds the same one as on the Patrons Join page?

https://metagame.wtf/join/patron

**Comment by HHH-GH** [comment]
How about this as an idea for the top part of the page?

Main title: Seeds
Subtitle: What are Seeds?
Box: Big version of Seed icon 🌱 at top, then the existing text below that. 
Seeds illustration
...

Basically it will look just like the top of the Guild Join/Patron Join page, with a Seed icon instead of a Patron/Guild cloaked person.

**Comment by peth-yursick** [comment]
> Is the new illustration for Seeds the same one as on the Patrons Join page?

Hey, sorry again I forgot to include it..
Here you go, the SVG:
![svg join as a player](https://user-images.githubusercontent.com/55857222/197333727-2448308f-34d3-4231-8bfd-0aaabbb35fe7.svg)
And other 2 if you want to replace:
![svg join as a patron](https://user-images.githubusercontent.com/55857222/197333740-8682238e-e0fc-4524-b8cc-2602876b5d91.svg)
![svg join as a guild](https://user-images.githubusercontent.com/55857222/197333742-a9d7865d-fc6a-4c40-9b85-60582dec5001.svg)
