### ISSUE TITLE
Add error tracking and ability to capture user feedback

### ISSUE THREAD

**Issue by luxumbra** [MetaFam/TheGame#1414]
### What would you like to be added?

I would like error & exception tracking added to the MetaOS application. Coupled with this, I would also like to see a feedback widget added to the frontend to capture feedback from any users who are having issues without them needing to find Discord or another comms channel.

I would also like to see MS Clarity working again on the app to gather usability data like heatmaps, rageclicks, etc.

I have used [Honeybadger](https://honeybadger.io) and [Sentry](https://sentry.io/) in the past on smaller projects and found them incredibly helpful in squishing bugs that users encounter in the wild.

### Why is this needed?

I feel we should have had this earlier than v1.0 but imho this is essential now we are in v1.0 and if we are to take our product seriously. 

- Tracking errors and getting detailed reports in a dashboard/email/discord channel will give us way more insight into issues and the problems our users are experiencing.
- A feedback widget will give our users an easy way to report their issues and us a better overview of issues with the the app.
- Re-activating Clarity will give us additional data we can use to improve the product.

**Comment by alalonde** [comment]
I 100% agree with the need for professional tooling to help with quality control. All of these things (with the exception of Clarity) I would say are mandatory.  Before implementing a tool, though, can we do some basic research around privacy and data harvesting?  I have used hotjar in the past but was never really comfortable with it TBH. It's basically pseudonymous spyware.  If we claim to be building a new web, then we need to abide by a higher standard.  (I'm skeptical that we would actually do anything with the data anyway. )

Let's definitely proceed with the error tracking and feedback widgets at least, provided they are not too much of a tradeoff with user privacy.

**Comment by luxumbra** [comment]
> All of these things (with the exception of Clarity) I would say are mandatory. Before implementing a tool, though, can we do some basic research around privacy and data harvesting? I have used hotjar in the past but was never really comfortable with it TBH. It's basically pseudonymous spyware. If we claim to be building a new web, then IMO we need to abide by a higher standard. (I'm skeptical that we would actually do anything with the data anyway. )

Totally agree with the privacy aspect and holding higher standards than our web2 counterparts and will do some digging on the data harvesting aspect. 

I've pushed a branch which has Honeybadger and UserBack added and I've removed HotJar & Clarity. Userback is  is on a free trial but isn't too pricey and lets you customise the feedback forms and info gathered as you like.
