### ISSUE TITLE
[MyMeta] Patrons leaderboard only loading top 48 patrons

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1417]
When you scroll down to the bottom of the patrons leaderboard, its not loading any more than the first 48.
There's a person holding 8pSeeds who reported that issue.

Also, same issue as in quests - patron cards go all the way to the edge of the screen instead of there being a margin..

**Comment by HHH-GH** [comment]
**Two parts**

**1. only 48 patrons shown**
I could do a quick fix for this. In `graphql/getPatrons.ts` there's a default limit of 50 patrons returned. 
```
export const getPatrons = async (limit = 50): Promise<Array<Patron>> => {
```
On the patrons page the limit could be changed to show more than 50 patrons, like ... 100? 200?
e.g. `const patrons = await getPatrons( 100 );`

That's a quick fix, the proper fix would be to do a infinite scroll/load like on the players page.

(The proper fix is maybe beyond my skills)

**2. Cards go all the way to the bottom of the screen**
Add the back to top button and Octo image like on the Seeds page? https://metagame.wtf/seeds

?

**Comment by peth-yursick** [comment]
> On the patrons page the limit could be changed to show more than 50 patrons, like ... 100? 200?

Should be 150 since there shouldn't be more than 150 patrons anyway 🤷‍♂️

> **2. Cards go all the way to the bottom of the screen**
> Add the back to top button and Octo image like on the Seeds page? https://metagame.wtf/seeds

Sounds good!

**Comment by HHH-GH** [comment]
Preview deployment here: https://frontend-pr-1439-mjhnbmqqna-uk.a.run.app/community/patrons
