### ISSUE TITLE
Temporarily Circumventing MyMeta Profiles

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1420]
Given MyMeta broke & people won't be able to create new profiles until #1405 is merged - while we just had a launch & new people wanting to get in - it would probably be wise to temporarily set the "for players" link in the onboarding game direct people to the [Engaged Octo's Path](https://metagame.wtf/play/paths/engaged-octos-path) instead of MyMeta.

Same goes for the "join as a player first" in the [guilds page](https://my.metagame.wtf/join/guild).

Not sure if any other place directs people to it but those should be the 2 main funnels to the profile creation..

**Comment by krzysu** [comment]
Something like here? https://github.com/MetaFam/TheGame/pull/1423
