### ISSUE TITLE
Quest Chains integration glitching on mobile

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1421]
As reported by a few users, looks like the scrolling down the paths glitches on mobile, making it impossible to use.
Trying to scroll down skips the quests & its not possible to swipe or scroll them back..

**Comment by luxumbra** [comment]
@vidvidvid or @dan13ram I'm looking into how the UX can be improved for the quest chains on mobile. While it is kinda usable on mobile, after trying to scroll the page up or down I want to abandon the process and throw my phone out the window. 😅 There's a lot going on with the carousel and I am not sure of how to tackle it. I disabled the onClick for mobile and added  prev/next buttons but I'm still having issues with moving to the next item when I try to scroll.

**Comment by vidvidvid** [comment]
Hey o/ yeah, i tried using it on mobile as well, was not nice. Probably we need to disable any other interaction when trying to scroll vertically. Maybe we could disable horizontal scrolling, I'm not sure how to best approach this.
