### ISSUE TITLE
[Quest Chains] Pressing back arrow in the text box moves to the previous quests & loses the text

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1424]
### What happened?

A user reported the interface switching the whole quest upon pressing back arrow instead of just going back a single letter in the input box - the text also disappears as the quest is changed.

### What did you expect to happen?

Move back a letter.

### How can we reproduce the problem (as minimally as possible)?

Probably by going to any of the paths on the website https://test.metagame.wtf/roles

**Comment by luxumbra** [comment]
I’ve upped the priority on this in Dework to medium but I’d argue it should be high due to the frustration this leads to when completing QC. Keyboard nav is great but we lose all the accessibility benefits if it hijacks the arrow keys when focus is on an input.

**Comment by vidvidvid** [comment]
looks like pressing either of the keys up, down, left or right while not having the text input focused will shift the current quest. i'll try disabling the keys when the quest modal is opened.
