### ISSUE TITLE
Procure SVGs for image assets where possible

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1432]
### What would you like to be added?

I'd like it if more of our assets were SVGs. The resizability is better and, more importantly, the ability to edit and update assets is orders of magnitude better.

This was sparked in part by the [SEED flow graph](https://github.com/MetaFam/TheGame/issues/1413#issuecomment-1287727707). The [export from Figma](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=6640%3A5361) converts the text to paths & includes all the art as rasterized PNGs. This [bloats the size](https://github.com/MetaFam/TheGame/pull/1426#issuecomment-1290530597) to over a MiB.

Producing a true and efficient SVG shouldn't be terribly difficult, but will take some knowledge of SVG to produce.

### Why is this needed?

Primarily the editability, but also the size of most images is significantly smaller as a SVG.

I'm also interested in adding animations and interactivity to some of the images, and that's only really possible with SVG.

**Comment by Seroxdesign** [comment]
This should be in a contribution guideline instead of an Issue, also outdated closing.
