### ISSUE TITLE
Switch description culling from character count to CSS `line-clamp`

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1440]
### What would you like to be added?

A players description is displayed as Markdown on their details page, and as a block of text on the leaderboard truncated to a certain number of characters.

Displaying as a block of text makes profile descriptions that use newlines uglier and harder to read. Additionally limiting by the number of characters makes for uneven final breaks partway through the line.

A better solution would be to render it as Markdown and use the CSS `line-clamp` property to limit the number of displayed lines. This can also be accomplished with [Chakra's `noOfLines` attribute](https://chakra-ui.com/docs/components/text/usage#truncate-text).

One additional feature would be to give all the text elements in the Markdown on the leaderboard the same font size to keep things even.

### Why is this needed?

As aforementioned, this would preserve the whitespace in profile descriptions making them more readable.

**Comment by HHH-GH** [comment]
I'll take this one 🤟
