### ISSUE TITLE
Further fixes to the patrons signup page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1442]
There's still a bunch of fixes to be made to make the [patrons signup page](https://metagame.wtf/join/patron) look great.
Some of these may seem like details but this is one of the most important, if not the most important page currently so we really need to get it right to proceed with converting new patrons & move on with the fundraise.

Here's everything in a list:
- [x] Box content font looks bigger than box heading, shouldn't be
- [ ] The headings should probably be bigger rather than bold & "total of" shouldn't be bold either
- [x] The box headings aren't capital letters as they are across the platform
- [x] Box content looks like its either using a different font or a very thin version?
- [x] Margins are much thinner than the rest of the platform or the design
   - ![image](https://user-images.githubusercontent.com/55857222/200113077-68c91f89-0c96-4b8f-a55e-d81c7c8ab480.png)
- [x] This last box was intentionally made wider so it can accommodate all text without breaking into a new line but looks like its breaking into a new line anyway..
   - ![image](https://user-images.githubusercontent.com/55857222/200113102-5d1b00bf-af2b-489c-95fc-26b6d01db6c4.png)
- [x] There's all this extra empty space in the bottom call-to-action cards, above button should be the same as below
   - ![image](https://user-images.githubusercontent.com/55857222/200113162-55f66b7b-7732-460d-9460-e2e2a053eb5c.png)

**Comment by HHH-GH** [comment]
@peth-yursick 

Most of this is clear, but is there a design I can use as a reference for the gaps/heading sizes/etc?

**Comment by HHH-GH** [comment]
Is this one in Figma up to date?

https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=5853%3A4465&t=H3ieVH4WceOKjeS8-0

**Comment by HHH-GH** [comment]
Did all the tasks here, except

>  The headings should probably be bigger rather than bold

If the font size is larger, many of the headings don't fit on one line on small screen sizes. Left them as bold, and uppercased.
