### ISSUE TITLE
[MetaOS] Updating the cards design

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1443]
This issue is about updating the cards design to make MetaGame as a whole look nicer & feel a bit more like a game.

Some of you who have been here for a long time may remember the original card mockup from 2019...
![image](https://user-images.githubusercontent.com/55857222/200819270-cde125f9-2423-4152-b9a5-f7604486371c.png)

Unfortunately, the production turned out nothing like it for a bunch of reason & then stayed like that for 2+ years.
Figured its time to revisit the card design to make it more game-like & make it applicable to other things now that its actually a viable option (because art for all the cards can easily be generated)

Here's what the cards look like when applied to all the categories:
![image](https://user-images.githubusercontent.com/55857222/200818157-5cd84835-2a9f-4f40-97cd-28167b4905b0.png)

[Here's a link to the figma file](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=6701%3A6415)

All categories:
- [x] Players leaderboard
- [x] Patrons leaderboard
- [ ] Patrons signup page
- [x] Guilds
- [ ] Guilds signup page
- [x] Paths
- [ ] Playbooks
- [x] #1462 
- [x] Quests
- [x] Raids
- [ ] The Bazaar

Before it can be applied to everything, there are other requirements:
- [x] Adding images to quests
- [ ] Playbooks page
- [ ] Learning Curve of the Role Paths
- [x] Time needed for Role Paths
- [ ] Difficulty of joining a guild
- [ ] The Bazaar doesnt even exist yet so dont mind it

**Comment by luxumbra** [comment]
Looking at the cards in situ in the deploy preview for #1438, I feel the backgrounds of the cards need to be darker or something to improve readability - the player cards are pretty hard to read when there's a lighter bg / profile image.

**Comment by thebeyondr** [comment]
> Looking at the cards in situ in the deploy preview for #1438, I feel the backgrounds of the cards need to be darker or something to improve readability - the player cards are pretty hard to read when there's a lighter bg / profile image. 

Strong agree here. Flipping the card color to a dark purple + opacity should do the trick. The design should be fun but still accessible I assume. @peth-yursick
