### ISSUE TITLE
The onboarding guidance screen

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1444]
### What would you like to be added?

I would love there to be an onboarding guidance screen to give people a view of how onboarding into MetaGame works before they start going through the whole process of completing the Engaged Octo path etc.

Wrote this for the newsletter then designed it into a page:
![image](https://user-images.githubusercontent.com/55857222/200820526-120a975b-c6d2-4ba7-b2d5-130b3029c731.png)
[Figma file](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=4143%3A1628)

- [x] This screen should appear between the onboarding game & the mymeta profile creation. If possible, this should be using the same cards template that @vidvidvid implemented for #1443
After that (these will be separate issues once this one is completed):
- [ ] The game should detect either when a player has gained the Engaged Octo role on MetaGame's discord or when their Engaged Octo path has been approved as completed, then present them with the same screen but showing their progress
- [ ] Then, once again when they become a player or patron, it should show something similar, congratulate them & show them the "welcome to metafam" page
- [x] After that, I will design a follow up screen that displays next stages..

### Why is this needed?

Right now people are put directly through the mymeta profile creation & then onto the engaged octo path without gaining a context on how joining MetaGame actually works.
Giving them an overview like this will help them understand & make them more motivated to continue their joining journey.

**Comment by peth-yursick** [comment]
Wouldn't exactly call this a finished design tho - it was made by a non-designer.
@davort are you interested in doing some final touches, giving feedback or your stamp of approval as "good enough for now"? 😂

**Comment by davort** [comment]
Love it! This is definitely ready to be shipped as is 🙌

**Comment by nitegeist** [comment]
Hey, I'm going to be tackling this issue. Keep me posted on any updates regarding it.
