### ISSUE TITLE
Updating the raids page & integrating actual dework boards

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1451]
Right now the raids page only has text & none of the text leads to actual raid boards which are in Dework.

This issue is about simplifying the raids page, make it display a bit of the bigger picture & actually link to Dework boards for their respective raids.

Current page:
![image](https://user-images.githubusercontent.com/55857222/202170822-e9a42143-38ee-4967-9dee-bc0190bf84c4.png)

New page:
![image](https://user-images.githubusercontent.com/55857222/202169370-7574a12f-c5a1-42bd-88bf-30b2718a797a.png)
[Actual figma file](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=6405%3A5159&t=asIhfroAZH6ZDMAG-1)

- Each of the cards should be opening the related Dework board inside the website in an iframe.
- The phases of metagame card should also be wholly clickable lin[king to the page about it](https://wiki.metagame.wtf/how-does-it-work/phases-of-metagame)
I will provide more info & necessary links when needed for whoever expresses interest in building this.

**Comment by peth-yursick** [comment]
Thoughts on the design @davort?
Anything that should be improved or, interested in doing some final touches before it can be put into production?

**Comment by peth-yursick** [comment]
Or if you think the whole progress bar card should be redesigned?
As usual, I thought it would be a 5 minute thing where I just turn raids into cards & have one card to display the goals but then it turned out to require much more time & design skills which I don't have 😂
Totally dont mind if you think its crap & should be scrapped.

**Comment by davort** [comment]
@peth-yursick I think it looks fantastic!
The progress bar card is solid, and IMHO perfectly clear. I can tell what are the phases, in which order they come, and where MetaGame currently is on this path (near the end of Phase 1). The phase cards also look very effective. Really nice work!

Just one thing - it isn't obvious that the cards are clickable. There is no clear "call to action". Nothing to hint that "there is something behind" the cards. Would you agree?

**Comment by peth-yursick** [comment]
> Just one thing - it isn't obvious that the cards are clickable. There is no clear "call to action". Nothing to hint that "there is something behind" the cards. Would you agree?

I think its fine, just the fact that there's literally nothing else on the page, the new animation effect that Vid added & the cursor changing from pointer to hand should make it obvious enough, hopefully

**Comment by davort** [comment]
If you say so :)
