### ISSUE TITLE
Broken link in onboarding game

### ISSUE THREAD

**Issue by ipatka** [MetaFam/TheGame#1459]
### What happened?

https://wiki.metagame.wtf/docs/wtf-is-metagame/metafam-way

![Screen Shot 2022-11-21 at 9 04 37 AM](https://user-images.githubusercontent.com/4401444/203074708-306bcc75-0775-4376-a7b4-dde7d618ac2d.png)

This link is broken. It should probably be https://wiki.metagame.wtf/

### What did you expect to happen?

Go to the link

### How can we reproduce the problem (as minimally as possible)?

Follow the onboarding quest to the screenshot above

### Is there anything else we need to know?

Happy to fix this myself, where is this code?

**Comment by luxumbra** [comment]
hey @ipatka thanks for reporting this. Can I ask what URL you were accessing the Onboarding Game on? The 'MetaManifesto' link was fixed and updated on the production site a little while back.

**Comment by ipatka** [comment]
i was using one from the newsletter. perhaps it is an outdated one https://frontend-pr-1332-mjhnbmqqna-uk.a.run.app/onboarding

**Comment by luxumbra** [comment]
> i was using one from the newsletter. perhaps it is an outdated one https://frontend-pr-1332-mjhnbmqqna-uk.a.run.app/onboarding

Ah yes, that is the original URL we posted and is now out of date.

**Comment by ipatka** [comment]
ok will close the issue then thanks!

**Comment by luxumbra** [comment]
> ok will close the issue then thanks!

No worries. If you're wanting to contribute, we have plenty of other issues and bug fixes that would love some attention. Have you taken a look at [our DeWork issues](https://app.dework.xyz/metagame-1/metafest-2022)?
