### ISSUE TITLE
The filters for quest selection are not visible

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1468]
### What happened?

The filter bar for selecting quests appears to have `overflow: hidden` set so the dropdowns don't display:

![Screenshot from 2022-11-28 16-26-03](https://user-images.githubusercontent.com/181523/204385125-c47a54a0-f3ac-4476-9460-f6d4ccd2bb2f.png)

When `overflow: hidden` is disabled, on the `div` near the options, it becomes apparent that `overflow: hidden` is also set on another `div` higher in the tree.

![Screenshot from 2022-11-28 21-36-21](https://user-images.githubusercontent.com/181523/204425464-34dbd09a-ed3d-4a40-8480-8bfc71ea8d29.png)

### What did you expect to happen?

You should be able to see the filter options.

### How can we reproduce the problem (as minimally as possible)?

Go to [test.metagame.wtf/quests](//test.metagame.wtf/quests) and try to filter the results.

**Comment by peth-yursick** [comment]
test.metagame won't load for me for some reason but seems to be working normally for me in prod
![image](https://user-images.githubusercontent.com/55857222/205033457-6bd00012-f0a4-4b36-a769-9bb0952c1ec5.png)

**Comment by luxumbra** [comment]
> ### What happened?
> The filter bar for selecting quests appears to have `overflow: hidden` set so the dropdowns don't display:
> 
> ![Screenshot from 2022-11-28 16-26-03](https://user-images.githubusercontent.com/181523/204385125-c47a54a0-f3ac-4476-9460-f6d4ccd2bb2f.png)
> 
> When `overflow: hidden` is disabled, on the `div` near the options, it becomes apparent that `overflow: hidden` is also set on another `div` higher in the tree.
> 
> ![Screenshot from 2022-11-28 21-36-21](https://user-images.githubusercontent.com/181523/204425464-34dbd09a-ed3d-4a40-8480-8bfc71ea8d29.png)
> 
> ### What did you expect to happen?
> You should be able to see the filter options.
> 
> ### How can we reproduce the problem (as minimally as possible)?
> Go to [test.metagame.wtf/quests](//test.metagame.wtf/quests) and try to filter the results.

Which browser/os is this? I am not experiencing it on Chrome/Linux
