### ISSUE TITLE
Update Hasura to the Newest Version

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1477]
### What would you like to be added?

Our version of Hasura, 1.3.3, is about two years out of date. At some point we need to migrate to v2 in no small part so that we can utilize [Hasura Cloud](//cloud.hasura.io) which has automated schema caching and ample provisioning that could well help with the occassionally abysmal loading times on the [players' leaderboard](//metagame.wtf/players).

### Why is this needed?

Hasura has been releasing significant functionality and performance enhancements for years and we ought to be taking advantage of them.

**Comment by Seroxdesign** [comment]
We've updated to Hasura V2
