### ISSUE TITLE
Getting rid of the hamburger loading thing

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1478]
For some reason, while the site is load, the page is displaying what appears to be a massive hamburger menu going beyond full screen 😂
![image](https://user-images.githubusercontent.com/55857222/206425031-7c83010d-1fb5-4857-af88-22308be3ae50.png)

It looks ugly, probably a bug & we should get rid of it?
Could be replaced with the little loading blocks like when clicking a raid on https://metagame.wtf/raids
But it could also simply be removed & replaced with a blank black or dark purple screen, imo would still be much preferable to this..

**Comment by luxumbra** [comment]
It is definitely a bug. A loader would definitely be preferable but this isn't being used as a loader, it's just missing some styles

There's a bunch of unstyled content on the page when loading. Not sure when it started happening but def feels like a regression.

![image](https://user-images.githubusercontent.com/780350/206437291-cda7a0bd-6b0d-43b0-8718-b8c355f5f7ee.png)

![image](https://user-images.githubusercontent.com/780350/206437750-ed3bd656-f758-4384-8296-cdc0c7ee650e.png)

**Comment by alalonde** [comment]
I spent some time looking into this. From what I can tell, Chakra is rendering the megamenu with the default responsive settings (`base` which is basically mobile), then on subsequent renders it switches to the correct setting (e.g. `lg` or `xl` for a desktop browser). Not sure why this is happening but I did fine [this](https://github.com/chakra-ui/chakra-ui/issues/6452) which seems related
