### ISSUE TITLE
Stand up a ComposeDB-compatible Ceramic node pointing to testnet

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1490]
Existing node is deployed through Google Cloud at `ceramic.metagame.wtf`

Ideally we can clone the existing node so as to not kill the existing functionality.

Set up a database to allow indexing as specified in the docs...

**Comment by dysbulic** [comment]
It'd be nice, but I've not heard of them setting up instances for organizations. I'm pretty sure it'll fall to us.

Something I'm curious about is if the daemon requires any local storage. If all the data is in IPFS or SQL then we ought to be able to use Cloud Run to host the server which could mean a significant cost savings.

**Comment by dysbulic** [comment]
@polimyl is on this. I'm pretty sure the new server will be https://ceramic.metagame.wtf:7007, right?
