### ISSUE TITLE
Upgrade MyMeta to use the ComposeDB graphQL queries and mutations

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1491]
- [ ] Frontend: Create a `useSaveProfileToComposeDB` hook, and have `EditProfileModal` use it
- [ ] Frontend: Add error handling to the save function and persist to our Hasura as a fallback (hopefully with minimal data transformation)
- [ ] Backend: Update the `updateSingle` cache to pull from ComposeDB instead

**Comment by dysbulic** [comment]
Will we be able to move the profile data out of Hasura and solely host it in ComposeDB?

That would probably help with the issue where people reload before the cache has time to repopulate.

It seems like all we would need to do is put the XP info into Ceramic.

I'd love to see it done in such a way that different organizations could store their own cred tokens, and get a leaderboard for that token.

**Comment by alalonde** [comment]
With all the issues we've seen with 3Box labs alpha software, I have very little confidence (in the short term anyway) of this new network being sufficiently robust to be our only source of truth for that data. 

The most robust solution IMO would be to write to both ComposeDB AND our own Hasura from the frontend, and read from only Hasura still acting as a cache.

**Comment by alalonde** [comment]
> Horare's Dictum: "Premature optimization is the root of all evil."

This is not about optimization, but resiliency. If ceramic goes down, profile updating and reading would still work fine.

You bring up good points though; I am going to proceed with just using ComposeDB as our data source (at least initially) with the hopes of ripping out all the caching code.
