### ISSUE TITLE
Build a tool for users to be able to migrate their existing profile data into ComposeDB

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1492]
Existing Ceramic data cannot be automatically ported over to ComposeDB. Thus, we'll need to build a backend flow for users to trigger exporting their own data from Ceramic and importing it into ComposeDB. Ideally this is just a click of a button and signing a few transactions.

This sort of thing is inherently error-prone, so we will need to est, troubleshoot and maintain the tool for ~6 months after launch.

**Comment by dysbulic** [comment]
Do you want to just use the Hasura cache, or do you want to maintain a legacy Ceramic tiles server?

**Comment by alalonde** [comment]
Great question. We should only support migrating for a certain amount of time, so we could in theory just keep the existing Tile server as the original "source of truth".   However it seems like our Hasura cache is probably good enough? @dysbulic  What do you think ?

**Comment by dysbulic** [comment]
Yeah. So I think there should be a button that populates your profile form with the deprecated values, and you just submit it like normal.

**Comment by dysbulic** [comment]
Especially since [self.id](https://self.id) has started breaking, so, other than our system, I don't know how one would make changes to their legacy Ceramic profile in any case.
