### ISSUE TITLE
Guidance screen bugs & linking to a wrong place

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1495]
There seem to be several problems with the new guidance screen..

![image](https://user-images.githubusercontent.com/55857222/211520914-36f95fbd-f147-40a7-b7d5-3eb784ca44a7.png)
1. clicking "understand" takes people to a wrong place - its linking straight to the [first step of the profile creation](https://metagame.wtf/profile/setup/name) instead of [the profile creation opening screen](https://metagame.wtf/start)
2. there's this weird section below the background, where the actual background is visible. Assuming the person overlaid another background image over the existing background image?
3. the blur on the card name rectangles doesn't seem to be working (in Chrome nor Firefox)
4. looks like the text inside the boxes is right aligned or leaving too big of a margin. I spent a while optimizing the text in figma to make sure single words don't break into new lines, which seems to be the case in prod after all..
![image](https://user-images.githubusercontent.com/55857222/211522359-3f6a5954-d52b-4784-8c54-885b7a3c3115.png)
Feature requests (feel free to ignore, will open as a new issue if needed):
6. would be great if the cards were animated in the same way as other cards (check https://metagame.wtf/players)
7. would be awesome is the finger pointing up was moving up & down

**Comment by luxumbra** [comment]
![image](https://user-images.githubusercontent.com/780350/212749458-402dbf6a-2c8b-40e2-a220-237a20914520.png)
Not consciously i didn't 😅

**Comment by peth-yursick** [comment]
Closed but doesn't seem to be fixed.. @alalonde @nitegeist 
![image](https://user-images.githubusercontent.com/55857222/213888445-acfd71c6-e646-42ab-8b21-dc5bd129d70b.png)

**Comment by nitegeist** [comment]
@peth-yursick it's finnicky man, I'm still working on it however. Will push when I've found a suitable fix

**Comment by alalonde** [comment]
> Closed but doesn't seem to be fixed

Is too: https://test.metagame.wtf/onboarding/guide

**Comment by peth-yursick** [comment]
My bad! I've realized today I was only looking at the live version 😅

There are two other smaller issues tho:
The whole thing looks to be bottom-aligned & there's a scrollbar, you can scroll like 1 milimeter up & down 😂
Not worth keeping it open just for that but would be good to fix before live if its not _too_ finnicky
![image](https://user-images.githubusercontent.com/55857222/213929580-2b6932ae-544d-42e5-bcb3-76d05f359c0a.png)

**Comment by nitegeist** [comment]
No problem, I'll try to get that fixed as well before it's merged 😄
