### ISSUE TITLE
Stand up a v2 (ComposeDB) Ceramic server

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1501]
### What would you like to be added?

I propose that we begin a capture the ComposeDB development work in the [`feature/composedb`](https://github.com/MetaFam/TheGame/tree/feature/composedb) branch.

When people are submitting bounties, they will merge to that branch.

We need a public test server for that branch.

### Why is this needed?

Actually, so long as there's an open pull request for that branch, a test server will be created using that software.

So, instead of the issue for the `feature/composebd` being about the models (#1493), it'd be for the entire endeavor, and would be closed when we release and migrate the production server.

**Comment by alalonde** [comment]
This sounds like a decent plan, however there is already so much divergence with open PRs that it may be too late to use the `feature/composedb` branch.

Since we already have #1490 (with a bounty) I am going to close this as a dupe
