### ISSUE TITLE
Upgrade Ceramic network for hard fork by 2023⁄02⁄15

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1506]
### What would you like to be added?

From Ceramic:

> **[A]ll Ceramic nodes operating on the Ceramic mainnet must be upgraded to running at least version 2.18.0 of the @ceramicnetwork/cli package by February 15, 2023.**

I don't know what the CLI package has to do with the server operation, but someone should verify whether we're good.

### Why is this needed?

They say so.

**Comment by alalonde** [comment]
This is already done, right?

**Comment by dysbulic** [comment]
According to @polimyl, yes.
