### ISSUE TITLE
Broken link in the mega menu

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1508]
Given MetaGame's discord server lost the boost level, we lost the /metagame invite link.
Given we lost the /metagame invite link, the link to our server on metagame.wtf is now broken..
Given this happened before, it would be better to just replace the link with a link that will never break: https://discord.gg/UnHwnzY

![image](https://user-images.githubusercontent.com/55857222/213935661-fc778f36-bde8-48e2-a6c3-68f6d2f9179b.png)

**Comment by luxumbra** [comment]
@peth-yursick KoH boosted us back to level 3 today after I asked nicely if someone would boost us.

**Comment by peth-yursick** [comment]
> @peth-yursick KoH boosted us back to level 3 today after I asked nicely if someone would boost us.

Ahh, nice!
Unfortunately this is like the fifth time we lost the boosts for a week or two at a time - and only the first someone reported one of the most important links being broken..
Given the link is not even displayed as "metagame" in this instance but hidden under a button, I think it still makes sense to replace it with a normal permanent link to make sure this doesnt keep on happening..

**Comment by dysbulic** [comment]
I added a redirect from [chat.metagame.wtf](https://chat.metagame.wtf) to a non-customized Discord invite URL.
