### ISSUE TITLE
Investigate using CredEquate to calculate the SourceCred distribution

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1515]
### What would you like to be added?

I am working on [Coorditang](//coorditang.vercel.app), a system to feed a multi-level Coordinape distribution into SourceCred for the calculation of XP.

My current work is stymied because PageRank, the heart of the CredRank algorithm that drives our current system, was originally used to determine the value of webpages, and one of the metrics it uses is the number of "pages linking to a page". The more links, the higher it's rated.

In Coorditang, the guilds vote on how funds should be distributed. Because the Content Guild is roughly twice the size of the Community Guild, it's votes end up being counted more.

CredEquate should allow using algebraic relationships that can better capture the multi-tiered distribution.

Here is the recording of @blueridger describing how to do a Credequate Distribution & how the data is organized. [Stacks DAO](//github.com/stx-advox/advocates-sc-stx) is the only organization running a CredEquate-based distribution.

https://user-images.githubusercontent.com/181523/215557448-afe94937-bb58-4062-9f72-751d2392429d.mp4

https://user-images.githubusercontent.com/181523/215557532-4b2f4935-39ba-4351-be71-4783ef3bf77f.mp4

https://user-images.githubusercontent.com/181523/215557573-c7882f7f-128e-4ddd-8f1d-7d5312ef9619.mp4

### Why is this needed?

The calculation is off using CredRank.

**Comment by peth-yursick** [comment]
closing for now, will reopen if we continue using sourcecred
