### ISSUE TITLE
Changing page titles (removing MetaGame prefix)

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1526]
It would be good to change the default page labeling way if possible.

The reason:
Looks like all pages are prefixed with "MetaGame" which is kind of lame, especially in the case of guild profiles:
![image](https://user-images.githubusercontent.com/55857222/219615024-a1c3438d-143f-43e8-a559-351efd2d8ac9.png)

If we want projects to use their guild pages as Linktree/something to send to people to get an overview & links to their project - the pages should probably simply be titled eg. "Giveth", rather than "MetaGame Guild Profile: Giveth".

But same goes for other things, eg. paths:
MetaGame Engaged Octo's Path > Engaged Octo's Path

Can this be done at the project level so it automatically affects all sub-pages or will each have to be changed manually?
@dysbulic @alalonde

**Comment by dysbulic** [comment]
@peth-yursick, there's a template for the pages. This will only require a couple changes.

**Comment by Seroxdesign** [comment]
this seems fixed

**Comment by peth-yursick** [comment]
Seems still present on every page except on guild pages..
