### ISSUE TITLE
Time zone setting is broken in the profile wizard

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1527]
### What happened?

When setting the time zone in the profile wizard, you get:

![Screenshot from 2023-02-17 20-16-35](https://user-images.githubusercontent.com/181523/219824049-85b3fb22-19a9-446a-9809-9c259502eec1.png)

### What did you expect to happen?

It to set.

### How can we reproduce the problem (as minimally as possible)?

Try to set the time zone from [metagame.wtf/profile/setup/timeZone](//metagame.wtf/profile/setup/timeZone).

### Is there anything else we need to know?

The time zone can be set from the profile details page, so it's specific to the wizard.

**Comment by Seroxdesign** [comment]
Resolved
