### ISSUE TITLE
Add "custom block" integration for mymeta profiles - UX / Design

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1540]
### What would you like to be added?

As specified [here](https://forum.ceramic.network/t/proposal-mymeta-idenity-aggregator-for-daoists/564):

Add MyMeta profile &/or MetaOS dashboard “custom block” integrations for two other projects utilizing Ceramic / ComposeDB to pull in users’ shared data

### Why is this needed?

More integrations can make mymeta profiles more valuable / interesting

**Comment by alalonde** [comment]
First integration here https://github.com/MetaFam/TheGame/pull/1541

**Comment by peth-yursick** [comment]
[#1512](https://github.com/MetaFam/TheGame/issues/1512) has a load of MyMeta custom block ideas

**Comment by alalonde** [comment]
Second integration (Dework) [here](https://github.com/MetaFam/TheGame/pull/1595)
