### ISSUE TITLE
Various bugs on beta.metagame.wtf

### ISSUE THREAD

**Issue by RikaGoldberg** [MetaFam/TheGame#1543]
### What happened?

Per Alec's request, I am lumping all of the issues into one. The issues are as follows:

1. Ceramic Error - cannot link Ceramic node (beta.metagame.wtf/me)
2. Error connecting to Dework using Discord or Gitub to join a raid (beta.metagame.wtf/raids)
3. Page transitions load laggy
4. Quest Explorer doesn't pull in quests

**Details**:
1. I disconnected Metamask, then reconnected. I started the port data process but quickly got this error message. In my browser console, I have a slew of errors. 
![image](https://user-images.githubusercontent.com/29102861/228639845-95d2ffee-2e28-4560-84d7-b5c38677a4d4.png)

<img width="869" alt="image" src="https://user-images.githubusercontent.com/29102861/228640065-217ee939-5aac-4c22-a328-790f5a50118a.png">
2. I open any of the Raids e.g, Inkeeping & Rewards. I accept Peth's invite to view the Dework board. Then I choose to "Connect with Discord" or "Connect with Github". I see the below error. 

![image](https://user-images.githubusercontent.com/29102861/228645564-a0e00aaf-0abb-4b13-9481-b10b67f39af1.png)
3. Clicking from one page to the next always results in a transition lag that displays text from the previous page. Then it goes away and the new page looks normal. 
4. No quests appear in Quest Explorer (I filtered on both open & closed)
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/29102861/228650709-1d58e541-bada-4cef-96f0-ccb3b54f4bc8.png">

**Comment by vidvidvid** [comment]
I'm getting the same error when trying to port the data: 
<img width="1030" alt="Screenshot 2023-03-31 at 11 08 02" src="https://user-images.githubusercontent.com/35112939/229077512-55a281a9-db11-4509-ba52-b8b62e34a33b.png">
