### ISSUE TITLE
Messed up css of the MarkdownEditor

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#1544]
<img width="741" alt="Screenshot 2023-04-03 at 23 02 38" src="https://user-images.githubusercontent.com/35112939/229762380-7ec3df6e-16bd-4009-b772-0412a4b12005.png">

It looks like there might be a problem in importing the css files in `web/pages/_app.tsx`:
```
import 'react-markdown-editor-lite/lib/index.css';
import 'assets/custom-markdown-editor.scss';
```
The classes from these two files aren't showing up in the console, so I'm assuming it has to do something with this. I don't know how to solve this problem, nor how it got messed up in the first place. On master branch everything works fine.
Help, please

_Originally posted by @vidvidvid in https://github.com/MetaFam/TheGame/issues/1520#issuecomment-1495715724_

**Comment by dysbulic** [comment]
I've been hunting for this for a minute & not having a whole lot of luck.

I just ran `yarn create next-app --example with-chakra-ui next-with-chakra-ui-app` which creates a Next 13 / React 18 app & the global styling acts as advertized.

I tried removing as much of the `Head` and Chakra-UI elements as I could with no effect.

Then I upgraded Next to match versions with the test program.

Finally, I found the line `{ sideEffects: false }` in the Next config. Disabling this fixes the CSS imports. Unfortunately, it also increases the bundle sizes by about 40%.

I'm still trying to get the bundle size down, but you can see the current status in #1545.
