### ISSUE TITLE
[MyMeta] Add 3Box Profile Edit Component to Setup Flow

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#155]
Add the profile edit widget near the end of the "about you" section of profile setup flow: 

https://3box.github.io/3box-profile-edit-react/examples/dist/
https://github.com/3box/3box-profile-edit-react

**Comment by dysbulic** [comment]
3Box's profile editor is soon to be dead being replaced by IDX.

The closest thing to a profile editor as of writing is [self.id](https://github.com/ceramicstudio/self.id) which will copy the 3Box profile into IDX.

This is supposedly going to be done automatically closer to mainnet launch.

**Comment by dysbulic** [comment]
This is replaced by #769.
