### ISSUE TITLE
Error from `null` `data.status` in questchains integration

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1554]
### What happened?

On [metagame.wtf/play/paths/engaged-octos-path](https://metagame.wtf/play/paths/engaged-octos-path) there is an error:

```
health.js:19 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'chains')
```

In looking at the relevant code, the property that's `null` is `data.status`.

Any help would be appreciated @dan13ram or @vidvidvid.

### What did you expect to happen?

No error.

### How can we reproduce the problem (as minimally as possible)?

Visit the page.

**Comment by Seroxdesign** [comment]
Seems like it's been resolved with our ID fix
