### ISSUE TITLE
It's impossible to delete profile sections

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1556]
### What happened?

When you click on the delete `❌` on a profile section, it jumps away & doesn't delete.

https://user-images.githubusercontent.com/181523/236425786-0b1fb764-a211-479a-91d9-700f1f58765a.mp4

### What did you expect to happen?

The profile section to be removed.

### How can we reproduce the problem (as minimally as possible)?

Edit a profile & try to delete.

**Comment by Seroxdesign** [comment]
This isn't an issue for me

**Comment by dysbulic** [comment]
> This isn't an issue for me, was this ever addressed?

It appears to have resolved itself somewhere along the line. I'm no longer seeing it in production.
