### ISSUE TITLE
Add support for other calendars in a user's profile

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1560]
### What would you like to be added?

In @davort's latest design there is an option to use meet with wallet OR another calendaring service.

The other calendaring service is just a link. We could probably use this to create a "custom text block" in the backend with this data.

### Why is this needed?

Most people don't use MWW, so pragmatically, we should be able to meet users where they're at.

**Comment by peth-yursick** [comment]
Maybe unnecessary now that we have the "links block" that people can use as a linktree?

**Comment by Seroxdesign** [comment]
> Maybe unnecessary now that we have the "links block" that people can use as a linktree?

This would resolve it tbh, no point in adding more onto the profile if it can be done through the links @peth-yursick thoughts?

**Comment by peth-yursick** [comment]
> > Maybe unnecessary now that we have the "links block" that people can use as a linktree?
> 
> This would resolve it tbh, no point in adding more onto the profile if it can be done through the links @peth-yursick thoughts?

yeah thats what I meant
