### ISSUE TITLE
Improve guild membership data - Development

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1561]
As proposed [here](https://forum.ceramic.network/t/proposal-mymeta-idenity-aggregator-for-daoists/564):

Build out more functionality for pulling in DAO memberships of existing MyMeta users, through data sources like DAOHaus. This will fill in some data gaps, data that we can eventually put on Ceramic for other apps to use as well

The primary goal of this is to make it easier for users to add guilds that they are part of. This functionality has been fully discussed and designed in #1539; please carefully read through that discussion ([starting here](https://github.com/MetaFam/TheGame/issues/1539#issuecomment-1664159399)) before beginning implementation. 

### Background Information and Terminology

- **Verified Guild** is a guild showing up in the MetaOS [guilds page](https://metagame.wtf/guilds) that has been verified by Metafam.  Verified Guilds are in the `guild` table, memberships are in `guild_player`, and metadata is in the `guild_metadata` table.  They are added through one of two processes: 
  - Manual addition by Metafam through a script or Hasura admin console. These guilds have no related `guild_metadata` table.  
  - Added through a gatekeeper process: a user wanting to add their guild starts [here](https://test.metagame.wtf/join/guild) and fills out a typeform to signal alignment. If this is approved by Metafam, they are redirected to the "join guild start" page. This requires the user to be logged in, the guild to have a Discord server, and the user to have some sort of administration access to that server. Once the form is submitted and guild is approved, there is an automatic daily job that keeps in sync members of the Discord server and guild members in MetaOS. These guilds I will refer to as **Verified Discord Guild**s.
- **Unverified Guild** is a guild added through the new "add guild" functionality described below. These guilds have both their own tile in the guilds page AND separate guild page, just like a verified guild. These should be distinguished in the UI with some sort of "UNVERIFIED" notice, warning of the lesser legitimacy of these types of guilds.
- **DaoHaus Guild** is a guild that was automatically linked to a player via the DaoHaus API. When a player signs up, we pull any DaoHaus memberships automatically for their ETH address.  These memberships are [displayed in the Guild Memberships section of a player's profile](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=360-16436&mode=design&t=KahCEL9xIoCWNzXc-4).  Note that these guilds DO NOT show up in the Guilds page in MetaOS. They are persisted in the `dao` table, and linked to players in `dao_player`.
 
### New Functionality to be Built

- On your own player page, you can [edit guild memberships](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=356-7526&mode=design&t=KahCEL9xIoCWNzXc-4)
- In the guild memberships panel edit mode, you can
  - [Reorder guilds](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=360-16267&mode=design&t=KahCEL9xIoCWNzXc-4) (for both verified and unverified guilds) that you are a member of by drag and drop, then saving the changes
  - [Hide auto-detected memberships in verified guilds](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=360-16268&mode=design&t=KahCEL9xIoCWNzXc-4) 
  - [Adding a membership to an unverified guild](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=356-7300&mode=design&t=KahCEL9xIoCWNzXc-4) There is a whole new flow to search for guilds and add memberships to existing ones. (Note that there is no approval step here!)
  - [Add a new unverified guild](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=360-16269&mode=design&t=KahCEL9xIoCWNzXc-4) There is a whole new flow where when a desired guild is not found through searching, the player can add a new one. The data to be collected here is the same as the Add Verified Discord Guild form (and should ideally reuse the same form, minus Discord-related fields)
- Unverified guild tiles should display an "unverified" tag (Unfortunately, I don't think this has been designed, reach out to Dave for guidance)
- Unverified guild pages should also display "UNVERIFIED" prominently

### Schema Updates

I see a few new columns that will be necessary:
- We will need to persist ordering information for a given player for all types of guilds. I envision a new `player.membership_metadata` JSONB column with a schema something like 
  ```
  {
    guildType: 'guild',
    guildId: <uuid>,
    position: <integer>
  }
  ```
  We could potentially also store this information in new `guild_player.position` and `dao_player.position` columns, but this would probably be more difficult.
- `guild_player.visible`. We already have a currently-unused `dao_player.visible` column that we can use for hiding these auto-fetched memberships.
- `guild.legitimacy` with potential values `VERIFIED | UNVERIFIED`. Usually we create an enum table for this sort of thing, e.g. `GuildLegitimacy`. See existing enum tables, e.g. `GuildType`.

A more all-encompassing refactor of guild/DAO tables may be in order for this as well; happy to discuss on a call.

### Additional notes
- When building the new "edit guild memberships" panel, please honor [Dave's detailed design spec](https://www.figma.com/file/vzrD9jHcKv2T5V8ikrGtUu/Improve-guild-membership-data?type=design&node-id=380-26792&mode=design&t=KahCEL9xIoCWNzXc-4)
- Please add a new environment variable `UNVERIFIED_GUILD_APPROVAL_REQUIRED=false` and use it in the `saveGuildHandler`. This will allow us to prevent abuse should it become a problem.

### Backend:

- Create a new action:  addUnverifiedGuild and copy the same file from `/backend/src/handlers/actions/guild/saveGuildHandler.ts`
- Remove requirement for connecting to discord, choosing roles and admins
- Re-use UI for form
- Hook up to add new Guild button on the player's guild block

**Comment by blaxkspace** [comment]
Interested

**Comment by dysbulic** [comment]
@Seroxdesign, the current behavior is for a user to be able to add themselves to *any* guild, when, if I'm reading this correctly, @alalonde, they should only be able to add themselves to unverified guilds, right?

**Comment by Seroxdesign** [comment]
> @Seroxdesign, the current behavior is for a user to be able to add themselves to _any_ guild, when, if I'm reading this correctly, @alalonde, they should only be able to add themselves to unverified guilds, right?
> 
> To answer my own question, I found the following on #1539:
> 
> > _We definitely want to still show verified guilds in the search results because we don't want them to add a duplicate one accidentally. There will be cases where they are indeed a member of this verified guild but our auto-member-sync system didn't work correctly. In that case, we should display some sort of (i) icon or something proposing a course of action, e.g. "If you are already a member of this verified guild, reach out to us on Discord (link) for help". This (i) icon would replace the (+) button because you can't add yourself to a verified guild._

They should be able to add themselves on to any Guild, whether or not it's verified

**Comment by dysbulic** [comment]
> They should be able to add themselves on to any Guild, whether or not it's verified

Doesn't that remove some of the autonomy from the administrators of verified guilds? It seems like it opens a guild to randos inserting themselves into the members list whereas they should follow the joining procedure defined by the guild.

**Comment by dysbulic** [comment]
@alalonde suggested reusing the existing guild signup form with a few fields filtered out for the unverified guilds.

@Seroxdesign, you created a new form that looks to largely be a duplicate. Why?

**Comment by alalonde** [comment]
> They should be able to add themselves on to any Guild, whether or not it's verified

No. This requirement is specified in detail in this issue's description.
