### ISSUE TITLE
Don't show the switch to Polygon message until necessary

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1580]
### What would you like to be added?

When first connecting to [metagame.wtf](//metagame.wtf), the user is greeted with a toast saying to connect to Polygon. *(Actually, it's the same toast twice, but that's a separate issue.)*

![Screenshot from 2023-07-19 09-54-24](https://github.com/MetaFam/TheGame/assets/181523/88391ddd-1278-45a6-843a-c5f642d283f9)

This is because there's a NFT the user can create as part of the onboarding flow & [’Chievemints](//chiev.es) is on Polygon. Only a small percentage of users will discover the minting option, so that message is unnecessary much of the time.

The switch network message should only display when they arrive at the minting option.

Also, it would be nice if there was an option to programatically ad & switch the network. There are RPC methods for doing this in Metamask & they're supported in other wallets as well.

### Why is this needed?

Currently, the user is asked to switch networks to no end.

**Comment by Innkeeping** [comment]
Nothing is on Polygon anymore.
