### ISSUE TITLE
Display onboarding chat dialog in full screen

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1581]
### What would you like to be added?

Currently, the onboarding chat flow is in a scrollable pane within the site window:

![Screenshot from 2023-07-19 10-49-10](https://github.com/MetaFam/TheGame/assets/181523/58b3ab17-e20f-404f-8673-7287027f62d1)

There's unused space at the bottom & the scroll window, I guess, sort of makes it look like a terminal within the site, but why not have it look like the chat bot is typing to the site?

### Why is this needed?

Having the scroll on the inner pane wastes space & breaks the natural scroll mechanics if the user scrolls outside of the pane.

It would also look more natural if the site was talking to the user rather than this isolated box.

**Comment by Seroxdesign** [comment]
https://github.com/MetaFam/TheGame/pull/1624

**Comment by Seroxdesign** [comment]
Duplicate issue
