### ISSUE TITLE
XP System - Updates and Fixes

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1586]
## The goal

Revive XP system, based off the SEED distributions

## How: 

Query the SEED contract for user's current balance, then maintain the balance within Hasura, creating a new record when the SEED balance changes.

The token balance will go up and down, as they receive, sell and transfer SEED tokens, we only want to pay attention to receiving SEED token

## Mehods:

1. Use the MG safe as a data source of distributions for players:
https://polygonscan.com/address/0xbaf60086da36033b458b892e2432958e219f4ed6

API: https://polygonscan.com/apis

2. Read from selected Safe as default, then in future make space for reading ERC20 token data.

### Hasura: 

1. In Token Table store:
   - Token Address primary key
   - Safe Address
   - Guild UUID
   
| Col Name | Type | Key Type | Null? |
|--------|--------|--------|--------|
| Token Address  | Text | Primary | No | 
| Safe Address | Text | null |  Yes |
| Guild Id | UUID | Foreign: Guild table | No |   

2. Table: Token through time
     -Token Address primary key
     -Foreign Key for user
     -Check what last value was for each user
     -If changed add a new entry: who user was, what balance is, block height of query
     -From list of balances calculate XP (total XP = total SEED received)
     
| Col Name | Type | Key Type | Null? |
|--------|--------|--------|--------|
| userID  | Text | Foreign key: Players | No | 
| Token Address | Text | Foreign key: Tokens |  No |
| Block height | Int |  | No |  
| Balance | Int | | No |
 
3. Table: Cumulative XP - Update VS multiple record being kept
 
| Col Name | Type | Key Type | Null? |
|--------|--------|--------|--------|
| UserId | Text | Foreign key: Players | No | 
| Token Address | Text | Foreign key: Tokens |  No |
| Balance | Int | | No |

Query to polygonscan.api:

```https://api.polygonscan.com/api?module=account&action=tokentx&address=0x4e83362442b8d1bec281594cea3050c8eb01311c&startblock=0&endblock=999999999&sort=asc&apikey=YourApiKeyToken```
        
API Reference: http://api.etherscan.io/apis

Hasura Cronjob will periodically fetch and store the data

### Frontend:

1. Decoupling cumulative XP from the player table
2. Accepting a Guild ID when generating a leaderboard

3. Expand Form for guild onboarding to collect:
   - Optional Safe Address
   - Optional Token Address

Warn guilds, if no Token Adress no access to XP leaderboard, but allow them to showcase membership sorted alphabatically.

4. Allow Guilds to modify their record and add a Safe and/or token address. And if they add a token Address allow them to have a XP leaderboard for their members on the guild page.

### Backend: 

Come up with algorithm for determining cumulative XP

### Why is this needed?

Fixing XP system for leaderboards, preparing to offer DAOs and GUILDs a method to track their player leaderboards.

**Comment by dysbulic** [comment]
This has been done.
