### ISSUE TITLE
Consolidate signing to a single chain

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1597]
### What would you like to be added?

Currently, we utilize different chains for various features of the site:

1. When completing the onboarding game, minting the completion token requires the user to be on Polygon
2. Updating your profile on Ceramic / ComposeDB requires signing on mainnet
3. When completing a questchain, minting the NFT requires Polygon

Relates to #1580 

We should switch all these to Optimism. Lots of discussion on Discord about the chain of choice; I won't get into that here.

- [ ] @dysbulic has switched the onboarding game Chievement over to gasless minting, it just needs to be hooked up to the frontend
- [ ] ComposeDB should sign with a DID on Optimism
- [ ] Questchains should mint gasless or on Optimism

### Why is this needed?

Switching chains is a big barrier to entry for new users and is, at minimum, annoying for all users.

**Comment by Seroxdesign** [comment]
### ComposeDB:

Contact https://3boxlabs.com/ to figure out if data can be migrated from 1 chain to another.

**Comment by Innkeeping** [comment]
This can be closed @dysbulic ?
