### ISSUE TITLE
Seeding Hasura DB locally not working 

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1604]
### What happened?

When trying to run the following command which seeds the DB:

```
yarn hasura:seed-db
```

The command runs with no error, however the DB is never seeded.

![image](https://github.com/MetaFam/TheGame/assets/69639595/46dcaa3b-c827-4a40-80ae-6f6e08ee7d41)

### What did you expect to happen?

The DB should seed properly

### How can we reproduce the problem (as minimally as possible)?

- Clone and install the repo
- Run the SEED db command with docker open
- observe

### Browser and operating system used (if applicable)

- OS: Windows

**Comment by alalonde** [comment]
I just ran this successfully on an empty database.  This is caused by the developer not having a valid `GITHUB_API_TOKEN` env variable set. I just pushed [a commit](https://github.com/MetaFam/TheGame/pull/1615/commits/9a0d972a01222cc60e4cd7fb7b262d8d50623614) to improve the error message.
