### ISSUE TITLE
Node 18 OR 20 update

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1606]
### What would you like to be added?

Node 16 is deprecated

### Why is this needed?

bad

**Comment by Seroxdesign** [comment]
https://nodejs.org/en/blog/announcements/v20-release-announce

**Comment by dysbulic** [comment]
I had to change the `engine` to `>=16` *(instead of `~16`)* or the seeding task wouldn't run in a GitHub Action because it was using Node 18.

**Comment by dysbulic** [comment]
I did this as part of another task.
