### ISSUE TITLE
User unable to update avatar

### ISSUE THREAD

**Issue by luxumbra** [MetaFam/TheGame#1630]
### What happened?

i was trying to change my avatar on my profile and after hitting save I get an error message relating to ceramic and my update isn't saved.

```
errorHandler: SyntaxError: Unexpected token 'S', "Service Unavailable" is not valid JSON}
errorHandler: SyntaxError: Unexpected token 'S', "Service Unavailable" is not valid JSON[[Prototype]]: Object
overrideMethod @ console.js:213
eN @ _app-26a928ac44263dcb.js:456
eo @ EditProfileModal.tsx:269
```

### What did you expect to happen?

I expected for my new avatar to be saved.

### How can we reproduce the problem (as minimally as possible)?

Visit https://metagame.wtf/me and click on the edit icon next to your avatar. Upload new image and hit save. The error appears within a few seconds of the button switching state to read 'uploading images to web3.storage'. Can also be experienced via the profile wizard.

### Is there anything else we need to know?

I have tried this on the profile wizard too where it also fails with the following errors:

```
{errorHandler: SyntaxError: Unexpected token 'S', "Service Unavailable" is not valid JSON}
errorHandler: SyntaxError: Unexpected token 'S', "Service Unavailable" is not valid JSON
[[Prototype]]: Object
eN	@	errorHandler.ts:14
(anonymous)	@	usePlayerSetupSaveToComposeDB.ts:109
await in (anonymous) (async)		
(anonymous)	@	index.esm.mjs:2124
await in (anonymous) (async)		
eU	@	react-dom.production.min.js:54
eH	@	react-dom.production.min.js:54
(anonymous)	@	react-dom.production.min.js:55
re	@	react-dom.production.min.js:55
rn	@	react-dom.production.min.js:106
(anonymous)	@	react-dom.production.min.js:117
oN	@	react-dom.production.min.js:274
eF	@	react-dom.production.min.js:52
ro	@	react-dom.production.min.js:109
nU	@	react-dom.production.min.js:74
nD	@	react-dom.production.min.js:73
```

```
uploadHelpers.ts:15 
 POST https://metagame.wtf/api/storage 503
i	@	uploadHelpers.ts:15
r	@	uploadHelpers.ts:5
(anonymous)	@	usePlayerSetupSaveToComposeDB.ts:65
(anonymous)	@	index.esm.mjs:2124
await in (anonymous) (async)		
eU	@	react-dom.production.min.js:54
eH	@	react-dom.production.min.js:54
(anonymous)	@	react-dom.production.min.js:55
re	@	react-dom.production.min.js:55
rn	@	react-dom.production.min.js:106
(anonymous)	@	react-dom.production.min.js:117
oN	@	react-dom.production.min.js:274
eF	@	react-dom.production.min.js:52
ro	@	react-dom.production.min.js:109
nU	@	react-dom.production.min.js:74
nD	@	react-dom.production.min.js:73
```

### Browser and operating system used (if applicable)

I have tried with Brave (shields on / off) & Firefox on Linux (Pop_OS)

**Comment by dysbulic** [comment]
I just successfully changed my avatar on the production site.

@luxumbra, we're you doing this on a test instance and, if so, is it possible you were doing it in the window where the frontend had started, but the backend had not? *(The backend only starts when it retrieves traffic, so until you use it (plus a minute or so), it'll fail.)*

When he backend isn't running you'll get "`Service Unavailable`".

**Comment by Seroxdesign** [comment]
This has been resolved.
