### ISSUE TITLE
User menu is cut off by the edge of the screen

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#1642]
### What happened?

When you click a users profile icon in the upper right of an authenticated window, the following displays:

![Screenshot from 2023-11-23 11-36-26](https://github.com/MetaFam/TheGame/assets/181523/b1dba866-f8b4-45a8-8b49-c4047d8e0b18)

### What did you expect to happen?

For the text not to be cut in half.

### How can we reproduce the problem (as minimally as possible)?

1. Visit [test.metagame.wtf](https://test.metagame.wtf).
2. Log in.
3. Click on your profile picture in the upper right-hand corner.

**Comment by Udit-takkar** [comment]
can't reproduce this

**Comment by Seroxdesign** [comment]
completed
