### ISSUE TITLE
unable to change profile images

### ISSUE THREAD

**Issue by joseacabrerav** [MetaFam/TheGame#1655]
### What happened?

I'm getting this error while trying to change image on my profile.

**"Error saving profile: web3.storage 500 response"**

![image](https://github.com/MetaFam/TheGame/assets/107449265/9deb81c4-06cb-4b60-9427-203dd37c1ac3)

### What did you expect to happen?

getting images updated

### How can we reproduce the problem (as minimally as possible)?

uploading a new profile image

**Comment by peth-yursick** [comment]
looks like this one already exists, opened by luxumbra #1630
