### ISSUE TITLE
call to action links needs an update

### ISSUE THREAD

**Issue by joseacabrerav** [MetaFam/TheGame#1658]
### What happened?

something we all forgot about - on the community page, players, guilds & patrons all have this call to action on top

![image](https://github.com/MetaFam/TheGame/assets/107449265/2293e831-b039-4028-bb3a-aa0af1bfb84c)

***

![image](https://github.com/MetaFam/TheGame/assets/107449265/f215a8b7-d247-4fc9-a339-aef32d25facf)

but the links still lead to the ugly old signup pages (which we should probably delete) should be changed: 

https://metagame.wtf/join/patron **to** https://metagame.wtf/signup?tab=patron

https://metagame.wtf/join/guild **to** https://metagame.wtf/signup?tab=guild

https://metagame.wtf/play/paths/engaged-octos-path **to** https://metagame.wtf/signup?tab=player

### What did you expect to happen?

updated links

### How can we reproduce the problem (as minimally as possible)?

go to the page where the call to action is displayed

**Comment by Udit-takkar** [comment]
this has been already implemented
