### ISSUE TITLE
Calendar block on the dashboard not working

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1676]
It worked for a bit with the redesign, now in the latest release it doesnt.
The block gives error "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

![image](https://github.com/MetaFam/TheGame/assets/55857222/cd7489b0-4350-4db6-82e8-84d0abc65d12)

**Comment by alalonde** [comment]
I bumped up the RAM on our frontend container; this seems to be fixed
