### ISSUE TITLE
On landing page, many image URLs are broken

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1678]
### What happened?

<img width="817" alt="image" src="https://github.com/MetaFam/TheGame/assets/1402582/5dfe45e4-aeef-4d76-83ea-aa0b44ceae45">

The broken ones seem to be hot-linked from twitter

### What did you expect to happen?

They should load properly

### How can we reproduce the problem (as minimally as possible)?

Go to "Who we are" section on landing page

**Comment by Udit-takkar** [comment]
@alalonde some of the urls are ipfs link which are invalid

<img width="1440" alt="Screenshot 2023-12-28 at 12 51 13 AM" src="https://github.com/MetaFam/TheGame/assets/53316345/94179df4-27aa-4455-bcec-eb4c29527b22">
