### ISSUE TITLE
Broken profile images should have a fallback

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#1681]
### What would you like to be added?

So long as our profile images are hosted elsewhere, we will always have some amount that are simply broken. We should handle this case gracefully:

- Fallback to a default, such as a generated jdenticon (the default for players with no profile image)

Ideally we would also remove the profile image reference from our DB after a certain number of failed fetches (or number of days without it resolving), but this would require a fair bit of effort.

### Why is this needed?

So long as our profile images are hosted elsewhere, we will always have some amount that are simply broken. We should handle this case gracefully.

**Comment by Udit-takkar** [comment]
@alalonde did you already implement this? I see the jdenticons package used in getPlayerImage function

**Comment by alalonde** [comment]
No, I just fixed the default images in that other PR. This goes a step further to use that fallback image when the IPFS one fails to load

**Comment by Seroxdesign** [comment]
Unfortunately the issue here is that we would need to set some sort of timeout check on all the images which would further slow down a very slow community page.

It's also a hack that hurts us in the long run, the solution here is to use our own Gateway, switch to a reliable CDN or simply not display images... let me know what you think

**Comment by Seroxdesign** [comment]
#### Potential Solution:

1. Load fallback first
2. Use onload listener to then swap out the IMG once it resolves/fails:

https://www.javascripttutorial.net/javascript-dom/javascript-onload/

**Comment by Seroxdesign** [comment]
#1696
