### ISSUE TITLE
Integrate Optimism's EAS into attestations on User Profiles

### ISSUE THREAD

**Issue by Seroxdesign** [MetaFam/TheGame#1687]
## What

A new block in the user profile can be added which displays your attestations, and allows other Players to write attestations for you, this should integrate optimism's EAS: https://optimism.easscan.org/

### Why is this needed?

This is part of the bigger Optimism Grant project, and is one of the main milestones.

**Comment by Innkeeping** [comment]
Was this completed? @Seroxdesign @dysbulic

**Comment by Innkeeping** [comment]
Check Ethers6 update @dysbulic
