### ISSUE TITLE
Old DAO links on guild profiles not following the design

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1689]
We've integrated the new "links block" design to make the link embedded in profiles look nicer, but this didn't apply to guild DAO links.

As can be seen on the MetaCartel guild page:
![image](https://github.com/MetaFam/TheGame/assets/55857222/fddd7f81-2244-4593-9bbe-092f0816d740)

- Discord is displayed nicely according to the new design
- Our DAO isn't, its using the old design & the long abandoned pixel font

**Comment by Seroxdesign** [comment]
![Uploading image.png…]()
