### ISSUE TITLE
Remove Discourse forum links in codebase

### ISSUE THREAD

**Issue by HHH-GH** [MetaFam/TheGame#1737]
### What happened?

User wrote a post on the forum, @peth-yursick said "how did you find the forum b/c we don't use it"

![image](https://github.com/MetaFam/TheGame/assets/92962228/6ae77ac0-d71c-4950-8c13-3c60e58823ae)

### What did you expect to happen?

No posts on forum?

### How can we reproduce the problem (as minimally as possible)?

I guess the link to the forum was found on Engaged Octo's Path quest, but ...

https://app.questchains.xyz/polygon/0xea512722cc047bfdbe90a1a2750491e89a818ca7

### Is there anything else we need to know?

Searching the codebase finds some links to the forum. 

![image](https://github.com/MetaFam/TheGame/assets/92962228/eeb3b982-5c2b-4225-944c-3f96e90de6d3)

https://github.com/MetaFam/TheGame/blob/73ce8151b69f6e501761ca2bb7c803ea00913a0e/packages/discord-bot/src/config.ts#L60

https://github.com/MetaFam/TheGame/blob/73ce8151b69f6e501761ca2bb7c803ea00913a0e/packages/web/pages/404.tsx#L107

Didn't find any links to [Engaged Octo's Path quest](https://app.questchains.xyz/polygon/0xea512722cc047bfdbe90a1a2750491e89a818ca7)

**Comment by peth-yursick** [comment]
Ahh yeah, the damn 404 page which we also never redesigned to match the new color scheme 🤣
Good find, thank you!

**Comment by Innkeeping** [comment]
This can be closed @dysbulic ?
