### ISSUE TITLE
Removing old link from profile opening screen

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#1739]
On https://metagame.wtf/start when you click "dont have a wallet" - the "Ethereum" link still links to the wikipedia which has been deprecated. This should be replaced with the new house of ethereum playbook, or the link should just be completely removed.

![image](https://github.com/MetaFam/TheGame/assets/55857222/d58d62bb-dae2-40d2-8704-fd82eb52ce67)

**Comment by Innkeeping** [comment]
This is corrected to point to [wtf is Ethereum playbook](https://metagame.wtf/academy/wtf-is-ethereum)
