### ISSUE TITLE
Add hover over for Creator contract addresses in playbooks on academy

### ISSUE THREAD

**Issue by Innkeeping** [MetaFam/TheGame#1757]
### What would you like to be added?

Add hover over for Creator contract addresses in playbooks on academy (address above playbook title) in I believe packages/web/components/QuestChain/QuestChainDisplay.tsx

### Why is this needed?

To clarify what the address is to the user completing a playbook without having to click on it and leaving the page to a profile page in app.questchains and getting lost.  Was a suggestion per a player completing playbooks.

**Comment by CrisLeash** [comment]
Yea, it would be great that once ur in metagame.wtf/quests, you stay there a complete the task, without having to log into queschains.xyz - so once a quest is complete it should automatically fill in into questchains.xyz from metagame.wtf

**Comment by Innkeeping** [comment]
Also see : #1771

**Comment by Innkeeping** [comment]
> Yea, it would be great that once ur in metagame.wtf/quests, you stay there a complete the task, without having to log into queschains.xyz - so once a quest is complete it should automatically fill in into questchains.xyz from metagame.wtf

It does forward to questchains, you should not have to log into questchains to complete a playbook.  There does need to be some clarity on 'awaiting approval' ref: #1770

**Comment by Innkeeping** [comment]
Looks like this happens now! Thanks @dysbulic

**Comment by Innkeeping** [comment]
Looks like this happens now! Thanks @dysbulic
