### ISSUE TITLE
[Bug] My metagame with walletconnect and gnosis safe multisig

### ISSUE THREAD

**Issue by vanmoortel** [MetaFam/TheGame#176]
Can't connect my Gnosis Safe Multisig with walletconnect.
![image](https://user-images.githubusercontent.com/54771141/98656698-3f7dfd80-2341-11eb-9a39-bc25a138a9e7.png)

**Comment by nicolas-law** [comment]
@vanmoortel did you fix this? And if you did, how? :)

**Comment by vanmoortel** [comment]
Hello @nicolas-law  😃 
I contacted the gnosis support and they told me that they don't support message signing :/
