### ISSUE TITLE
[MEGA ISSUE] Discord as source of truth for guilds

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/TheGame#184]
### Context

Currently we use Moloch / Aragon as a means for discovering DAOs and other external guilds.  There is a Daohaus API for exploring these DAOs, however, any given guild / DAO must use Moloch / Aragon for this API to know about them.  We have observed that almost every organization who has expressed interest in becoming a Metagame guild has their own discord server, however.  And that discord provides a robust API that can be leveraged to easily onboard guilds.

### Design

We will create a Discord Bot that can be used to both onboard guilds and provide a way of interacting with MetaGame.  

- MyMeta "Join as guild" page: If a guild expresses interest in joining MetaGame, they can navigate to a "Join as a guild" page within MyMeta. This will provide some introductory text about MetaGame as well as a [Discord auth URL](https://discordjs.guide/preparations/adding-your-bot-to-servers.html#bot-invite-links) that can be clicked to add the bot to their Discord server.  
- Once accepting the various permissions required by the bot, the user will be redirected back to MyMeta, at which time we will attempt to fetch the necessary metadata to create the Guild in MetaGame. 
  - We can match existing guilds by manually add a `discord_id` to the existing guilds in our DB
  - Initial data to collect and allow editing: 
    - `guildname` (basically a username for a guild)
    - `description`
    - `discord_invite_url` (just the code, we will prepend "https://discord.gg/" to the input field
    - `join_button_url`
    - `logo` (fetch the image and display, allow editing the URL. Editing will display the new image)
    - `moloch_address` ?
    - `name`
    - `type` enum: `FUNDING` | `SOCIAL` | `SERVICE` | `PROJECT` | `RESEARCH`
    - `website_url`
  - We will also fetch all the roles for the discord server and populate a multi-select widget. This will allow the user to select the roles that indicate membership in the guild. We will also ask for roles that indicate some sort of administrator / owner status.
- On submission, add the guild + metadata. Save the discord server ID on the guild table and discord membership role IDs in a new JSONB column. Also, query the list of members in the discord server, filter by whatever roles count as members, match the member's discord ID with our `player.discord_id` and insert the match into the GuildPlayer table.  Only add discord guild members that already have player accounts in MetaGame.

### Prerequisites

- Refactor the DB to better match this deeper Discord integration. Move discord_id from player_account / discord to main player table, as well as adding a discord_id to the guild table. Migrate all the data along the way.
- Move the guild-specific columns from the `player` table in `guild_player`. Not sure at this point what these are.
- Get #355 merged and deployed with the new MetaGame bot. It would be nice to dogfood the initial onboarding with the MetaGame (Metafam) discord server, but we can probably (hopefully?) sufficiently test with dev discord servers.

### Forthcoming

These should be broken into separate issues:

- Get your XP / Stats / Player card
- Onboarding enhancements: Add eth address, discord ID, discourse ID in mymeta player setup flow?
- Edit "memberships" section of profile setup to [query the discord servers the bot has access to](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=guilds), determine if the player is already a member of one or more, and display a list of matched servers (like it does now with DAOs) that are pre-checked.

**Comment by peth-yursick** [comment]
Good job writing this out!

>     * `moloch_address` ?

Maybe this one should be dao_address rather than Moloch specific.

Also this doesn't mention the review step anywhere, only "join as guild", but not every guild that tries that will be accepted.

**Comment by alalonde** [comment]
> Good job writing this out!
> 
> > ```
> > * `moloch_address` ?
> > ```

OK, yeah, i'll rename that column. Not super familiar with the various DAO tooling out there.

> Also this doesn't mention the review step anywhere, only "join as guild", but not every guild that tries that will be accepted.

Yes, thanks for clarifying that, I was wondering if we would just accept everybody.  What we can do is just add a `status` flag or something on a guild and set it to `pending` by default.
