### ISSUE TITLE
[Mega Issue] Player Profile 

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#185]
- Allow users to update their role on frontend + add the role field to Player table in Hasura
-̶ ̶S̶k̶i̶l̶l̶s̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶c̶o̶l̶o̶r̶ ̶c̶o̶d̶e̶d̶
- Allow people to specify their "top skills" (max 3) + other skills as a separate list
-̶ ̶C̶o̶n̶n̶e̶c̶t̶ ̶N̶F̶T̶ ̶g̶a̶l̶l̶e̶r̶y̶ ̶s̶e̶c̶t̶i̶o̶n̶ ̶t̶o̶ ̶3̶B̶o̶x̶ ̶d̶a̶t̶a̶
- ~~Allow players to set their Timezone~~
-̶ ̶H̶i̶d̶e̶ ̶s̶e̶c̶t̶i̶o̶n̶ ̶o̶n̶ ̶t̶h̶e̶ ̶p̶r̶o̶f̶i̶l̶e̶ ̶w̶h̶e̶r̶e̶ ̶t̶h̶e̶ ̶u̶s̶e̶r̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶h̶a̶v̶e̶ ̶a̶n̶y̶ ̶d̶a̶t̶a̶

**Comment by dan13ram** [comment]
- Show shares for DAOHaus Membership instead of XP
- Make profile sections editable only for user's own profile
- Disable `Collab` button until we have the feature ready

**Comment by dan13ram** [comment]
- Replace all occurrences of images with the https://nextjs.org/docs/basic-features/image-optimization
- Replace icons from `react-icons` with `chakra-icons`

**Comment by dysbulic** [comment]
> - Allow users to update their role on frontend + add the role field to Player table in Hasura

Is there a design for how the roles are to be presented?

> - Allow people to specify their "top skills" (max 3) + other skills as a separate list

Would it be sufficient to allow users to sort their skills so they can put their top *x* first? Is there a specific place three skills are needed?

**Comment by dysbulic** [comment]
> - Replace all occurrences of images with the https://nextjs.org/docs/basic-features/image-optimization

The issue with this component is that it only allows for pixels in specifying the dimensions. Pretty much none of the images are specified in straight pixel values.

Is this component important enough that it is worth whatever hackery it will take to get it in place?
