### ISSUE TITLE
Integrate BrightId to MyMeta

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#186]
Allow users to link their BrightID to their player profiles
Show a "verified" checkmark beside the name if users are BrightID verified
Store info in our DB

**Comment by dysbulic** [comment]
BrightID checks the uniqueness of a user relative to an application context. Applications [have to be added](https://dev.brightid.org/docs/guides/docs/basic-integration.md) by the BrightID team before they can be used.

[This form](https://www.brightid.org/#use-in-your-project) is for contacting the team, or there is [a Discord](https://discord.gg/K3y8rdfV).

I'm assuming this hasn't been done yet, but wanted to verify before proceeding.

**Comment by dysbulic** [comment]
BrightID doesn't prevent multiple accounts from being created by a single individual. The application assigns an ID to each account, and when BrightID is checked it will return all the IDs that have been verified with that BrightID in the order they were added.

If someone registers multiple accounts, would you want to only show the first ID as being BrightID certified?
