### ISSUE TITLE
MetaSys - Create a draggable / resizable window system for MetaGame "apps"

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#188]
Inspiration:
- https://poolside.fm
- https://live.ethonline.org/
- https://github.com/arturbien/React95

https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-(Copy)?node-id=3003%3A37

**Comment by alalonde** [comment]
I used [PhosporJS](https://github.com/phosphorjs/phosphor) for a previous project. It was great though we ended up forking it, and the original is no longer supported it seems.
