### ISSUE TITLE
Move discord bot logic into TheGame repo

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/TheGame#20]
Old repo: https://github.com/MetaFam/bot

If we can move this into this repo it will let us easily build more features on top of it. We should probably re-write it in TypeScript as well since Discord.js has pretty good TS support.

Currently the bot updates files in TheSource repo for sourcecred to use, but once we implement generating the identities file from the database then we can update it to push the data into our DB directly.  However, with the new ledger stuff that @decentralion is working on, that might be wasted effort since the way identities are being linked is changing. They will all be going into the ledger now, so we might want to have a representation of that in our database. e.g. when a user is created, we push the identity to the ledger file on github)

We can also start implementing other bot functionality such as fetching your XP, your SEED balance, etc once we have this here

**Comment by alalonde** [comment]
This is underway; groundwork was laid in #484

**Comment by dysbulic** [comment]
@alalonde, this has been done, yes?
