### ISSUE TITLE
[MetaOS] Mega Issue - Design / Roadmap

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#204]
Following Friday's product design raid, we're moving onto building the platform.

## [Platform Design](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-Copy?node-id=3198%3A3)

Not sure if we're building mobile-first from the get-go, but this is how I see it working on desktop vs. mobile.
![image](https://user-images.githubusercontent.com/55857222/101480653-4570f980-3954-11eb-9bac-302ec5569bae.png)
- The main differences are that on mobile, the "journal & goals" tabs would be collapsed by default & there would be no navigation bar, but the floating MG crystal instead. It would give the "navigation bar buttons" on single press, and open the full app drawer on double tap.
- If making the mobile version like this makes it impossible to have a single build for both mobile & desktop, we can drop the navigation bar from the desktop version and have also have a floating crystal that slowly follows the mouse as you navigate the page.

For anyone who missed out, here's the full outline of the platform:

### v0.1 - A navigation bar with an app drawer & an empty background.
![image](https://user-images.githubusercontent.com/55857222/101479219-22dde100-3952-11eb-87a2-e47a2ee7597e.png)
- A) navigation bar
- B) nav. with app drawer open
A user must be able to open any of these "apps" inside an iframe window, as suggested in this issue.
- First version of the app drawer ✅
- [Second version issues](https://github.com/MetaFam/TheGame/issues/254)

### v0.11 - The beginning of a dashboard in the background.
![image](https://user-images.githubusercontent.com/55857222/101479368-60db0500-3952-11eb-80c3-5260d6745669.png)
- The design is super-rudimentary, a mockup sort of thing. But unless it gets updated in the coming few days, just go with it. Simply have these containers that display XP & Seeds to begin with, you can drop the morale & carbon footprint for now.

###  v0.12 - A better dashboard.
@Polycarpik' Journal quest should be ready before this step, so it can be integrated as suggested in the "v0.11" rendering above.
The dashboard itself should have a better design by then, and it shouldn't just display "XP & Seeds" but also "+% this week" for each of them. Hopefully we also get the morale indicator by then & someone to estimate our carbon footprint.

### v0.13 - Make it mine! Populating the dashboard.
![image](https://user-images.githubusercontent.com/55857222/101479967-4e150000-3953-11eb-8c6b-fc17e03e39b5.png)
- Mine as in yours, not as in mining. 
- We should have a login by then. metagame.wtf will be the public version, and then my.metagame.wtf is the post-login version where you can customize the theme, the dashboard etc.
Custom backgrounds to begin with.
- Then, a player should be to take any app they opened inside a window, and pin it to their dashboard.

### v0.2 - Start dApp integrations

- The very first deep dapp integration will probably be the front-end components for our Balancer-based Seed market. It will have its own "Seed subscription page", looking [something like this.](https://www.patreon.com/epicmusicvn)
- Following it, we should get in Paco's Mooni, to help people go directly Seeds to fiat.
- Then, something fun, let's get [Audius](https://audius.co/) in there! Talked to Cooper, [seems ready](https://audiusproject.github.io/api-docs/#audius-api-docs).

### Main Quests

- One of the most critical quests is @pakokrew's **Seed Market**. Its basically 2 lists, 1 listing all the things that players & guilds of MetaGame have in supply & all the things that they need. Basic supply & demand.
- **ValueFeed** - Building on @benoxmo's work @nicolas-law took it a step further, and now we need to take it multiple steps further. He said he wants to rewrite it in TypeScript, but that's beside the point of this post. The next big goal is to get a filtered feed of the most valuable things happening on Discord channels, Github & Discourse - onto the background of the platform, below the dashboard.
- Other than that, **Quests**: the questing system itself should be moved from Discord to the website. We need a place where we can post MetaGame quests, and for players to claim & complete them. We can start with something simple, eg. if we have the "quest complete" backend feed to Discord, we can easily loop it back to Sourcecred.
- After that, the user quests! Its different than the market itself because its about labor & smaller chunks of it. While the on the market itself, you post "hiring a front-end engineer", the "user quests" system is more like a bounty board for temp work.

### Side Quests

- **Install App**: The app drawer should have an empty slot called "install app", which would ask the user "do you want to install it for yourself or MetaGame as a whole?" & "is this app useful for your project or MetaGame as a whole?" If the user wants it installed for MetaGame as a whole, an issue gets opened and its decided whether its good enough, and whether its useful for the user or MetaGame, then we can figure out whether the user needs to pay for the install or get rewarded.
- **Calendar**: A collaborative calendar for DAOs to align on meeting times. Think gcal + doodle but token curated. Now think MVP for that. We'll probably be doing this in collab with Gnosis and should be fairly well paid. Ping me for more info on this.
- **JustAsk**: MetaGame Quora, basically. Ask questions & reward answers with Seeds.
- **DebateIt**: A small app for making decisions. We usually discuss things on Discord or on forums, but things get buried in a stream. We need to have a fixed places for the "summary", "for" & "against". Something like this: 
![image](https://user-images.githubusercontent.com/55857222/101483756-ed88c180-3958-11eb-8103-6f1b533ed2ad.png)
If you want to build this, just ping me and I'll make a proper design 🤣

### Trivial Quests

Just some fun things to do, could be high impact but fairly low effort.
- **Ticker**: Its a really small thing, just a ticker line at the bottom or the top of the screen, displaying the price of Seeds, community sentiment, news, in-game tips & player-broadcasted messages.
- **1MillionSeeds**: Think 1million pixels but token curated. Extra mechanic: the screen space gets diluted as more Seeds are minted.
- **Memecraft**: A mini-app for photoshop battles & photoshop tennis. We're already playing photoshop tennis on Discord, but it would be cool to have a proper interface for it that keeps track of the images etc. Could have battles between them and whatnot.

_Note: all the icons are simply emojis, the reason they may look different to you is because you're on another OS._

**Comment by pakokrew** [comment]
Would like to discuss a little bit about that "windowing" idea. The possibility for users to open windows, move, resize them, pin them. 

I personally don't like this, even if sometimes it's fun for things like poolside.fm, but I'll try to explain why I think it's not a good idea to start with that. 

First, I believe that we should first focus on what we want to build: what's inside the windows, not how they are displayed. 
Building such a platform will take us a non-negligible amount of work, will have to be maintained and highly bug-prone (bad memories with interspace). That time could be instead spent on building important stuff first.

That way of creating website, despite being fun and vintage, is totally counter-ergonomics. In addition to not being mobile-friendly, it's neither responsive. It will behave very differently on different OS and screens. It's not common, regular people will get confused about how that works. That's something very geeky, reminds me customizing linux desktop environment, and that's something most people don't do. Do we want to be inclusive or only onboard debian kernel developers ?

Lots of 'apps' will not display well on small windows some may fit like tickers, but some other like profiles&quest won't.

I would better suggest to have a default dashboard layout, the app drawer would be just a router to different pages. Each "window" being one full page. Small stuff like seeds&XP ticker could be on the main page. People that use the app for the first time will not be confused having an empty dashboard and lost in the choice of what app they can add.

I mean, we (almost) don't have anything now, we need to build all these blocks one by one. Most of people will want to see the same stuff at the beginning. Customizing our own dashboard could come at later iterations, only for those who wants it.

**Comment by plasmacorral** [comment]
> First, I believe that we should first focus on what we want to build: what's inside the windows, not how they are displayed.

> ...Do we want to be inclusive or only onboard debian kernel developers ?
 
> Lots of 'apps' will not display well on small windows some may fit like tickers, but some other like profiles&quest won't.


I emphatically agree with this sentiment, Pakokrew.  Build the platform out before adding customization and the technical debt that comes along with maintaining the Burger King "Have it your way" approach.  Having all the accouterments is hard to appreciate if the beef patty isn't fully cooked.

p.s. While I'm eager to learn, I personally don't yet have the dev skills to do any of the heavy lifting.  Regardless, I'm here to try and help.

p.p.s. Don't eat Burger King, that shit is foul even when fully cooked.

**Comment by peth-yursick** [comment]
> I would better suggest to have a default dashboard layout, the app drawer would be just a router to different pages. Each "window" being one full page. Small stuff like seeds&XP ticker could be on the main page. People that use the app for the first time will not be confused having an empty dashboard and lost in the choice of what app they can add.

There will definitely be a default dashboard, and it won't be customizable from day 1.
What you see on the wireframe is just a placeholder for what the default dashboard is supposed to be. 
Those should be the very basic default info displayed, but there should also be things like "daily quests", "upcoming events" etc.

> I mean, we (almost) don't have anything now, we need to build all these blocks one by one. Most of people will want to see the same stuff at the beginning. Customizing our own dashboard could come at later iterations, only for those who wants it.
We actually do already have every single one of these blocks. All of these icons were taken [from the wiki](wiki.metagame.wtf/), where they currently reside & lead to existing pages. Its just that they are opened inside a new tab which is lame.

I agree with you about prioritizing making the default good vs making it a blank slate, but I still feel pretty strongly about the windows part.
On mobile, everything should be opened in full screen, no doubt about that. But I think for the desktop version, the windows are crucial to have a unified experience with so many external things.
MetaGame will always be bringing things inside of its interface, things that are out there. 
Long term, we should strive to make frontends for dapps that fit cleanly inside the dashboards widgets or whatever, but for now I think the iframe windows are an important part of bringing all of these pieces of MetaGame into a single interface.
I mean.. Just look at the wiki, having 12/13 most important buttons inside MetaGame simply open inside new tabs is.. Sub-optimal to put it mildly 😅

**Comment by davort** [comment]
Hey everybody! Just wanted to post the first finalized batch of designs for the Dashboard, covering laptop/PC, tablet and phone layouts. 
![CleanShot 2021-02-14 at 11 03 46](https://user-images.githubusercontent.com/1573304/107890438-6c7e1580-6f19-11eb-9c81-9787a382b765.png)
If anyone's is up for building this, I'd be delighted to work with you and support the implementation! There is a separate issue open for that: https://github.com/MetaFam/TheGame/issues/337

**Comment by pakokrew** [comment]
> Hey everybody! Just wanted to post the first finalized batch of designs for the Dashboard, covering laptop/PC, tablet and phone layouts.


This is good looking !
And also very interesting, however, there's not such things as Journal, Moral, carbon footprint, Claimed quests, personal goals, ...
What do we do with these?

**Comment by peth-yursick** [comment]
> there's not such things as Journal, Moral, carbon footprint, Claimed quests, personal goals, ...
> What do we do with these?

I think its fine to have it hardcoded to begin with?
Though I should probably open issues for all of these things..
Think I should open a "Dashboard megaissue" or have a separate issue for each of these things?

- XP stuff kind of exists with basic stats through the bot, needs to be fed to the site
- Hammad is working on the first version of the Journal (an XP feed to begin with)
- Moral doesn't but shouldn't be too hard to implement, it will be based on a "how are you doing?" prompt when logging into MetaGame.
- Carbon footprint similarly shouldn't be too hard
- Claimed quests will come from your quests module

**Comment by geleeroyale** [comment]
Closing this because its super outdated according to @peth-yursick
