### ISSUE TITLE
Rename database models

### ISSUE THREAD

**Issue by pakokrew** [MetaFam/TheGame#220]
Our model names in our database currently have different casings.

Would be better to have all of them written the same way.

Suggested casing for example Player Account: `player_account`

- [ ] Rename all the models

- [ ] Rename Account -> player_account

- [ ] Update all the frontend/backend graphql queries

**Comment by alalonde** [comment]
I'll take a look at this since I almost tackled it in my timezone branch. I can see this causing great merge pain though for active contributors..

**Comment by alalonde** [comment]
Fixed by #255
