### ISSUE TITLE
[MetaOS] Micro Front End Experiment MVP with Wiki

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/TheGame#227]
To test out this micro frontend approach, we can start with trying to integrate the wiki into mymeta. Options:

https://single-spa.js.org/docs/module-types
- Seems better for route based micro-frontends (probably more applicable for something like the wiki), but might also work for the modular profile sections.

https://bit.dev
- Seems better for component based micro front ends (e.g. profile modular sections)

**Comment by peth-yursick** [comment]
I don't know much about micro front ends, but is this something that could fix the issue we were talking about @luxumbra?
