### ISSUE TITLE
Fix player card aspect ratio scaling

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#241]
The player cards still appear too wide on my screen & they get even shorter depending on info.
It shouldn't scale the way it does:
![image](https://user-images.githubusercontent.com/55857222/102726025-94873900-431b-11eb-9871-9f370762df2a.png)
It should retain an aspect ratio of something like 2:3, regardless of screen size & info contained.

**Comment by dan13ram** [comment]
so do you want it to show large empty spaces for users without any updated information, for ex: burrrata  ?

**Comment by peth-yursick** [comment]
> 
> 
> so do you want it to show large empty spaces for users without any updated information, for ex: burrrata ?

yes

**Comment by alalonde** [comment]
> The player cards still appear too wide on my screen & they get even shorter depending on info.
> It shouldn't scale the way it does:
> ![image](https://user-images.githubusercontent.com/55857222/102726025-94873900-431b-11eb-9871-9f370762df2a.png)
> It should retain an aspect ratio of something like 2:3, regardless of screen size & info contained.

Is this screen shot what you want it to look like? or what it currently looks like

**Comment by peth-yursick** [comment]
> 
> 
> > The player cards still appear too wide on my screen & they get even shorter depending on info.
> > It shouldn't scale the way it does:
> > ![image](https://user-images.githubusercontent.com/55857222/102726025-94873900-431b-11eb-9871-9f370762df2a.png)
> > It should retain an aspect ratio of something like 2:3, regardless of screen size & info contained.
> 
> Is this screen shot what you want it to look like? or what it currently looks like

What it currently looks like.
The cards should all be the same size (something like 2"x3.5" - like business cards).
On the screenshot you can see that even the top cards are too wide.
