### ISSUE TITLE
Customized interface for Balancer pool

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#263]
To make interacting with the pool more accessible.

**Comment by peth-yursick** [comment]
Asked the PrimeDAO people if their frontend is open source, if yes we can just slightly modify the design & reuse.
Will report when I hear back from them.

**Comment by luxumbra** [comment]
Did you hear anything back on this @peth-yursick ?

I'd like to have a crack at the styling if we are able to use the PrimeDAO frontend.

**Comment by peth-yursick** [comment]
> 
> 
> Did you hear anything back on this @peth-yursick ?
> 
> I'd like to have a crack at the styling if we are able to use the PrimeDAO frontend.

One of their people told me he thinks its all open source, but now I've been waiting again for him to come back with a link...
I dug this up: https://github.com/PrimeDAO/prime-pool-dapp
But not sure if that's it..

**Comment by peth-yursick** [comment]
How it looks for them: 
![image](https://user-images.githubusercontent.com/55857222/106272602-9654ee00-6231-11eb-8b6a-7ed1f405250e.png)

**Comment by luxumbra** [comment]
I have just forked their repo and will have a look but anything beyond the styling is probably best left for others to do.

**Comment by luxumbra** [comment]
@peth-yursick Did I see somewhere that there was some work being done on this by @Artists?

**Comment by luxumbra** [comment]
Having looked at this, it is beyond my knowledge & skillset. Sorry.

**Comment by peth-yursick** [comment]
> 
> 
> Having looked at this, it is beyond my knowledge & skillset. Sorry.

No worries dude, thank you for trying!
Maybe take care of that Playbooks section for the wiki?
