### ISSUE TITLE
[MyMeta] Allow editing 3Box profiles on MG instead of redirecting to 3box

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/TheGame#27]
https://docs.3box.io/build/plugins/profile-edit

**Comment by hammadj** [comment]
Putting on backburner until Identity Index is ready

**Comment by peth-yursick** [comment]
Does this depend on #309?

**Comment by dysbulic** [comment]
> Does this depend on #309?

Yes. This component is specific to 3Box which will no longer be used post transition to IDX.

I do not know of any plans to develop a component like this for IDX, so if you would like profile editing on a single page, it would need to be designed.

**Comment by peth-yursick** [comment]
> I do not know of any plans to develop a component like this for IDX, so if you would like profile editing on a single page, it would need to be designed.

I think that step was actually a part of Marko's original design of the profile creation flow.
But the "single-page edit design" is still an open issue #278 right?


> 1Hive is also on 3Box and looking to migrate, so collaboration might be possible. I don't know what their frontend stack looks like.

I just added Gabi from 1Hive to the dprofiles call we're having with 3box & the rest of the bunch, he should be on the next one.

**Comment by mquellhorst** [comment]
See PR #943
