### ISSUE TITLE
Still landing on old page when navigating to metagame.wtf

### ISSUE THREAD

**Issue by plasmacorral** [MetaFam/TheGame#277]
I saw Metadreamers post that the issue was resolved
https://discord.com/channels/629411177947987986/692892074198040647/798818730103930900

However,  I am still seeing the old website after a brief flash to the new one. Using Firefox Version 84.0.2 (64-bit) on windows 10 with no shortage of plugins.  I cleared browser data and rebooted my machine and then navigate to metagame.wtf and I see the new page flash but am eventually redirected to https://wiki.metagame.wtf/

I get this glimpse: 
![image](https://user-images.githubusercontent.com/32695229/104646891-18b0b000-567f-11eb-91f6-10f04fe04674.png)

before landing back at the "old" main page:
![image](https://user-images.githubusercontent.com/32695229/104646923-2108eb00-567f-11eb-8ffc-8848bcb8fa8d.png)

Here is info from my console:
Navigated to https://metagame.wtf/ 
GEThttps://metagame.wtf/ 
GEThttps://metagame.wtf/component---src-pages-index-js-0a14339b25b939d64fe5.js[HTTP/2 200 OK 600ms] 
GEThttps://metagame.wtf/commons-0530a0f4da5128c2c370.js[HTTP/2 200 OK 1193ms] 
GEThttps://metagame.wtf/app-01bd87eff4a6cdffee30.js[HTTP/2 200 OK 5918ms] 
GEThttps://metagame.wtf/styles-5c46604c9913d2c2b163.js[HTTP/2 200 OK 1485ms] 
GEThttps://metagame.wtf/webpack-runtime-ef60df01893f257e0b21.js[HTTP/2 200 OK 1486ms] 
**GEThttps://metagame.wtf/favicon.ico[HTTP/2 404 Not Found 1934ms]** 
XHRGEThttps://metagame.wtf/page-data/app-data.json[HTTP/2 200 OK 305ms] 
XHRGEThttps://metagame.wtf/page-data/index/page-data.json[HTTP/2 200 OK 305ms] 
Navigated to https://wiki.metagame.wtf/ 
GEThttps://wiki.metagame.wtf/[HTTP/2 200 OK 2200ms] 
GEThttps://metagame.wtf/static/28e6bba46279d15b0351f46be30bb576/78d2a/icon.png[HTTP/2 200 OK 1194ms] 
GEThttps://wiki.metagame.wtf/styles.9d215d50.css[HTTP/2 200 OK 1087ms] 
GEThttps://wiki.metagame.wtf/main.336bff44.css[HTTP/2 200 OK 433ms] 
GEThttps://wiki.metagame.wtf/c4f5d8e4.7fadd380.css[HTTP/2 200 OK 496ms] 
GEThttps://wiki.metagame.wtf/img/mg-crystal.png[HTTP/2 200 OK 307ms] 
GEThttps://cdn.substack.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fe93a37b7-2a48-421c-80b7-3079eca8beb7_2048x881.png[HTTP/2 200 OK 2478ms] 
GEThttps://cdn.substack.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Ffa305be3-279a-440a-9ba2-cfa2d49281c4_952x186.png[HTTP/2 200 OK 1767ms] 
GEThttps://cdn.substack.com/image/fetch/w_1456,c_limit,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2Fbe6c92b4-6ead-4a60-acf0-db9cc0251b9c_1310x265.png[HTTP/2 200 OK 3009ms] 
GEThttps://wiki.metagame.wtf/assets/players.png[HTTP/2 200 OK 1078ms] 
GEThttps://wiki.metagame.wtf/assets/guilds.png[HTTP/2 200 OK 1731ms] 
GEThttps://wiki.metagame.wtf/assets/patrons.png[HTTP/2 200 OK 2037ms] 
GEThttps://wiki.metagame.wtf/assets/lamers.png[HTTP/2 200 OK 2038ms] 
GEThttps://wiki.metagame.wtf/styles.e481156c.js[HTTP/2 200 OK 453ms] 
GEThttps://wiki.metagame.wtf/runtime~main.acfc2a13.js[HTTP/2 200 OK 453ms] 
GEThttps://wiki.metagame.wtf/main.601e022c.js[HTTP/2 200 OK 1729ms] 
GEThttps://wiki.metagame.wtf/1.5646dfc8.js[HTTP/2 200 OK 1044ms] 
GEThttps://wiki.metagame.wtf/2.9573e78e.js[HTTP/2 200 OK 2003ms] 
GEThttps://wiki.metagame.wtf/53.3002927c.js[HTTP/2 200 OK 1043ms] 
GEThttps://wiki.metagame.wtf/c4f5d8e4.897f6d3b.js[HTTP/2 200 OK 2003ms] 
GEThttps://fonts.googleapis.com/css2?family=IBM+Plex+Mono&family=IBM+Plex+Sans:wght@400;700&family=Press+Start+2P&display=swap|[HTTP/2 200 OK 4030ms] 
GEThttps://wiki.metagame.wtf/1.5646dfc8.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/2.9573e78e.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/53.3002927c.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/c4f5d8e4.897f6d3b.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/img/mymeta-bg.jpg[HTTP/2 200 OK 1185ms] 
GEThttps://wiki.metagame.wtf/1.5646dfc8.js[HTTP/2 200 OK 0ms] 
GEThttps://fonts.gstatic.com/s/ibmplexsans/v8/zYX9KVElMYYaJe8bpLHnCwDKjWr7AIFsdA.woff2[HTTP/2 200 OK 2838ms] 
GEThttps://fonts.gstatic.com/s/ibmplexmono/v6/-F63fjptAgt5VM-kVkqdyU8n1i8q1w.woff2[HTTP/2 200 OK 3201ms] 
GEThttps://fonts.gstatic.com/s/ibmplexsans/v8/zYXgKVElMYYaJe8bpLHnCwDKhdHeFQ.woff2[HTTP/2 200 OK 3068ms] 
GEThttps://wiki.metagame.wtf/2.9573e78e.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/53.3002927c.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/c4f5d8e4.897f6d3b.js[HTTP/2 200 OK 0ms] 
GEThttps://wiki.metagame.wtf/img/mg-icon.png[HTTP/2 200 OK 882ms] 
GEThttps://wiki.metagame.wtf/img/mg-icon.png

It seems like after the 404 on https://metagame.wtf/favicon.ico I get redirected to https://wiki.metagame.wtf/

Here is the stacktrace of that 404 if that might help:
load
resource:///modules/FaviconLoader.jsm:191:20
load
resource:///modules/FaviconLoader.jsm:581:70
loadIcons
resource:///modules/FaviconLoader.jsm:657:26
onPageShow
resource:///modules/FaviconLoader.jsm:694:12
onHeadParsed
resource:///actors/LinkHandlerChild.jsm:60:24
handleEvent
resource:///actors/LinkHandlerChild.jsm:175:21

Please let me know if I can provide further information to help debug.

**Comment by hammadj** [comment]
@plasmacorral Yep that's expected. Needed to go to the old one first to purge the web worker before redirecting to the new one. Will leave it like this for another week or so for people to visit it and trigger the purge, after that can migrate it fully to the wiki
