### ISSUE TITLE
[MetaMaps] Update Hasura table structure

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#293]
In [the MetaMaps spec](https://gist.github.com/TheLoneRonin/93e1b6c01dd0977d55564492d692bdae) @TheLoneRonin lists the following desired updates to Hasura:

- [x] Reset all diffs in Hasura.
- [ ] Have maps associated with Player.id instead of an Ethereum address.
- [ ] Map data should be json instead of text.
- [ ] Migrate the Redux subsystem to `@reduxjs/toolkit`.

[Pull request #292](https://github.com/MetaFam/TheGame/pull/292) accomplishes #1.

Additionally, the permissions on the `Map` table seem overly permissive and should be reviewed.

**Comment by dysbulic** [comment]
Switching to use `Player.id` rather than `ethereum_address` requires that the current user has an entry in the `Players` table.

Currently entries in that table are generated using a multi-step form at: https://my.metagame.wtf/profile/setup.

Two options for how to handle a user that needs an account created:
- Forward the user to MyMeta and have them complete the form there
- Create a placeholder row with just an `id` and `ethereum_address` that can be completed later

I'm leaning toward the second as the additional profile information doesn't do anything for MetaMaps. A `username` is required to create a row in `Players`, so I could pop up a dialog for that.

**Comment by dysbulic** [comment]
I had a call with @IxaBrjnko and @TheLoneRonin to discuss our aspirations for MetaMaps. @IxaBrjnko has the most complex vision which is a tripartite system to (1) interface with a variety data sources, (2) allow specification of relationships between various sources, and (3) force-flow data through those networks to generate visualizations.

The existing company that comes closest to their vision is [Tableau](//tableau.com) with their [Prep](//www.tableau.com/products/prep) & [Desktop](//www.tableau.com/products/desktop) suites.

One possibility discussed for surfacing data was [Hasura's Remote Joins](https://hasura.io/blog/remote-joins-a-graphql-api-to-join-database-and-other-data-sources/). They allow viewing (and potentially updating) a datasets housed in a different data store. It is straightforward for GraphQL-based systems, or it is possible to write a de/muxing layer to expose other types of APIs.

Hasura is a server-based system, so each user wouldn't get their own datasets.

**Comment by IxaBrjnko** [comment]
3 parts of this are addressed in the current PRs to Metamaps Alpha, and the other "Map data should be json instead of text." would be easier to work on as a single issue in the main repo once we merge in those changes...

**Comment by dysbulic** [comment]
MetaMaps has been removed from active development.
