### ISSUE TITLE
[MetaMaps] Only authenticate when necessary

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#295]
Currently if a user has not connected their $ETH wallet they are not able to do anything other than look at a message asking them to authenticate.

The application should only ask the user to log in when they are performing an interaction, such as saving a map, that needs to be tied to their account.

If they are not logged in when they start, a new ephemeral map should instantiated that they can edit anonymously.

There should also be a `Connect` button in the same place as on [my.metagame.wtf](//my.metagame.wtf). Ideally the component from `packages/web/components/LoginButton.tsx` should be abstracted to `packages/design-system` and then included in MetaMaps via the import of `@metafam/ds`.

**Comment by ace-smart** [comment]
I would like to work on this issue?

**Comment by ace-smart** [comment]
@dysbulic @TheLoneRonin In the MetaMaps, the `Setup Profile` link is needed still?
I think `Setup Profile` feature should be available on only `MyMeta`.
What do you think about this?
![image](https://user-images.githubusercontent.com/76216456/106624306-f4196b00-658e-11eb-878e-8f1ca3382825.png)

**Comment by dysbulic** [comment]
> [Is] the `Setup Profile` link is needed still?

I think we need the ability to insert content by the profile icon. I [suggested an 'options` parameter](https://github.com/MetaFam/TheGame/pull/328/files/0a9ac1532c5ef95dc37ea806d0d6b7e6d5ffbdd6#r568305756) in #328.

**Comment by IxaBrjnko** [comment]
If we can pull the merge from MetaMaps Alpha, this would be a lot easier to work on in the main repo...

**Comment by dysbulic** [comment]
MetaMaps has been removed from active development.
