### ISSUE TITLE
[MetaMaps] Update the UI to be consistent with other MetaGame sites

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#297]
From [@TheLoneRonin's spec](https://gist.github.com/TheLoneRonin/93e1b6c01dd0977d55564492d692bdae#updating-component-libraries):

- [ ] Update and migrate components to @metafam/ds.
- [ ] Copy theme elements from other MetaGame's designs. Can use Figma as a reference: https://www.figma.com/file/RWVfMGvXDAX74fQexze8uO/Meta-Game-Copy-Copy?node-id=58%3A2
- [ ] Improve overall code structure to jsx/tsx.

**Comment by IxaBrjnko** [comment]
So, one goal might be to construct the My.Meta UI out of the MetaMaps... We would want a way to format the box containing the My.Meta profile so that it contained the schema elements currently displayed in the player cards loading in <PageContainer>...

**Comment by IxaBrjnko** [comment]
I also think I saw that @dysbulic had already made some of these changes in PRs to the MetaMaps Alpha...

**Comment by dysbulic** [comment]
MetaMaps has been removed from active development.
