### ISSUE TITLE
Integrate Ceramic Network 

### ISSUE THREAD

**Issue by META-DREAMER** [MetaFam/TheGame#309]
Create a "hello world" integration of Ceramic / IDX into our repo (e.g. adding 3ID connect to login flow and setting / getting a field from the user profile)

https://twitter.com/ceramicnetwork/status/1354448316512284675?s=20

**Comment by dysbulic** [comment]
For reference, there is [a profile record](https://developers.idx.xyz/guides/definitions/default/#basic-profile) associated with an IDX, but it is currently empty. So, the first time a user logs in with IDX, maybe the system should copy their 3Box profile into IDX?

You can experiment in the [web playground](https://ceramicstudio.github.io/web-playground/) which instantiates the `ceramic`, `idx`, & `did` objects for manipulation using the development console.

Setting and retrieving the profile looks like:

- `await idx.set('basicProfile', { name: 'Δυς' })`
- `await idx.get('basicProfile', did.id)`

**Comment by dysbulic** [comment]
I checked with [3Box support](https://discord.gg/pYXBnKkt) and [3ID-Connect](https://github.com/ceramicstudio/3id-connect) will eventually handle migrating the user profile the first time a user uses IDX "closer to the mainnet release".

**Comment by dysbulic** [comment]
The system which verifies accounts (Discord, Github, Twitter) and associates them with an IDX DID is [identitylink-services](https://github.com/ceramicstudio/identitylink-services). It is possible to run the services ourselves, but there will be a hosted version that is released closer to mainnet.

To support out current coverage, there would also need to be support for Discourse as well.

Github verification requires creating a Gist; Twitter tweeting. To verify on Discourse, a user could have to post a reply with their DID to a special thread dedicated to these verifications. It looks like there's [an API for reading posts in a particular topic](https://docs.discourse.org/#tag/Topics/paths/~1t~1{id}~1posts.json/get).

**Comment by dysbulic** [comment]
I [forked identitylink-services](https://github.com/MetaFam/identitylink-services) to the MetaFam repo to look into adding Discourse support while still garnering my precious XP.

**Comment by dysbulic** [comment]
Another aspect of the IDX integration is using it as the basis for determining a Player's accounts for XP distribution.

I'm working on [IDX as a SourceCred source of truth](https://github.com/sourcecred/sourcecred/issues/2718) for ETHDenver.

**Comment by dysbulic** [comment]
The ETHDenver work is complete. I [summarized the outstanding issues](https://github.com/sourcecred/sourcecred/issues/2718#issuecomment-778125602) on SourceCred's Github. I'll copy that here for ease of access:

> The current state of the [work to use IDX to generate SourceCred aliases](//github.com/dysbulic/idx-sourcecred-bridge/blob/main/index.js) has been submitted to ETHDenver.
> 
> The development of IDX is not quite to the point that it is fully possible to complete this work.
> 
> * In Ceramic, the `aka` default document type alias for holding social account links doesn't exist yet. (`basicProfile` & `cryptoAccounts` are all that's defined.)
> * There will be a hosted version of the IdentityLink system.
> * There will be a UI for completing account verifications and a profile.
> 
> Additionally there are a few known issues with the current system:
> 
> * The attestation for the Verifiable Credential for an account link is not verified.
> * If the verification process fails repeatedly, you can get an Invalid Challenge Token message. I assume from Redis returning a stale entry.
> * The aliases are not serialized back out. [Support was added this morning](#2747), but time didn't permit.
> * Discourse is [not a linkable account type](https://github.com/ceramicstudio/identitylink-services/issues/10).

Until the IDX support for linked accounts is a little better, I'm going to move this back to the Icebox.

**Comment by oed** [comment]
Thanks for the rundown @dysbulic!

> In Ceramic, the aka default document type alias for holding social account links doesn't exist yet. (basicProfile & cryptoAccounts are all that's defined.)

This will be fixed within the next week or so.

> There will be a hosted version of the IdentityLink system.

We will have this up and running within the next week as well (at least for twitter + github)

> The attestation for the Verifiable Credential for an account link is not verified.

What do you mean by this? Not sure I follow.

> If the verification process fails repeatedly, you can get an Invalid Challenge Token message. I assume from Redis returning a stale entry.

Interesting point. We will look into this. Tracking here: https://github.com/ceramicstudio/identitylink-services/issues/15

**Comment by dysbulic** [comment]
> > The attestation for the Verifiable Credential for an account link is not verified.
> 
> What do you mean by this? Not sure I follow.

This is a limitation of the software I wrote. I'm not calling `verifyJWS` and checking the attestation author. I'm just creating aliases for any account links that exist, and that's not secure.

**Comment by oed** [comment]
Ok @dysbulic is there any limitation on the ceramic here, or is it just that you haven't implemented it in your system? Just want to understand if there is something we should fix :)

**Comment by dysbulic** [comment]
> [I]s there any limitation on the ceramic here, or is it just that you haven't implemented it in your system?

Ceramic is good to go so far as providing authentication for an attestation. I just didn't get to the point of adding the checks to what I was working on.

**Comment by dysbulic** [comment]
We're on the waitlist for [the rollout of Ceramic's main net](https://blog.ceramic.network/ceramic-mainnet-early-launch-program/). The wait of the list is 4‒6 weeks.

**Comment by dysbulic** [comment]
I got a message that we're in the first cohort to be onboarded for the mainnet launch.

Their desire is that we be able to go to production at the end of April.

**Comment by dysbulic** [comment]
This is getting revived as an attempt to address the timeout issues for which #551 was investigating migrating to Hasura Cloud.

When running a query for the 3Box profiles in the GraphQL explorer in the Hasura Console, it will intermittently timeout.

So, the plan is to cache the 3Box & IDX information in Hasura and periodically check for updates. Also, a mechanism to trigger a refresh would likely be useful.

**Comment by dysbulic** [comment]
> Is this done? It is not clear.

This particular ticket is done. The current work replacing the IDX integration with Glaze is captured in #769.
