### ISSUE TITLE
[MyMeta] Change the enneagram selection screen to the new color selection screen

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#312]
Just hastily opening before it slips my mind 😁
Please DM or comment here when you want more details 🙃

**Comment by staked-smart-ace** [comment]
@peth-yursick Could I work on this issue?
I am looking for more details :)

**Comment by ace-smart** [comment]
@peth-yursick this is @super-senior from Discord :)
Could I work on this issue?

**Comment by dysbulic** [comment]
Where are the designs for the color selection UI?

**Comment by dysbulic** [comment]
The [winning entry](https://discord.com/channels/629411177947987986/779498127135735878/811331426015379457) for the updated personality profile is:

![Screenshot from 2021-02-18 18-26-34](https://user-images.githubusercontent.com/181523/108435168-e6aee280-7216-11eb-94c2-900c80bf3202.png)

I've tried [a few different five-color assignment tests](https://dhappy.org/.../MetaGame/five-color%20alignment%20tests/). They all come back with scores on all the axes. I guess that's what's captured by the divided bar chart below the type names.

Rather than the divided bar chart, I'd like to do a radar chart which I think would make it easier to score each axis without worrying about percentages. This could be normalized to a bar or pie chart for ease of display.

¿Do we want to integrate the personality test into the site to save Players having to copy over their results? [One of the tests](https://github.com/Jerdle-code/color-pie-test) is BSD-licensed and looks relatively straightforward to implement.

The designs with the icons are still needed.

**Comment by alexkyen** [comment]
hey @dysbulic, is the next step here to locate the figma?

**Comment by dysbulic** [comment]
> is the next step here to locate the figma?

Yeah. I've got the call out & it should be located shortly. Why it's not in my history I don't understand…

**Comment by peth-yursick** [comment]
> 
> 
> hey @dysbulic, is the next step here to locate the figma?

There isn't a figma for this afaik, it was made in illustrator.
But the illustrator file can probably be imported in figma?

**Comment by dysbulic** [comment]
@alexkyen, that was why I couldn't find the Figma, it was an [Illustrator file](https://discord.com/channels/629411177947987986/782054676546846752/812437464663851048).

**Comment by dysbulic** [comment]
This task is completed by #384. Unfortunately the test servers only deploy the frontend, and this adds a table for colors and removes the Enneagram table.

I am working to bring up a test system so the pull request can be properly reviewed.

**Comment by dysbulic** [comment]
There is a test server partially up. You can view the input page at: http://31.220.51.54:3000/profile/setup/playerType

**Comment by dysbulic** [comment]
There is [a legal issue with the distribution](https://company.wizards.com/en/legal/fancontentpolicy) of the Magic iconography. For one, parts of MetaGame aren't free, and for two, the iconography for the guilds of Ravnica are explicitly protected from use.

I have been considering my choices for what part of the mythos is chosen to represent a particular combination of colors. Specifically, I think the pure colors are too generic, and I think the shards are too amorphous. I would like to maybe use Gods to fill out those portions of the archetypal structure.

So, there are 32 possible combinations of five things chosen without repetition. From the [Gods listing](https://gatherer.wizards.com/Pages/Search/Default.aspx?output=compact&sort=mana-%7ccolor-&action=advanced&subtype=+%5b%22God%22%5d), here are the colors associated with various deities:

* `W----`: (White):
  * [Reidane, Goddess of the Worthy](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503626)
  * [Halvar, God of Battle](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503619)
  * [Heliod, God of the Sun](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479497)
* `-U---`: (Blue):
  * [Alrund, God of the Cosmos](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503646)
  * [Cosima, God of the Voyage](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503657)
  * [Thassa, God of the Sea](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479500)
* `--B--`: (Black):
  * [Egon, God of Death](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503700)
  * [Valki, God of Lies](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503724)
  * [Tergrid, God of Fright](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503721)
  * [Erebos, God of the Dead](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479503)
* `---R-`: (Red):
  * [Birgi, God of Storytelling](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503734)
  * [Toralf, God of Fury](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503766)
  * [Purphoros, God of the Forge](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479506)
* `----G`: (Green):
  * [Esika, God of the World Tree](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503781)
  * [Jorn, God of Winter](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503793)
  * [Kolvori, God of Kinship](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503796)
  * [Nylea, God of the Hunt](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479509)
* `WU---`: [Ephara, Goddess of the Polis](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479501)
* `W-B--`: [Athreos, God of Passage](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479505)
* `W--R-`: [Iroas, God of Victory](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479499)
* `W---G`: [Karametra, Goddess of Harvests](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503325)
* `-UB--`: [Phenax, God of Deception](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479504)
* `-U-R-`: [Keranos, God of Storms](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479508)
* `-U--G`: [Kruphix, God of Horizons](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479502)
* `--BR-`: [Mogis, God of Slaughter](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479507)
* `--B-G`: [Pharika, Goddess of Affliction](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=479511)
* `---RG`: [Klothys, Goddess of Destiny](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=476471)
* `---RG`: [Xenagos, God of Revels](https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=503344)

The set of Gods overlaps with the set of ten [guilds of Ravnica](https://mtg.fandom.com/wiki/Ravnica#Guilds):

There are five which are "allied colored" meaning that the two colors representing the guild are cooperative:

* `WU---`: The Azorius Senate is the police force, legislative and judicial body of Ravnican bureaucracy.
* `-UB--`: House Dimir was recently thought extinct, and provides illegal but necessary services, while openly serving as couriers, investigators, reporters, and archivists.
* `--BR-`: The Cult of Rakdos, considered a necessary evil by some, is composed of thrill-killers who provide the heavy labor force, catering, and entertainment of the plane.
* `---RG`: The Gruul Clans have fallen from their former glory as the keepers of Ravnica's wilds and now are nothing but a loose affiliation of berserker clans who seek to wipe civilization from the plane.
* `W---G`: The Selesnya Conclave promotes what is now the strongest, nature-based religion of Ravnica and its ledev guards patrol the rural areas along with being conservationists and charity workers.

The other five are "enemy colored" meaning the two colors representing the guild are in conflict:

* `W-B--`: The Orzhov Syndicate was originally the most widespread religion of Ravnica. Now it regulates trade and banking, among other activities such as law.
* `-U-R-`: The Izzet League is responsible for the world-city's civil engineering works and new magical developments.
* `--B-G`: The Golgari Swarm manages food production and organic waste disposal.
* `W--R-`: The Boros Legion is a standing army that protects the Guildpact and contains the League of Wojek, the official peacekeepers of the City of Ravnica.
* `-U--G`: The Simic Combine provides medical assistance and performs biological research.

Similarly, the three-color combinations exist in allied and enemy forms. The allied forms are the Shards of Alara which represent environments:

* `WU--G`: The Bant Shard: A shard of rolling hills, forests and glittering beaches. The landscape is dotted with beautiful high-rising castles.
* `WUB--`: The Esper Shard: The sophisticated beauty of this shard is etched into every artifact, city, and even the faces of some of the inhabitants.
* `-UBR-`: The Grixis Shard: The inhabitants of this hellish shard are either buying power at a high price or spiraling out of sanity and into despair.
* `--BRG`: The Jund Shard: Goblins, lizardmen, and humans scour this shard for food and power, but all here are ruled by fearsome dragons.
* `W--RG`: The Naya Shard: The lush growth and rich natural beauty of this shard sometimes masks the savage dangers of the jungle.

The enemy colored combinations (a color and its two enemies) are represented by the Clans of Tarkir:

* `W-B-G`: The Abzan Houses: Worshiped Aspect: Scale of the dragon (Endurance)
* `WU-R-`: The Jeskai Way: Worshiped Aspect: Eye of the dragon (Cunning)
* `-UB-G`: The Sultai Brood: Worshiped Aspect: Fang of the dragon (Ruthlessness)
* `W-BR-`: The Mardu Horde: Worshiped Aspect: Wing of the dragon (Speed)
* `-U-RG`: The Temur Frontier: Worshiped Aspect: Claw of the dragon (Savagery)

The four-color sets don't have aspects in the mythos, instead they are simple adjectives:

* `WUBR-`: Artifice
* `-UBRG`: Chaos
* `W-BRG`: Aggression
* `WU-RG`: Altruism
* `WUB-G`: Growth

An alternative for the pure colors are the types of spellcasters for each color:

* `W----`: Cleric
* `-U---`: Wizard
* `--B--`: Warlock
* `---R-`: Shaman
* `----G`: Druid

Also there's the iconic creature type for each pure color:

* `W----`: Angel
* `-U---`: Sphinx
* `--B--`: Demon
* `---R-`: Dragon
* `----G`: Hydra

The presence of all five colors is simply represented as "WUBRG".

The program currently uses pure colors, guilds of Ravnica, shards of Alara, clans of Tarkir, a Colorless type, & WUBRG. Having a shorthand for a type is useful, but without the iconography it is significantly less effective.
