### ISSUE TITLE
[MyMeta] - Fix card aspect ratio

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#326]
Right now cards all get stretched horizontally on bigger screens:
![image](https://user-images.githubusercontent.com/55857222/106524843-66cd0c80-64e3-11eb-810c-beef74bd7368.png)
They should stay taller consistently, like player cards:
![image](https://user-images.githubusercontent.com/55857222/106524895-79dfdc80-64e3-11eb-9ec2-ecaf4c1b8d15.png)

**Comment by ace-smart** [comment]
Could I fix this issue?

**Comment by peth-yursick** [comment]
> 
> 
> Could I fix this issue?

Yes sir!
