### ISSUE TITLE
[MyMeta] Allow a Player to store their pronouns as part of their profile

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#331]
I would leave this until after the migration to IDX (#309), but I think it would be useful for Players to be able to save their preferred pronouns to their profile.

Operating in a space where neither sex nor gender is visually expressed, it's a question that comes up.

**Comment by jaburx** [comment]
I'm doing this

**Comment by dysbulic** [comment]
@jaburx [pretty much did this](https://github.com/MetaFam/TheGame/pull/711), but abandoned the code when changes were requested.

The storage of profile fields is [moving to IDX](https://github.com/MetaFam/TheGame/issues/309), so adding it to Hasura is probably not warranted at this point.
