### ISSUE TITLE
[MetaOS] - Build The Dashboard

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#337]
MetaGame needs a dashboard!
With the creation of the new metamenu, it became obvious metagame needs a "home" page as well.
Not the landing page - though that is needed as well...
The home page aka the dashboard where people can see:
- Their Seeds & XP stats as well as other MetaGame stats
- Latest posts, podcasts & videos
- Upcoming events
- The leaderboard
- ???

[The design](https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/Mega-Menu?node-id=86%3A107)
The actual layout doesn't matter & will be updated.
Mainly what matters for now is the backend for this stuff to work.
Like plugging in google calendar, a way for pulling in the latest content, embedding the leaderboard, measuring "morale" etc.
Some of these things are relatively simple in how they should work, some will require a bunch of discussion.

Eventually, the thing should be modular so people should be able to customize, move the modules around & embed other dapps or things they want easily accessible through their dashboards.

Want to work on it?
Comment here, feel free to ask anything.

**Comment by davort** [comment]
Hi, I am the designer behind these mockups. Feel free to ping me about anything regarding the Dashboard. Looking forward to talking and working with you!

**Comment by vidvidvid** [comment]
After I'm done with the user profile / edit update, I would like to work on this.
