### ISSUE TITLE
[MyMeta] Error reconnecting with Metamask after an initial connection with WalletConnect

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#338]
> [Davor]: [I'm] connecting with MetaMask and this screen pops up whenever I load a new page on my.metagame.wtf
> 
> <img src='https://user-images.githubusercontent.com/181523/107406922-0176ae00-6ad7-11eb-9b3d-4f5828f67f6a.jpg' width='150px'/>
> 
> But can't seem to get past it. … I hit the "Sign" button, but then nothing happened after that ☹
> 
> [The error console when I attempt to sign is:]
>
> ![Screenshot_20210209](https://user-images.githubusercontent.com/181523/107407248-72b66100-6ad7-11eb-98b3-ad17506ee784.png)
>
> I remembered that the first time I tried this, I used the Argent app, FWIW. But even then, I didn't get any feedback from the website whatsoever

It looks to me like Web3Modal has cached WalletConnect and is attempting to use it. Why the Metamask dialog is coming up, I don't know.

Adding `modal.clearCachedProvider()` to the `Disconnect` action should be done.

This doesn't fix Davor's issue since he can't connect.

**Comment by dysbulic** [comment]
After a little testing, when a page loads with Metamask connected, `window.ethereum.isConnected()` is `true`. `modal.cachedProvider` is `injected`. 

Ideally, we would check if the provider is connected on load and show the profile information if so.

I did a quick test of logging in with Wallet Connect on my.metamaps.wtf, and it shows my Metamask profile rather than an empty one, so more than likely something is using `window.ethereum` rather than the `provider` returned by Web3Modal.

**Comment by dysbulic** [comment]
Ok, so it seems as though if `modal.cachedProvider` is `injected` then the call to `web3Modal.connect()` won't prompt the user, but will just return. The way I handled it in an app I'm working on:

```javascript
const disconnect = async () => {
  setAddress()
  web3Modal.clearCachedProvider()
  if(web3?.currentProvider?.disconnect) {
    await web3.currentProvider.disconnect()
  }
}

const connect = async () => {
  try {
    const provider = await web3Modal.connect()
    const web3 = new Web3(provider)
    ⋮
  } catch(err) {
    disconnect()
  }
}

const enableIfInjected = async () => {
  if(web3Modal.cachedProvider === 'injected') {
    await connect()
  }
}

useEffect(() => enableIfInjected(), [])

return <Button onClick={connect}>Connect Your Wallet</Button>
```

**Comment by pakokrew** [comment]
I walked around a lot of different issues while managing web3 wallet in my app Mooni, and that's the top of the iceberg. 
There's a lot of bugs in the libraries (web3modal, walletconnect, ethersjs etc) and more in the implementation of the provider in every wallet. 

The issue you mention is specifically when users use the app on a mobile web browser and login with a mobile app via walletconnect. The cache issue does not come from web3modal but from walletconnect which stores which wallet it is connected to and does not allow to clear that. The only workaround I found is to manually delete a key in the localstorage.

I will try to put the work I've done in Mooni in this repo to handle as much wallet as possible. 

You can check some code there http://github.com/pakokrew/mooni/
