### ISSUE TITLE
[Bot] Automate role assignments using discord bot

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#341]
- setup trigger in Hasura on the role field in the Player table so that whenever it changes a function is called that uses the discord bot client to update that Players role in discord (diamond, platinum, etc)

**Comment by alalonde** [comment]
[Started working](https://github.com/MetaFam/TheGame/tree/feature/auto-update-discord-roles) on this today. I created the hasura trigger, however, we will need to at least partially implement #184 as we need a mapping between our ranks and a discord Role ID. I'll jump over to that one then. Probably quite a bit of refactoring involved there.
