### ISSUE TITLE
When user is logged in change Setup profile to Edit profile

### ISSUE THREAD

**Issue by markoprljic** [MetaFam/TheGame#344]
Change Setup profile to Edit profile, if user is logged in and has already set up their profile.

<img width="320" alt="Image 2021-02-12 at 5 15 49 pm" src="https://user-images.githubusercontent.com/5704285/107793026-22990200-6d56-11eb-8889-3767fe6557e8.png">

**Comment by alalonde** [comment]
Yup, I did just this in #333

**Comment by dan13ram** [comment]
Closing this as we no longer use text for setup/edit profile.
