### ISSUE TITLE
[MyMeta] Use text links for the profile setup and disconnect actions

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#357]
Once a Player connects their wallet, there are links next to their profile picture allowing them to configure their profile or disconnect. These links were switched to icons to save space, but the look is visually unappealing.

Switch back to the text links, and only go to icons when the screen is narrow enough that the profile picture is pushed behind the app drawer (~1100px–`lg` breakpoint).

![Screenshot from 2021-02-12 23-09-36](https://user-images.githubusercontent.com/181523/108458592-fd6b2e80-7242-11eb-9fc6-539b3bdf7420.png)

**Comment by luxumbra** [comment]
I'll pick this up if it's available and still on the roadmap.
