### ISSUE TITLE
[Quests] Use pSEED subgraph for creating quests

### ISSUE THREAD

**Issue by pakokrew** [MetaFam/TheGame#381]
The backend handler for creating quests is currently reading on-chain for getting pSEED balances.

We should replace this and use the sub-graph from @dan13ram 

Note: We have since moved on to using polygon pSeeds, DO NOT base this on mainnet pSeeds.

**Comment by dan13ram** [comment]
`packages/backend/src/handlers/actions/quests/createQuest/permissions.ts`

**Comment by dan13ram** [comment]
Added a new issue for Polygon pSEED https://github.com/MetaFam/TheGame/issues/1021

**Comment by peth-yursick** [comment]
You mentioned changing the amount needed for creating quests in the recent PR @dysbulic 
Was this also changed?

**Comment by dysbulic** [comment]
I am pretty sure we did this. The pSEED value in Hasura is coming from Polygon.
