### ISSUE TITLE
[MyMeta] Allow profile images with transparency

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#385]
The current code for loading profile images puts a solid color behind the image:

<img src='https://user-images.githubusercontent.com/181523/110163807-8dba7f00-7dbe-11eb-9668-5bf63132bd45.png' width='275'/>

This is useful for the autogenerated images:

![Screenshot from 2021-03-05 14-26-55](https://user-images.githubusercontent.com/181523/110164085-e12ccd00-7dbe-11eb-8717-15bfc20724b3.png)

But unnecessarily limits the creativity of users that have chosen an image.

The background behind the profile image of a user who has specified one via 3Box should be transparent.

**Comment by tobi110289** [comment]
Did a version that works: https://github.com/MetaFam/TheGame/pull/409

**Comment by luxumbra** [comment]
Seems this has gone stale due to unfortunate issues with timing and the old PR/Review workflow. @tobi110289, honestly, things have improved greatly with regards to workflow in recent weeks. We'd love to get more contributions from you. Did you ever join the MetaGame Discord?

**Comment by chair28980** [comment]
I am mere inches from merging this to develop, @dysbulic showed me the way today and I crossed up some origin/fork branches and ended up blowing the whole thing up. This should be merged tomorrow.

**Comment by mquellhorst** [comment]
Moved to Done but seems to reopen after move
