### ISSUE TITLE
Set up a testing environment for the backend

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#389]
I have a pull request, #384, that is blocked b/c no one can test it b/c it makes changes to Hasura's structure and there's no testing environment for Hasura.

There should be some workflow for testing changes that alter the backend structure.

**Comment by dysbulic** [comment]
I tried setting up a test server using Hasura Cloud. Unfortunately, it is running v2.0.0-alpha and we are currently using 1.3.3.

I am not able to run `hasura metadata apply` b/c the configuration is v2 and it demads v3. I found a way to update the configuration, but it overwrites the metadata.

In general, I have not been able to find a way to migrate from v1 Hasura to v2.

**Comment by dysbulic** [comment]
I have been trying to bring up a VPS to just demonstrate the profile editing page for the moment.

The problem has been with Linux's out-of-memory process killer. For whatever reason it is beneficial to overestimate the amount of available memory and over-allocate.

This means that sometimes a process will run out of memory, at which time it is killed.

I started with a VPS with 1GiB of memory and it was unable to complete the installation process without getting killed. I switched to a 2 GiB machine, and it could complete the build, but dies when serving pages.

I can build a static version of the site which lets you interact with the personality chooser, but the profile pages with the colored disposition on them isn't generating yet.

**Comment by alalonde** [comment]
Can you specify a hasura version to run in Hasura Cloud? I would be surprised if they forced you to use an alpha version.

**Comment by dysbulic** [comment]
> Can you specify a hasura version to run in Hasura Cloud? I would be surprised if they forced you to use an alpha version.

I was too, but I've looked to the best of my ability and asked in Discord to no avail. I think part of it is that they're young enough in their cloud offering that v2 is all they want to support.

Maybe an automated migration of metadata will come later…

**Comment by dysbulic** [comment]
I'm looking at different continuous deployment options. One of the prettiest (and seemingly most versatile) is [codefresh](http://codefresh.io). This is what I prepared to send to them, but I'm not 100% sure it's correct:

> Currently all code is managed through Github. When a pull request is created Vercel creates a test version of the frontend (generated by Next.js) and makes it available at a host on the internet.
> 
> The backend has no testing environemnt. It is an Express server backed by Hasura. All the servers along with a Postgres database are deployed via Docker to OnRender.com.
> 
> I'm trying to understand how codefresh fits in to that pipeline. Will it serve test versions of the site? Would it allow testing the backend?

@hammadj, where is the Postgres instance backing Hasura located? Is everything on OnRender deployed using Docker?

**Comment by alalonde** [comment]
We have two services and the DB hosted at render.com (https://render.com/pricing#)

All three on the starter plan, $21 / month total. Easiest solution would be to spin up adjacent services and DB in the same team, but that obviously doubles the cost. 

Slightly off-topic, but it seems like we should move toward somehow reimbursing folks for these sorts of outlays. For hammad, for instance, we could maybe bundle in reimbursement for the various dev services' costs after a round of SEED minting at the time of reimbursing his account the gas fees.

**Comment by alalonde** [comment]
Working on leveraging github actions to just stand up a postgres / hasura instance at build-time.
