### ISSUE TITLE
[MetaOS] Completing Patrons

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#445]
- Add the "league rankings" (diamond, platinum, gold, etc.) to the patron pages, like on the [players leaderboard](https://my.metagame.wtf/)
- Make the patron "player cards" include skills & be the same height as the player cards on the [players leaderboard](https://my.metagame.wtf/)
- Add the link to https://my.metagame.wtf/patrons to the app launcher

**Comment by alalonde** [comment]
Not to mention a link to that page!

**Comment by peth-yursick** [comment]
> 
> 
> Not to mention a link to that page!

Oh damn, right!
I asked Lux to add it to the wiki app launcher, but forgot about the main one 😱

**Comment by dan13ram** [comment]
@peth-yursick do we have the logo for this?

**Comment by peth-yursick** [comment]
Not really closed. There are league rankings now but it seems like its only displaying their player ranking rather than patron ranking. Patron ranking should be based on pSeeds rather than XP, just on the same 7, 7, 7, 14, 21 scheme

**Comment by dan13ram** [comment]
> Not really closed. There are league rankings now but it seems like its only displaying their player ranking rather than patron ranking. Patron ranking should be based on pSeeds rather than XP, just on the same 7, 7, 7, 14, 21 scheme

Ah. Cool

**Comment by alalonde** [comment]
Yeah, makes sense. Let's just compute this in React rather than storing it in the DB as there's really no concept of "patron rank" outside of this board.

**Comment by dan13ram** [comment]
Yes @alalonde, I had the same thoughts. Will raise a PR with these changes by tomorrow
