### ISSUE TITLE
Setup Auth with Web3Modal on NextJS app

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#46]
https://www.figma.com/file/zDHqledo5H2aKR3KDvbur8/Meta-Game?node-id=1713%3A32

Here's the login screen. The design isn't up to date, but the two options we want here for signing in are web3Modal (metamask, walletconnect, etc) and https://magic.link with email for anyone that doesn't have an existing ETH account. For the scope of this issue, we will implement web3modal first. 

You can see how the existing implementation works in the app-react package for inspiration, and can probably re-use code from there for web3 provider and what not.

**Comment by brymut** [comment]
Will work on setting this up

**Comment by youngkidwarrior** [comment]
@hammadj I can work on this and have it done by the end of the week.

**Comment by dan13ram** [comment]
@youngkidwarrior please go ahead, I've not been able to get to this yet.

**Comment by krzysu** [comment]
it was done in this commit https://github.com/MetaFam/TheGame/commit/2e4c3a6c6589bff030a472d2684a928b736435ef
