### ISSUE TITLE
typecheck of github push differs from local commit

### ISSUE THREAD

**Issue by mquellhorst** [MetaFam/TheGame#461]
When I commit the pre-hook runs typecheck and succeeds. 
However, when I push the commit to github a different typecheck seems to run which throws errors (so this one is more strict)

Could we use the same (the strict one) for commits?

**Comment by dan13ram** [comment]
@mquellhorst 

pre-commit hook runs `yarn lint-staged` which runs `eslint` and `prettier` only for staged files.
pre-push hook runs `yarn typecheck`

and there is no difference between the local typecheck and workflows typecheck commands as can be seen (here)[https://github.com/MetaFam/TheGame/blob/master/.github/workflows/PR-CI.yml#L37] and (here)[https://github.com/MetaFam/TheGame/blob/efe0e8bde3d070eaf373187e78513f4c41f3f659/package.json#L30] 

Please reopen if the issue persists for you. :)
