### ISSUE TITLE
Set up staging environment

### ISSUE THREAD

**Issue by geleeroyale** [MetaFam/TheGame#471]
We need a staging environment to move more quickly with PRs

**Comment by alalonde** [comment]
@geleeroyale you should have access to do this now

**Comment by alalonde** [comment]
Also, update the render.yml file, look into if we can maintain separate versions for development vs master branches?

**Comment by alalonde** [comment]
Staging database, hasura / backend instances have been stood up. Also copied all prod data to staging.

Just need @hammadj's help getting an associated vercel frontend staging instance and this should be GTG.
