### ISSUE TITLE
Fix intermittent build failures in Github Actions

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#482]
I made a change to our build a few weeks ago to stand up a docker container with our backend code for the web build to point to.  This seems to be failing now.  This may not be a best practice but it needs some investigation to see what's going on.

**Comment by dan13ram** [comment]
@alalonde 
Builds are still failing.. actually its just stuck at `yarn wait-on` for 
https://github.com/MetaFam/TheGame/pull/515
But it passed another PR https://github.com/MetaFam/TheGame/pull/529

**Comment by alalonde** [comment]
Does `/healthz` even exist on hasura? May need to use a different health check endpoint.

**Comment by dan13ram** [comment]
@alalonde It does exist. https://hasura.io/docs/latest/graphql/core/api-reference/health.html
This code works locally for me as well as has worked for other PRs (ref #529 and #548)

I just don't why it works sometimes and then fails at other times!

**Comment by alalonde** [comment]
Yeah, #515 error is due to a separate issue I believe. I think we're good here.
