### ISSUE TITLE
[Quests] Add formatting to the Quests

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#487]
We have the quests now but its not possible to format their descriptions, not even put things in a new row 
![image.png](https://images.zenhubusercontent.com/6012e742cf90c0930a4aa829/abd006b5-8531-4ecb-a56f-41455eb295d6)
We need to be able to format the text in the description.
Integrate the [Quill component](https://github.com/zenoamaro/react-quill) to allow for quest formatting.

**Comment by luxumbra** [comment]
I'd like to take this if no-one else is on it. @alalonde

**Comment by peth-yursick** [comment]
> 
> 
> I'd like to take this if no-one else is on it. @alalonde

We've been enforcing "assign it to yourself if you're working on it", and this one was only added yesterday anyway, so I don't think anybody is working on it yet

**Comment by luxumbra** [comment]
Happy days. I am just updating my local repo

**Comment by mquellhorst** [comment]
@luxumbra are you still working on this else I'ld like to pick it up?

**Comment by luxumbra** [comment]
@mquellhorst I have been off for a few days and was going to go at it this week but am aware it's been with me for nearly 3 weeks and hasn't gone anywhere, so go ahead.

**Comment by peth-yursick** [comment]
What's the status on this @mquellhorst?
The last thing I remember was "its done but I need to test it" & that was months ago..
And once its completed, will it be completed for Playbooks as well?
Or if someone makes it for Playbooks, does that close this issue?

**Comment by alalonde** [comment]
There is a PR that was abandoned

**Comment by luxumbra** [comment]
> There is a PR that was abandoned

@Udit-takkar if you're going to take a look at #760, this will be relevant for you. 😄

**Comment by Udit-takkar** [comment]
Ok thanks
