### ISSUE TITLE
[MyMeta] Add Internal Guilds to the guilds page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#489]
On the https://my.metagame.wtf/guilds page, there should also be internal guild pages.
The guild profiles should feature information from [this page ](https://www.figma.com/file/l9qXlzJFaNGvWTdxgJCPjf/MetaGame-Onepagers?node-id=0%3A1)
One of the containers should be like this:
Title: How to join
Body: Do one of these things (list evergreen quests from the above figma in bullet points), then get on discord & contact Head Innkeeper of that specific guild (names will be provided when you choose to tackle this issue.
The guild logos should also be ready by then, if not - ask in the #tavern or #artists-guild.

Dependant on #460

**Comment by alalonde** [comment]
These are essentially Metafam guilds, right? I would highly recommend renaming internal guilds (or external guilds) so that they're both not called "guilds"...

**Comment by mquellhorst** [comment]
So far there aren't any external guilds right?
I'm wondering whether there will be external guilds, I suggest we discuss this during the builder meet

**Comment by peth-yursick** [comment]
No, so far they are all external guilds.
The internal guilds will be "builders guild", "designers guild" etc. they will be added when we have pages for current (external) guilds.

**Comment by mquellhorst** [comment]
Ah I see. 
I agree with Alec on renaming external guilds.
I'ld say guilds contribute to MetaGame and you earn seeds
External guilds are more like alliences

**Comment by peth-yursick** [comment]
> Ah I see.
> I agree with Alec on renaming external guilds.
> I'ld say guilds contribute to MetaGame and you earn seeds
> External guilds are more like alliences

They won't both be called guilds. There will be "Guilds" & "Internal Guilds" with the internal guilds scrolled sideways or something pinned on top of the guilds page so they're more obviously separate.
Alliances are a third thing which already exists (though not in prod yet): groups of guilds (eg. Bloom Network & MetaCartel)
