### ISSUE TITLE
[Roadmap] Products

### ISSUE THREAD

**Issue by geleeroyale** [MetaFam/TheGame#507]
- [ ] Whitelabel "Products"
  - [ ] MetaAPI?
  - [ ] MyMeta
  - [ ] MetaSys
- [ ] Product pages
- [ ] API Documentation

**Comment by Baconaetor** [comment]
Is there a way to archive issues, or should we just remove this for now? We are so far away from this as to be irrelevant. @peth-yursick do you want to weigh in here?

**Comment by peth-yursick** [comment]
> 
> 
> Is there a way to archive issues, or should we just remove this for now? We are so far away from this as to be irrelevant. @peth-yursick do you want to weigh in here?

Its probably far away but I don't think we should remove it. If anything, it should be here to remind us that's what we want long term 🤷‍♂️

**Comment by peth-yursick** [comment]
Merged to MetaOS Full Roadmap #913
