### ISSUE TITLE
[MyMeta] Bots show up in MyMeta

### ISSUE THREAD

**Issue by mquellhorst** [MetaFam/TheGame#512]
Vercel is listed in the player list on MyMeta.
Only players should show up all others should be filtered out.

**Comment by mquellhorst** [comment]
Could it be that the dev environment is ahead of the production env?
Vercel doesn't seem to be in Hasura in the dev env :)

**Comment by alalonde** [comment]
See the Sourcecred instance for this, especially https://github.com/MetaFam/XP/commit/919c83e9202abca48c1ed37c5dba2f679884f000

**Comment by mquellhorst** [comment]
So the latest version of XP needs to be pushed which will probably fix this, no further action needed
Keep it open to track if this will fix it

**Comment by alalonde** [comment]
I believe this has been fixed. Vercel isn't there anymore
