### ISSUE TITLE
Fix identity collisions in sourcecred account migrator

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#516]
e.g. 

```
ERR! failed to update player ClientError: Uniqueness violation. duplicate key value violates unique constraint "Player_scIdentityId_key":
```

This is happening for dozens of players currently, causing their XP not to update in mymeta.

**Comment by alalonde** [comment]
Also see https://github.com/MetaFam/TheGame/issues/555

**Comment by mquellhorst** [comment]
Bot can update the eth address, closing this
