### ISSUE TITLE
[MyMeta] Add support for xDAI & Polygon DAOs

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#549]
Right now, the profile pages are displaying DAOHaus DAOs & NFTs on Ethereum mainnet.
With the increasing fees on mainnet, both DAOs & NFTs are rapidly moving to xDAI & Polygon.
We should add support for xDAI & Polygon.

**Comment by mattcan** [comment]
![metafam-thegame-549_01](https://user-images.githubusercontent.com/621541/119229021-bd7a4880-baca-11eb-95c0-57e2f0420d97.png)

This is a list of DAOs across mainnet, xDai, and Polygon on a users profile page. A large number of these DAOs have no title or logo. There is also no marker to identify network. Going to pitch this in the design channel but possible solutions:

* if title is missing, use Moloch contract address
* if title is missing, use _Unknown DAO_
* create mini network bands on DAO avatars (I'm thinking like the old 'Fork with Github' bands)
* change the background colour of the DAO avatars dependent on network

We'll have some of the same problems when it comes to the `/players` page too.

**Comment by mattcan** [comment]
Some notes for myself:

* Opensea API (what is being used for NFT data) doesn't seem to report network information though it may support Polygon
* looked at a couple Moloch contracts with no title on the xDai chain, they don't seem to have the `Register` event in history but need to dig more
  * should also check with DaoHaus subgraph team for insights

**Comment by mattcan** [comment]
PR for backend change which adds xDai and Polygon DAOs: #643

**Comment by mattcan** [comment]
I split the NFT work into another issue so I don't block progress while working on DAOs and because it seemed unrelated, at least from a data source perspective. See #647 for NFTs

**Comment by mattcan** [comment]
Unfortunately life is getting in the way and I can't put any more time into MetaFam. I know I don't have a lot done but I do have the one open PR left. There is a build failure that I am unable to replicate, hopefully someone is able to find my mistake.
