### ISSUE TITLE
[MyMeta] Finish the personality type transition (styling & removing)

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#550]
@dysbulic has done a great job building the Magic colors system, now we just need somebody to put in the finishing touches.

First, style the colors & the bars as it was originally designed.
Currently:
![image](https://user-images.githubusercontent.com/55857222/117956479-5e257700-b319-11eb-81de-29d0fed88134.png)
Should be more like this (disregard percentages, it should be 33/33/33):
![image](https://user-images.githubusercontent.com/55857222/117956560-739aa100-b319-11eb-9099-d138a0144b3d.png)

Changes required:
- Make the bar same width as text (much wider than currently)
- Make it rounded & without the edges
- Change the colors to the ones of the designed icons & make them gradient
- Replace the icons, move them below the bar & add more space between them so each icon is centered below its color
- Change the bar that's on the creation flow as well
- Finally, hide the "pioneer, settler & town planner" part of the profile

Icons & colors can be exported from [this figma](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-Copy?node-id=58%3A2), if you can't do it - comment here or contact me on discord.

**Comment by luxumbra** [comment]
I have made a new PR which is ready for review.  [preview here](https://the-game-epam9hk4u-metafam.vercel.app/players)

**Comment by dysbulic** [comment]
This is apparently done.
