### ISSUE TITLE
[MyMeta] Cannot update profile

### ISSUE THREAD

**Issue by Mettodo** [MetaFam/TheGame#553]
I am trying to update my profile. 
When I click to go to the next step, I just go back to the main page.
https://user-images.githubusercontent.com/24914615/118150228-fce5cc80-b41a-11eb-9530-f5e4713e1b9d.mp4

**Comment by dan13ram** [comment]
Can confirm the same thing is happening to me as well.

**Comment by verhovn** [comment]
yeah, i completed only after i start using >> in the up right 
still cannot upload my image (

**Comment by mquellhorst** [comment]
It seems this behavior only occurs in production
When running locally it works fine

**Comment by alalonde** [comment]
Just tried to reproduce in production but now I can't. Can others repro still?

**Comment by geleeroyale** [comment]
Got fixed automagically - possibly by fixing broken Discord bot the day before today.
