### ISSUE TITLE
Support multiple eth addresses

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#555]
I've seen a whole bunch of issues around people switching eth addresses. It seems that we should support a one-to-many relationship between players and eth addresses. 

Is this even supported with sourcecred? Isn't one's eth address just an alias? in that case what is your primary source of identity?

**Comment by dysbulic** [comment]
I'm pretty sure you can have multiple aliases of the same type, and that ETH addresses are aliases, so it should be possible.

The question is when doing disbursements, where do you send it?

**Comment by mquellhorst** [comment]
This is part of SourceCred.
Currently people can update their ETH address with the bot.
Closing this one
