### ISSUE TITLE
[MetaMaps] MetaMaps Bugs

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#56]
- crashes without any error message when opened in a non web3 browser (TypeError: Cannot read property 'enable' of undefined). Should use web3 modal so people can connect with non metamask browsers (e.g. WalletConnect)
- images aren't persisted, when I reload a map the image is broken
- When I change ethereum accounts and refresh, I get infinite loading state
- Also get an infinite loading state when I load it on a mobile app browser (Coinbase Wallet, metamask mobile, etc)
- When I refresh, I see my old map again, but the name of the map gets reset to "metamap". Should make it so it either persists the name and the map, or neither, and give a warning if the user is going to close it without saving changes.

**Comment by TheLoneRonin** [comment]
@hammadj, thanks for the testing Hammad!
I'll make sure to look into those now.

**Comment by dysbulic** [comment]
MetaMaps has been removed from active development.
