### ISSUE TITLE
[MetaMaps] MetaMaps URL / Name Handling

### ISSUE THREAD

**Issue by hammadj** [MetaFam/TheGame#58]
Should set the URL for the map so people can share the link and it will load that specific map. Probably need to have it scoped to the user that created it so there is no naming conflicts. In addition, the URL should be updated in the address bar when the user saves it.

Would also be good to show a dropdown list of the existing maps the user has already created instead of having to type it out and click "load". If the user is saving a map that already exists, the button should say "Update" instead of "Save". If its a new map, it should be "Create" instead of "Save"

**Comment by IxaBrjnko** [comment]
Closed, opened, not sure... I think it would be significantly easier to work on this issue once we have fully merged PRs to MetaMaps-Alpha to be able merge into those into the main TheGame repo so that we can work on this issue directly there <3

**Comment by dysbulic** [comment]
MetaMaps has been removed from active development.
