### ISSUE TITLE
Create MetaCartel Ventures Guild

### ISSUE THREAD

**Issue by vrortvedt** [MetaFam/TheGame#614]
Certain Blood Mages of MetaCartel Ventures have expressed interest in creating an MCV MetaGame funding guild to be able to interact with the wider crypto community beyond our Moloch contract.

Our DAO is here: https://app.daohaus.club/dao/0x1/0x4570b4faf71e23942b8b9f934b47ccedf7540162/

We'd like to request the creation of an MG guild.

**Comment by peth-yursick** [comment]
@hammadj @alalonde @mquellhorst
