### ISSUE TITLE
[Quests] Intro & Evergreen quests

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#627]
Currently, intro & evergreen quests are all in Notion but we should move them all to the actual questing interface.
The difference between onboarding or evergreen quests & "normal" quests is that the players will need to complete a few of the former to be able to take "normal" quests.

Exact numbers as well as the design to-be-discussed
Interested? Comment here.

**Comment by Baconaetor** [comment]
What do you mean by "actual questing interface"? The Wiki?

**Comment by jonathanprozzi** [comment]
I'm interested in this peth and would like to learn more.

**Comment by peth-yursick** [comment]
> 
> 
> What do you mean by "actual questing interface"? The Wiki?

No no, up on the website: https://my.metagame.wtf/quests



> 
> 
> I'm interested in this peth and would like to learn more.

Nice! This one requires #487 to be completed first, which is currently assigned to @mquellhorst but I'm guessing he'd be willing to pass it on to you as he has a bunch of other issues assigned to him (for which he's also not submitting any PRs 😝 @mquellhorst)

**Comment by peth-yursick** [comment]
Realized there's another blocker to moving the quests to the website 😬 @jonathanprozzi 
Its building the Raids #642

**Comment by peth-yursick** [comment]
Done!
