### ISSUE TITLE
[Quests] Upvoting

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#635]
A propose a simple upvoting system where any player or patron can upvote or downvote a quest.
For this, the app would need to check whether the person has a player role on our discord or 8 polygon pSeeds.

A better version of this issue would be using Seeds to upvote.
Each upvote would cost 1 Seeds which would go towards additional bounty for quest completion & make the quest float up in the quests explorer.
For this, additional logic in terms of actual payout would need to be implemented.

To complete, you'll first need a design.
Ask about it in #designers-guild on Discord 🙃

**Comment by mquellhorst** [comment]
This could help prioritizing quests

**Comment by Seroxdesign** [comment]
Outdated
