### ISSUE TITLE
Have Patrons Pool Eth Instead of Buying Seeds

### ISSUE THREAD

**Issue by Baconaetor** [MetaFam/TheGame#636]
Per Discord conversation here:
https://discord.com/channels/629411177947987986/783432928804732928/851925062801162290
We've decided to have Patrons add Eth directly to the pSeed Balancer pool, instead of buying seeds first. So we need to:
1. Calcuate a recommended Eth amount
2. Update all documentation

**Comment by Baconaetor** [comment]
Just realized it's WETH not ETH. . .

**Comment by peth-yursick** [comment]
> 
> 
> Per Discord conversation here:
> https://discord.com/channels/629411177947987986/783432928804732928/851925062801162290
> We've decided to have Patrons add Eth directly to the pSeed Balancer pool, instead of buying seeds first. So we need to:
> 
>     1. Calcuate a recommended Eth amount
> 
>     2. Update all documentation

Hey man, thank you for being so quick to act but this is the wrong repo
The right one: https://github.com/MetaFam/metagame-wiki/issues

**Comment by Baconaetor** [comment]
Opps, sorry about that. The worst part is I legit debated this for like ten minutes before I created it, and still got it wrong! 🤦
