### ISSUE TITLE
[Quests] Raids

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#642]
So, we got Quests, but before we move on with moving all the Quests from Notion to the website & making a huge mess, we should first have Raids.

What are raids? Simply, groups of quests.
Raids can be displayed in the same way as quests:
![image](https://user-images.githubusercontent.com/55857222/121421757-cabe8080-c96e-11eb-9eee-38bcea0c4236.png)
A raid should look pretty much like a quest:
![image](https://user-images.githubusercontent.com/55857222/121421695-b7abb080-c96e-11eb-8143-35b20c6b5090.png)
Except...
Instead of "proposal", they have quests inside them:
![image](https://user-images.githubusercontent.com/55857222/121422201-43254180-c96f-11eb-9faa-7355f100a4c9.png)

Would be great if they were displayed in columns based on what stage they're in:
![image](https://user-images.githubusercontent.com/55857222/121422406-8089cf00-c96f-11eb-9208-ba8feea61249.png)
But that will require some input from the designers.
To begin with, there could simply be more categories than just "open".
![image](https://user-images.githubusercontent.com/55857222/121422512-9a2b1680-c96f-11eb-9c24-921c57673203.png)

Long term, there should be a nicer way of displaying all of the raids & who's working on them, like the State of Raids map (except automatically updating)
![image](https://user-images.githubusercontent.com/55857222/121423637-c72bf900-c970-11eb-8620-98f24a014a2c.png)

There was some more thinking in terms of speccing Raids a ages ago, refer to #455

**Comment by Baconaetor** [comment]
Ah, yeah, thanks for linking me this @peth-yursick! This is def the kinda thing we need to make progress on. Specifically that State of Raids map so it's easier for people to tell what's going on. Do we have any designers working on this?

**Comment by peth-yursick** [comment]
> Ah, yeah, thanks for linking me this @peth-yursick! This is def the kinda thing we need to make progress on. Specifically that State of Raids map so it's easier for people to tell what's going on. Do we have any designers working on this?

Oh man, I wish... 😂
What are your thoughts on this map vs the new one?
![image](https://user-images.githubusercontent.com/55857222/145691423-007784f3-5770-42a1-bd95-e3ee6898b84f.png)

The main differences:
- The old one had the green ring that was indicating whether the project is upcoming, progressing optimally or struggling.
- The new one maps domains/internal guilds & roles (still has 🚨 for what should be prioritized but the map is less readable)
