### ISSUE TITLE
[MyMeta] Add support for xDAI & Polygon NFTs

### ISSUE THREAD

**Issue by mattcan** [MetaFam/TheGame#647]
Split from #549 due to size.

---

## What

Load and display NFTs from xDai and Polygon chains.

## Why

Due to transaction costs, NFTs are moving to alternative chains. For example, many POAPs are deployed on xDai. We want to be where our users are.

## How

Currently, NFTs are being pulled from the OpenSea API. OpenSea allows users to post NFTs on Ethereum, Matic (Polygon), and Klatyn. There does not seem to be mention of xDai.

Your problem may be half solved by verifying if Matic/Polygon NFTs are showing on MyMeta.

## References

* https://matic.opensea.io/
* https://docs.opensea.io/reference#api-overview

**Comment by peth-yursick** [comment]
Hey man! Any chance you're interested in picking this back up now, a year+ later @mattcan? 😂
It seems to be a much needed thing now that we're minting achievements as well as Quest Chains NFTs on Polygon..
Couldn't find you on discord unfortunately

**Comment by Seroxdesign** [comment]
Moving onto Optimism so gonna close
