### ISSUE TITLE
[Quests] Playbooks UI

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#657]
_This quest was discussed as part of the call around the Wiki revamp, which took place on June 11, 2021. Complete notes from the call can be found [here](https://www.notion.so/S2W11-MetaGame-Wiki-Migration-Rebuild-Discussion-11-June-2021-6521656b2b7e470eb6c7afb11460e6f6)._

Playbooks are meant to serve as guides for people who have just joined MetaGame. They can be found in a dedicated subspace in the Wiki: [Browse playbooks | MetaGame Wiki](https://www.notion.so/Playbooks-UI-5ae958cfe1e945658deecd3a78764a0a#0315bf2c8239499a9161c2cbe4d6e888)

With new plans in place for migration and revamp of the Wiki, it's a good time to start working on the new and enhanced Playbooks UI.

**Comment by davort** [comment]
Before we get down to sketching out ideas, it would be good to learn more about the technical possibilities and limitations of [Docusaurus](https://docusaurus.io/). This is currently being investigated, so hopefully we will soon be able to discuss the feasibility of the following ideas for the Playbooks UI.

**Basic features**

- Search, Filter, Sort → parameters TBD. Recycle existing filtering UI from #503 
- Reactions / emojis → e.g. to be able to react when certain parts of a playbook are outdated (perhaps there's a better way of solving this particular problem, but emoji-ing might still be interesting)
- Comments → how does that work with Docusaurus? If not possible, should we open and keep playbook-specific discussions on Discourse, instead?

**Nice to haves**
- Sharing as a feature? → perhaps just being able to click a shortened link, and have it added to clipboard, ready to be pasted anywhere? 
- Bookmarking or saving for later? → presuming players can somehow "log in" to the wiki?
- Rating playbooks → perhaps just positive ratings, such as "I recommend this".

**Comment by dysbulic** [comment]
There is a related [issue within the wiki repository](https://github.com/MetaFam/metagame-wiki/issues/257).
