### ISSUE TITLE
XP updates to Player page

### ISSUE THREAD

**Issue by plasmacorral** [MetaFam/TheGame#666]
I know this has been raised in the past.  I looked but did not find any open or closed issues in our XP or Sourcecred repos.  

Page here: https://my.metagame.wtf/players does not reflect XP changes shown here: https://xp.metagame.wtf/#/explorer.

Is that something easy to fix and is there a longer term change to help keep the XP shown in sync?

**Comment by alalonde** [comment]
Yes, I am aware of this. I am hoping the latest deployment fixes this
