### ISSUE TITLE
Gracefully handle DAOhaus API availability problems

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#687]
Currently in the test environment we're seeing lots of these:

```
Jul 6 03:25:31 AM  Pulling memberships failed: FetchError: request to https://api.thegraph.com/subgraphs/name/odyssy-automaton/daohaus-xdai failed, reason: connect ETIMEDOUT 104.18.10.19:443
```

I assume that the URL is correct, but the endpoint is down? If so we should anticipate outages and handle them gracefully.

@mattcan

**Comment by mattcan** [comment]
I think what you are seeing is this: https://github.com/MetaFam/TheGame/blob/develop/packages/backend/src/handlers/remote-schemas/resolvers/daohaus/resolver.ts#L32-L39

I should have made that a `console.warn`

**Comment by mattcan** [comment]
Work in progress branch that I started a few weeks ago. Quickly added this test now, and it is passing: https://github.com/MetaFam/TheGame/commit/c836130dc135982a5c87be72e2b2fb1ac7a98b82

(I'm getting tslint errors during commit that I don't understand, which is why I haven't pushed it previously)
