### ISSUE TITLE
lerna isn't updating discord bot & other packages

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#698]
I was just helping @luxumbra and part of the fix was going into `discord-bot`, removing `dist/`, running `yarn`, and then `yarn build`. `yarn build` would not run until `yarn` was run despite being run from the root.

After that the same basic issue occurred with `packages/web/` where it is necessary to manually run `yarn` in the directory.

So, `lerna` isn't updating all the packages node modules as expected.

**Comment by tommymaher15** [comment]
I feel this one is potentially blocking me from solving  [this issue](https://github.com/MetaFam/TheGame/issues/343l). 

Just tried to add a LInkOverlay for this issue and getting some lerna errors  in the console I could add in here if thats useful. Quite new to a lot of things here right now but would be curious about this one has I've not used lerna before.

**Comment by mquellhorst** [comment]
Just ran a fresh install and there were no problems.
On my other system where this issue occurring I was able to fix it by clearing docker containers and images by running:

```shell script
docker system prune -a
```

I've added this to the documentation.
I'll close the issue for now.

Let @mquellhorst  or @dysbulic know if you keep experiencing this behaviour
