### ISSUE TITLE
Change the timezone display to IDX's residence city and country

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#707]
Currently the cities associated with the timezone selections are often far from the actual location of the user. IDX's `basicProfile` includes `residenceCity` and `country` properties. These will be present in the IDX cache (#686) when it goes live and can be utilized for the location for the timezone.

**Comment by alalonde** [comment]
Yeah, agreed that that data is more useful than an explicit timezone. I was going to suggest changing the current setup profile from timezone to city / country, but it's probably not worth the effort.

**Comment by peth-yursick** [comment]
Connecting this #718 thing as it seems more likely to fit the original purpose of having timezones

**Comment by peth-yursick** [comment]
Looks like we're now displaying both location & timezone so closing this
