### ISSUE TITLE
The color display on a player's profile is broken

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#716]
Some recent change altered the display of the color chart on the players' profile pages. It now looks like:

![Screenshot from 2021-07-22 04-01-05](https://user-images.githubusercontent.com/181523/126607512-c575d1be-8ef5-4bda-8415-816e2e8a5e99.png)

**Comment by tommymaher15** [comment]
Quick question on this. 

What did it look like before?

**Comment by tommymaher15** [comment]
Is the issue above on a specific profile? 

it doesn't seem to be be active currently

**Comment by dysbulic** [comment]
¿Are you able to view [this Figma](https://www.figma.com/file/n36ggiRBQEGzRUbGxWfkMX/Meta-Game-Copy?node-id=58%3A2)? There is an example of the color chart on the profile on the upper right-hand side.

It is only present for players who have updated their profile since it was added, which isn't many. [@luxumbra has it.](https://my.metagame.wtf/player/luxumbra)

**Comment by tommymaher15** [comment]
I just checked some profiles that have it active and the bug doesn't seem to be showing at least for me.

**Comment by dysbulic** [comment]
> [T]he bug doesn't seem to be showing at least for me.

Good point. It isn't present in Firefox and Opera apparently, but it is in Chrome and Brave.

**Comment by tommymaher15** [comment]
Weird. I'm actually on Chrome right now

**Comment by dysbulic** [comment]
> Weird. I'm actually on Chrome right now

Huh… ¿What OS? I'm in Ubuntu. Let me go check a Windows box…

**Comment by tommymaher15** [comment]
I'm on a windows 10 machine right now. thats a strange one

**Comment by dysbulic** [comment]
I see the bug in Windows 10 on Chrome 92.0.4515.107. I also see it in Chrome on Android.

Do you have an Android device?

**Comment by tommymaher15** [comment]
Yeah I do I'll test it out and see what happens

**Comment by dysbulic** [comment]
Edge on Windows is also broken for me.

**Comment by tommymaher15** [comment]
Yep I can see it now! 

I'll start testing some stuff out now to get it back. 

Good catch thanks for the help.

**Comment by tommymaher15** [comment]
I think I've fixed it. 

There was a flex container wrapping the  ColorBar within PlayerHero.tsx 

I removed this and it's seemed to do the trick initially. Will test on other devices and see if that was the right thing to do
