### ISSUE TITLE
Add "office hours" section to Player Profile and Player Card

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#718]
Currently timezone is used to determine a player's whereabouts, which may or may not correlate with that same player's preferred working hours. 

There may be reasons for players to prefer working outside the "9 to 5" window, and it may vary wildly.

"Office hours" section would allow for finding players who are accessible during a specified time window.

**Comment by peth-yursick** [comment]
Maybe unnecessary now that people can integrate Meetwithwallet, Calendly etc @davort?

**Comment by davort** [comment]
> Maybe unnecessary now that people can integrate Meetwithwallet, Calendly etc @davort?

Agreed 👍🏻
