### ISSUE TITLE
Responsive "Sort & Filter" UI

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#725]
The "Sort & Filter" UI was first introduced for browsing the list of players. 
In #503 @dan13ram and I made it work nicely for the largest and smallest viewports, but the "middle ground" is not so great.

Seeing how the UI is still fully functional, even if visually suboptimal, in certain medium-sized viewports, we agreed that this should be addressed in a separate issue.

**Comment by alalonde** [comment]
@davort Has this been completed on my.metagame.wtf ?

**Comment by davort** [comment]
Hey @alalonde - I am not 100% sure what you mean exactly with "completed". 
There are some final additions that need to find their way to the live site. More info here: https://github.com/MetaFam/TheGame/pull/724
