### ISSUE TITLE
Remove packages/web/.env.local from the repository

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#730]
A couple months ago I lost three days trying to figure out why I couldn't get my changes in Hasura to display locally. It took @dan13ram to help me figure out it was because the file `packages/web/.env.local` was sending my requests to the production backend.

I just blew another few hours doing the same thing again with @chair28980.

The [contributing guide](https://github.com/MetaFam/TheGame/blob/develop/guides/FRONTEND.md#connecting-to-remote-servers) tells the user to create this file, so we don't need it in the repository.

I vote we remove it. ¿Any objections?

**Comment by dan13ram** [comment]
It's in the repo?
If yes, we should definitely remove it.

**Comment by dysbulic** [comment]
Well, hmm, I had no memory of creating it & @chair28980 didn't either, but it isn't in the repo. I guess we both followed the frontend guide & forgot about it. 😬

Nevermind.
