### ISSUE TITLE
Upgrade bcrypto to v5.4

### ISSUE THREAD

**Issue by mquellhorst** [MetaFam/TheGame#740]
Current version is 5.2.
v5.4 seems to be needed on [M1 architecture](https://github.com/bcoin-org/bcoin/pull/1009).

Needs testing on other architecture / OS

- [x] OSX M1
- [ ] OSX x86_64
- [ ] Windows x86_64 (x86_32)
- [ ] Linux x86_64

**Comment by alalonde** [comment]
Are people seeing build issues with 5.2?  `3box` depends on this package which is now deprecated. We could force the version to 5.4 but would have to test that 3box works with it

**Comment by mquellhorst** [comment]
Yeah at least someone with a mac on M1 architecture needed to update to v5.4 to make it work.
I updated on a linux system and had no problems but it didn't ran the caching profiles action. I guess that's the part which uses 3box.

**Comment by mquellhorst** [comment]
For now the M1 architecture problem is fixed by #803
