### ISSUE TITLE
Playbooks 

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#752]
Playbooks are short onboarding & skill-building guides.
Right now they are hosted [on the wiki](https://wiki.metagame.wtf/docs/playbooks/browse) but we need to build them a proper interface to make it easier for people to submit them as well as upvote/downvote them, filter them, etc.

The design should be based on the [existing MetaGame branding](https://skinny-estimate-0fd.notion.site/Design-MetaGame-1f9977cfaf3e4c29aeaa225734152f22) & some of this [design already exists for Playbooks as well](https://skinny-estimate-0fd.notion.site/Playbooks-UI-5ae958cfe1e945658deecd3a78764a0a).

The design still needs to be finished & help is required but we mainly need help with building. You can find the links to everything you'll need to [get familiar with the codebase here](https://skinny-estimate-0fd.notion.site/Builder-Path-aed890599bc743d8896f6f3249693ca2), you can [ask for help here](https://discord.gg/6JFXC9T) or contact me @petheth on twitter or telegram.

Useful things to get built:
- Playbook posting itself
- Categories & filtering
- Upvoting/downvoting playbooks
- Time to read
- Reacting to playbooks
- Comment
- Share
- Fork
- Bookmark (pin to your "dashboard" or "goals" both of which are nonexistant features)

We realize this is far from being specced out & requires more than 2 people, but if you're interested in jumping on this, do know there are others ready to jump in & help as well.
If you're interested in working on this, just comment here or [ask about it on discord](https://discord.gg/6JFXC9T).

More links:
[Playbooks Spec WIP](https://docs.google.com/document/d/1OZlidtGFbhNFb6aKnEJBR7ycnduXamChaW2s8pchdzE/edit#)
[More info on the whole Playbooks project](https://meta-game.notion.site/Playbooks-UI-5ae958cfe1e945658deecd3a78764a0a)
[Playbook WIPs on Notion](https://www.notion.so/Write-a-Playbook-3d8b963053f5457091abfe74f06248c9)
[📕-playbooks discussion on Discord](https://discord.gg/TCFdHCr)
[Playbooks UI WIP](https://www.figma.com/file/EDj3DFVrV2ms6QA7Q8gRdp/Playbooks-UI---Quick-Questions?node-id=0%3A1)

**Comment by alalonde** [comment]
At Peth's request, I'm attempting to lay out a path towards an MVP for adding playbooks to the existing codebase (commonly known as MyMeta).

This seems to include, at the least:

Backend:
- Defining new schema / tables to be added to Hasura / Postgres (Can be mostly inferred from here)
  - This can include additional metadata not necessarily in scope for the MVP as it's easiest to define as much of the schema as possible up-front
  - Consider permissions in Hasura, e.g. only the author can edit their own playbook
    - Playbooks are world-readable

Web:
- Pick a rich-text editor / display component that is sufficiently advanced to accommodate all the content we want to include in Playbooks (we can probably just start with what Docusaurus etc supports)
  - Probably needs some flexibility with import / export in different data structures
  - How is the content data stored? Is it just exported as JSON, markdown, HTML etc? What about images? Can we just stuff the content in a database BLOB column or the like? Do we want to associate the content with the creator somehow via e.g ceramic?
- Create / edit interface. This is essentially just the rich-text editor with a save button, plus additional fields for e.g. category selection, title, isPublished, cover image.
  - Authors must have a mymeta profile and be "signed in" 
  - Probably sufficient to support this for large devices only .. ?
- View playbook interface
  - Could be built-in to the rich-text component as a different "view" 
  - Are there designs for this? I suppose it's somewhat dependent on the chosen rich-text component
- List / filter playbook interface
  - Seems like there are designs for this already
  - Probably sufficient to just support listing all playbooks for the time being, only need e.g. filtering when there's so much content that it's not easily discoverable
- "Time to read" is presumably just calculated based on word count or the like and can be re-computed on save in the backend

After writing this all out, it seems like choosing the rich-text editor / viewer is step #1, with possibly the DB schema definition happening in parallel.
