### ISSUE TITLE
[MyMeta] DAOHaus DAOs not being displayed in memberships

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#756]
DAOhaus DAO memberships are no longer being displayed on player profiles, likely due to changes in the DAOhaus graph?
Needs to be fixed.

**Comment by alalonde** [comment]
This _may_ have been fixed with #729, created a PR to get it into master

**Comment by peth-yursick** [comment]
> 
> 
> This _may_ have been fixed with #729, created a PR to get it into master

Indeed! Thank you
