### ISSUE TITLE
Moar Data! - Add more data to MyMeta player & guild profiles

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#757]
Merged into #264

**Comment by mquellhorst** [comment]
I propose to first make an overview of all the data points we like to be added so the builder picking up this issue knows exactly what to do. Anyone up for that?

**Comment by dysbulic** [comment]
So, HackFS is over and the next thing in my sights (unless MetaFactory makes loud noises about their as-of-yet incomplete NFTs) is adding an interface for editing [IDX's base profile](https://github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-19/CIP-19.md#record-schema) as well as create a new schema to hold additional fields MetaGame wants to define.

The information we currently save from IDX is:
* name
* image URL
* background image URL
* location
* country
* description
* emoji
* gender
* website

Of that, all of it is displayed except `location`, `country`, and `gender`. The location information is slated to be displayed as part of the timezone display. I don't particularly like `gender` as a field. I think it should simply be `pronouns` without someone having to name their gender.

The profile information stored by MetaGame in the Hasura instance is:
* username
* color disposition
* timezone
* available hours
* rank
* seasonal xp
* total xp
* skills

Additionally, we store verifications of account ownership for Twitter and GitHub.
