### ISSUE TITLE
[MyMeta] Use the Ceramic Network as Source of Truth

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#769]
I am gearing up to begin a two part process to give users ownership of their profile data by creating a frontend to manage the basicProfile and a new IDX definition for MetaGame-specific profile elements.

This work will touch a bunch of issues:

* [x] #309
* [ ] #757
* [ ] #718
* [ ] #715
* [ ] #707
* [ ] #547 (possibly)
* [ ] #443
* [x] #386
* [ ] #363
* [x] #331
* [ ] #311 (possibly)
* [x] #278
* [x] #27

It supersedes #155.

**Comment by dysbulic** [comment]
@alalonde @dan13ram @hammadj @mquellhorst Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/MetaOS-6012e782d1bec10015d7f4e5/issues/MetaFam/TheGame/769?planning-poker)

**Comment by tommymaher15** [comment]
If I can help out on any of these issues I'd be happy to. Got everything fixed and running on my end at last.
