### ISSUE TITLE
Pull in player's guild memberships data from Discord

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#771]
I am finishing up #184 which allows us to pull just about any data from a guild's discord server.  This allows us to improve at least two sections of MyMeta, the first of which this issue will cover:

### A player's list of guilds in their profile
(For reference, see the Memberships section here: https://my.metagame.wtf/player/metadreamer)

Currently we show some hardcoded information for Metagame: 
![image](https://user-images.githubusercontent.com/1402582/130112748-4f45b853-12e0-45bc-ab0b-26211b04ec01.png) 
But now we can migrate existing MyMeta guilds to get their information from a discord server as opposed to moloch. Here is what we currently show for Metadreamer's moloch-fetched DAO membership:  
![image](https://user-images.githubusercontent.com/1402582/130113414-058b6e64-d514-4059-9535-7effb0dc69cb.png)
These images have been manually curated and placed in the MyMeta codebase, whereas now we can just fetch the logo from a Discord CDN.  

### Outstanding questions
- Does it make sense to reorganize the memberships section now? I could see us now separating DAO memberships (which may be totally external to MetaGame) and guild memberships (which by definition are within MyMeta) 
- Currently we have "Player" hardcoded beneath a DAO as well as their pulled-in share (member share divided by total shares). "Player" doesn't really make sense here, I would recommend just removing this. 
- For guilds with their Discord server linked, we could e.g. fetch a player's highest role in their server and display that. 
- Undoubtedly there is more interesting information we could pull in from Discord and display as well. We have full access to their server via the Discord API.

**Comment by peth-yursick** [comment]
Great to see this coming together! Thank you 🙏
> Does it make sense to reorganize the memberships section now? I could see us now separating DAO memberships (which may be totally external to MetaGame) and guild memberships (which by definition are within MyMeta)
What do you mean by reorganizing it? Might not be necessary to separate DAO memberships from guild memberships as guilds can have a DAO or not have it, I'd say prioritize data from daohaus if it exists, otherwise discord.
> Currently we have "Player" hardcoded beneath a DAO as well as their pulled-in share (member share divided by total shares). "Player" doesn't really make sense here, I would recommend just removing this.
> For guilds with their Discord server linked, we could e.g. fetch a player's highest role in their server and display that.
Yeah, I think that makes sense. And for the ones that only have daohaus, we could just have it say "member"?
> Undoubtedly there is more interesting information we could pull in from Discord and display as well. We have full access to their server via the Discord API.
Nice! Yeah, would be very cool to display some of their discord data on the profiles.

**Comment by alalonde** [comment]
Keeping this open for now as a placeholder for these items, documented in the #772 PR:

TODO still:

-  Do we also want to populate / sync guild_player with DAO memberships? This would make it easier to abstract away the nature of the membership (discord server vs DAO) and just dynamically fetch the relevant metadata on-demand
- Add a data migration to link known DAO addresses with their corresponding guilds
- The players section of a guild could benefit from sorting (if a DAO is linked, by total shares, otherwise by highest discord role position). We'll need a new action e.g. getDiscordGuildMemberRoles as it would be too expensive to fetch for each user (presumably?)
