### ISSUE TITLE
[Events] Liminal Village

### ISSUE THREAD

**Issue by Baconaetor** [MetaFam/TheGame#775]
Place holder for the Liminal Village/Italy gathering on the ZenHub roadmap.

**Comment by peth-yursick** [comment]
What was the purpose of these @Baconaetor?

**Comment by dysbulic** [comment]
> What was the purpose of these?

They are used to block out time spans in the [ZenHub Roadmap](https://github.com/MetaFam/TheGame/issues/775#workspaces/metaos-6012e782d1bec10015d7f4e5/roadmap?repos=255885896).

**Comment by peth-yursick** [comment]
> 
> 
> > What was the purpose of these?
> 
> They are used to block out time spans in the [ZenHub Roadmap](https://github.com/MetaFam/TheGame/issues/775#workspaces/metaos-6012e782d1bec10015d7f4e5/roadmap?repos=255885896).

Why & can I close them now since we got 78 open issues?

**Comment by Baconaetor** [comment]
> 
> 
> > > What was the purpose of these?
> > 
> > 
> > They are used to block out time spans in the [ZenHub Roadmap](https://github.com/MetaFam/TheGame/issues/775#workspaces/metaos-6012e782d1bec10015d7f4e5/roadmap?repos=255885896).
> 
> Why & can I close them now since we got 78 open issues?

I was experimenting to try and help create a good roadmap for us. You can close them yes, or. . .I guess I will while I'm here.
