### ISSUE TITLE
[MyMeta] Upgrade to Next 11 & React 17

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#792]
@Cali93 & I would like to [web3.storage](//web3.storage) to house the [profile, header](https://github.com/MetaFam/TheGame/issues/27), and [background](https://github.com/MetaFam/TheGame/issues/443) images being added by users of the in-house front end to IDX.

We are having difficulty getting it to work and all signs point to it would likely work with the latest versions of Next and React.

React 17 has been out for almost a year, and it's useful in general to be using the current stable release.

@mquellhorst was in the programming session as well and concurred this seems like the most expedient path.

**Comment by mquellhorst** [comment]
Involves #793

**Comment by dysbulic** [comment]
[IDX](//idx.xyz) is being deprecated in favor of [Glaze](https://developers.ceramic.network/tools/glaze/overview/) which also requires Webpack 5 and motivates us to do this update.

**Comment by mquellhorst** [comment]
React has been updated.
NextJS can be updated to version 12 but needs testing.

**Comment by alalonde** [comment]
React, yes, Next, no.

**Comment by peth-yursick** [comment]
> React, yes, Next, no.

looks like rich changed his mind lol
so the issue should remain open?
if so, should it be put on the priorities list on dework or kept here for now?

**Comment by alalonde** [comment]
I'll leave that answer to @dysbulic, not sure what has changed since he created this. Probably no to dework though

**Comment by dysbulic** [comment]
I'm upgrading to React 18 and Next 12 as part of #1405.

**Comment by peth-yursick** [comment]
> I'm upgrading to React 18 and Next 12 as part of #1405.

Nice nice, closing this then
