### ISSUE TITLE
[MetaOS] Megamenu - Add User menu with links

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#818]
Let's add a menu that opens when the user's avatar is clicked. 

The menu should contain two links from the start:

1. View profile
2. Disconnect

More options may be added later on, but these two will suffice for the time being.

I would suggest using Chakra UI's [Menu component](https://chakra-ui.com/docs/overlay/menu) for this.

Let me know if you're good to add this in without a visual spec, or if you'd prefer me to first design something in Figma. Either will be be fine with me 😊

**Comment by phys3** [comment]
Added in this pr https://github.com/MetaFam/TheGame/pull/817

**Comment by mquellhorst** [comment]
Closed by #817
