### ISSUE TITLE
[MetaOS] - Change font for Megamenu to Exo 2

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#819]
The original design in Figma used Exo, which was the first and only variant of that typeface at the time. It has been updated and improved with its second release - [Exo 2](https://fonts.google.com/specimen/Exo+2)

This is already visible in Figma: [Mega Menu](https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/Mega-Menu?node-id=684%3A281)

We'll need these variants of the font:

- Regular 400
- Regular 400 italic
- Medium 500
- Bold 700

**Note:** This same font will eventually become _the_ font for the whole MyMeta website, with eventually one of the existing fonts in use kept for headlines. But more on that in near future.

Let me know if you have any questions.

**Comment by phys3** [comment]
switched in this pr https://github.com/MetaFam/TheGame/pull/817 not yet merged

**Comment by davort** [comment]
Great, thanks @phys3.

Any chance you could change the font on the "CONNECT" button to Exo 2, too? Or is that something that falls out of the scope for MegaMenu adjustments?

![CleanShot 2021-09-12 at 18.19.29.png](https://images.zenhubusercontent.com/603d32d6edb5330e5cd0dd54/0373e2f5-0654-4dec-b45c-22541baaff38)###

**Comment by mquellhorst** [comment]
Closed by #817
