### ISSUE TITLE
[MyMeta]: Make the staging and production sites use a single Postgres instance

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#824]
@polimyl pointed out that we don't have to be running two separate Postgres instances on [Render](//render.com). We could be running staging and production as separate databases in a single instance. Removing one of the Postgres instances will save us $7 / month.

**Comment by alalonde** [comment]
Ha, yeah, duh 😁 🤪

**Comment by alalonde** [comment]
Just looked into this. Render actually does charge by the database, not database instance. Attempting to create a new database within an existing instance resulted in a "Permission denied" error
