### ISSUE TITLE
[MetaOS] Fixing MetaMenu Links

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#840]
The new menu looks great but some of the links are wrong & some are missing.

To replace
- On the community tab
  - Under the community tab, there is an "alliance" button & the alliances page doesn't exist yet. I think this should be replaced with a link & an icon for the community Calendar & renamed to "Events"
  - Discord link has expired - should be replaced with https://discord.gg/metagame
- On the learn tab
  - Welcome to MetaGame link [should be this](https://meta-game.notion.site/Welcome-to-MetaGame-7e28e75f3c264c7b939eaaa2239b9c28)
  - "On your path to becoming a player? Go through here"
  - Great Houses should switch places with Playbooks
  - Asketh & Skill Trees should probably just be removed as they don't exist yet
  - MetaRadio is missing completely, [add pls](https://anchor.fm/MetaGame/)
  - Same for the [MetaMedia youtube](https://www.youtube.com/metamedia) channel which has a bunch of interesting videos
- On Contribute
  - Roles is taking people to wiki but [should actually be taking them here](https://meta-game.notion.site/Internal-Roles-Guilds-bec3a0437f684322b650dbb7aca616e8)
  - Quests aren't working yet so the link should temporarily be changed [to this](https://meta-game.notion.site/e0e83b7ea2a54d6294c5e167ba7b306a?v=81e5d4755ab44c3a93df3eaaee6fd369)
- Invest
  - The first button should be "Become a Patron" with a link [to this](https://wiki.metagame.wtf/docs/enter-metagame/why-patron)
  - The second link should be "Buy Seeds" with a link [to here](https://app.balancer.fi/#/swap/ether/0x30cf203b48edaa42c3b4918e955fed26cd012a3f)
  - Third should be "Plant Seeds" with the link [to the pool](https://pools.balancer.exchange/#/pool/0xea05a15dbce2eb543ffda16950e95b2bd2e40d0e/)
  - Finally, "Support Grants" which should be taking people [to Giveth](https://giveth.io/)

**Comment by peth-yursick** [comment]
@blake-hunsicker or @phys3 might be interested in this one

**Comment by phys3** [comment]
Waiting for:
- Events icon
- Metaradio icon
- Youtube icon
- Become a patron icon
@davort

Fixed in this pr https://github.com/MetaFam/TheGame/pull/842

**Comment by davort** [comment]
@peth-yursick & @phys3 – sure thing, but we'll have to order these icons from Trolleo. They weren't included in the original package, since these links weren't there in the [early wireframes](https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/?node-id=0%3A1), when we had done the original planning.

In the meantime, I'll make some placeholder icon we can use, even if it ends up being ugly as hell. But it will have unblocked us, at least.

**Comment by davort** [comment]
Pinged Trolleo and in the meantime created the 4 requested icons. Here's a preview: 
![CleanShot 2021-09-27 at 18 37 10](https://user-images.githubusercontent.com/1573304/134949930-af2b24ad-6b4e-4f60-9721-719a47460323.png)

@phys3 please find them here: https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/Mega-Menu?node-id=980%3A707
