### ISSUE TITLE
Library 📚 Button 🤔 you good bro❓❓

### ISSUE THREAD

**Issue by jb0gie** [MetaFam/TheGame#852]
https://wiki.metagame.wtf/docs/home#here 
does this button work yet? all i see it doing is making the floating sidebar thingy twinkle only noticed that after spam clicking (hehe)

maybeh like add some SFX or make it a touch more `apparent` when a user clicks on something hehe look at b0gie raising issues weeeeeeeee 
![image](https://user-images.githubusercontent.com/6885227/135994026-34fda91d-ff5b-4b95-ab37-270b5b4a4080.png)

**Comment by peth-yursick** [comment]
The library button used to be "👈" to indicate that the library is the sidebar, but someone thought it made no sense & changed it to 📚 & in a weird way, now it makes even less sense.
The sidebar highlights when you click the button to show that is it, that its already open.
Anyway, this is an issue for the wiki, not TheGame, if you still want it: https://github.com/MetaFam/metagame-wiki/issues
