### ISSUE TITLE
Next and Previous Buttons needed when scrolling through Players

### ISSUE THREAD

**Issue by tenfinney** [MetaFam/TheGame#870]
When i wanted to review every player's profile in succession I needed to click back to all the players, then scroll down and then click the next one.  Each time it required a re-querying of all the players.  As you go deeper in the list it becomes more time intensive and a little frustrating.

An efficiency would be to add "Next" and "Previous" buttons when people are in  in a profile to see the next or previous player profile.

**Comment by Udit-takkar** [comment]
Do you think a previous and next button would fix this ?  
I think retaining the scroll position would be better

**Comment by Udit-takkar** [comment]
the fetching of the  players is also very slow. How can we optimize this?

**Comment by mquellhorst** [comment]
The slow load is refered here: #997

**Comment by peth-yursick** [comment]
looks like this was fixed without adding buttons
