### ISSUE TITLE
Indicate number of active players

### ISSUE THREAD

**Issue by tenfinney** [MetaFam/TheGame#871]
In our documents we talk about 150 player limit but it looks like a lot more than that are queried. 
Solution? I'm not sure. Set the max amount queried to 150?
![309-players](https://user-images.githubusercontent.com/32429716/138092191-759cd7a3-98a5-497a-9cef-8cbae4d7c8ad.png)
?

**Comment by luxumbra** [comment]
> In our documents we talk about 150 player limit but it looks like a lot more than that are queried. Solution? I'm not sure. Set the max amount queried to 150?

We are limited to 150 players and currently have about 89 players in discord. MyMeta acts as a hall of fame, so I don't think having a hard limit on players queried makes sense. That said, having a filter for 'current' and 'past' and default to just showing the 150 most active would perhaps be a nice addition.

**Comment by luxumbra** [comment]
I think it should be limited to current players & anyone who reached a rank. if you're ranked but dont have the player role anymore, you should drop off the leaderboard when you drop out of the ranked roles.

**Comment by mquellhorst** [comment]
Behind the total number of players we can add the nr of active players in brackets for example

**Comment by peth-yursick** [comment]
> Behind the total number of players we can add the nr of active players in brackets for example
> 
> Maybe also a label on the profile whether a player is active or not

What's the difference between an "active player" & a "non-active player"? "Active" in the sourcecred sense or in general?
Usually, non active players are not players at all. They either need to be active or move over to the patron side.
