### ISSUE TITLE
Edit Profile Button Not Working in Player Profile Page

### ISSUE THREAD

**Issue by tenfinney** [MetaFam/TheGame#872]
Although the Edit Profile Button can be accessed by clicking the Avatar in the upper right corner of the page next to the pSeed count, it does not work in the areas circle in red.
Brave, Firefox and Chrome
![edit-profile-button-not-working](https://user-images.githubusercontent.com/32429716/138095508-33d6671c-631a-4922-816f-f814f0a2a993.png)
.

**Comment by luxumbra** [comment]
The issue here is that the Chakra Button component used has an `href` prop which ChakraUI doesn't have on their Button - I am surprised this passed typechecks/linting. As it is 'linking' to another page, it should be a Chakra Link component with a button variant to style it as desired.
