### ISSUE TITLE
Animate player hero data changes

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#890]
### What would you like to be added?

Let's animate the player hero changes the same way other profile section changes are animated.
Preferably we'd animate only the fields that were actually updated instead of animating all of the player hero section.

Example:
![animation](https://user-images.githubusercontent.com/35112939/139543736-f2d33f5e-329f-4c74-ae32-5a531873b1b4.gif)

Player hero section:
<img width="403" alt="Screenshot 2021-10-30 at 19 52 55" src="https://user-images.githubusercontent.com/35112939/139543809-c1ec3ce3-365a-4ff0-b581-2e457d8e6b16.png">

### Why is this needed?

To align it with other animations on the profile page.

**Comment by firattale** [comment]
Hi @vidvidvid , I am going to start with that.

**Comment by vidvidvid** [comment]
was fixed!
