### ISSUE TITLE
Mobile view adjustment for profile hero data fields

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#891]
### What happened?

Bad alignment in mobile view.

### What did you expect to happen?

Good alignment in mobile view.

### How can we reproduce the problem (as minimally as possible)?

Check profile hero dialog for editing profile hero data.

### Is there anything else we need to know?

It would be great if you could check and potentially adjust also the other dialogs for editing profile data.

### Browser and operating system used (if applicable)

<img width="379" alt="Screenshot 2021-10-30 at 19 55 14" src="https://user-images.githubusercontent.com/35112939/139546079-bf694da2-ca26-42ae-98be-5667951de3b7.png">

**Comment by firattale** [comment]
can you please assign this to me @vidvidvid ?

**Comment by vidvidvid** [comment]
You also might wanna align with @dysbulic on this, since I think he's also working on data that's related to this particular dialog.

**Comment by mquellhorst** [comment]
Fixed by #943
