### ISSUE TITLE
Clean up guild page

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#893]
### What would you like to be added?

Player page:
![image](https://user-images.githubusercontent.com/1402582/139940141-13c458cc-3299-4dad-99e0-7b247b7c8517.png)

Current guild page:
![image](https://user-images.githubusercontent.com/1402582/139940163-749ea387-430c-4558-ac33-6c934478cbc5.png)

- Adjust guild page column sizes to match the player page
- Get rid of sections that don't have any data: Skills, stats, gallery, quests. Implementing these would be in their own issues, let's just hide for now

### Why is this needed?

UX standardization

**Comment by marswong** [comment]
@alalonde what if re-order the whole layout: fix the profile section on top, then arrange the rest at bottom. just like this:

![Screen Shot 2021-11-12 at 11 30 34](https://user-images.githubusercontent.com/10388933/141406412-165f3baa-5f59-4a2c-ad27-326e82644e68.png)

ps: the information of profile could be more compact

**Comment by vidvidvid** [comment]
The profile page was re-designed recently, please [see figma](https://www.figma.com/file/M3BpWO13WJVp7YivScL6K9/Dashboard?node-id=1401%3A7911) for reference or run the develop branch of the repository.
