### ISSUE TITLE
On guild page, pull in announcements from Discord channel

### ISSUE THREAD

**Issue by alalonde** [MetaFam/TheGame#894]
### What would you like to be added?

We currently have an empty "announcements" section on a guild's page:
![image](https://user-images.githubusercontent.com/1402582/139941124-78a7da4a-1fa5-4d2f-a0c9-912768faddb6.png)

For guilds that have a [connected discord server](https://my.metagame.wtf/join/guild), we could pull in the "announcements" discord channel automatically. 

This should probably happen on-demand using a Hasura remote action, like how a guild's discord roles are currently fetched.

Outstanding questions:
- Is there a standardized way of identifying public "events" or "announcements" channels via the discord API?
  - If not, we would need the guild owner (as specified in our DB) to provide the channel ID
- Any additional permissions required?

### Why is this needed?

The data is already there and we should have access to it, why not?

**Comment by mquellhorst** [comment]
@Udit-takkar could you report the status on this issue?

**Comment by Udit-takkar** [comment]
@mquellhorst  I mentioned the permissions that have to be updated if the discord bot and he told me that he would have to make some changes on the discord bot code.
