### ISSUE TITLE
Enhance the styling of the MegaMenu

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#911]
### What would you like to be added?

New styles for the panes that open up when a top-level navigation item is clicked.

Here is a demo in Figma that shows it in action: https://www.figma.com/proto/A6Nh2tyBbRCpglAnm7JQDm/MetaMenu?page-id=86%3A107&node-id=684%3A281&viewport=322%2C48%2C0.15&scaling=min-zoom&starting-point-node-id=684%3A281

Please contact me about any details re: implementing this design. There are things like background blur or drop-shadow effects, that might go unnoticed at first glance. I will gladly be your helper while you build this in 👍

### Why is this needed?

These panes are currently still very plain-looking, and don't fit all too well with the rest of the website. The new styling will make it feel more like an integral part of the website, which it really is.

**Comment by perbruno** [comment]
I'm working on it

**Comment by Udit-takkar** [comment]
@perbruno  should i assign you? If you are currently working on this one?

**Comment by perbruno** [comment]
@Udit-takkar , yes, if it's ok

**Comment by perbruno** [comment]
@davort, I've opened a PR to get some help if the details are ok. I also have some doubts about the colors and the Avatar's background on hover.

**Comment by davort** [comment]
@perbruno – please, do tell about the doubts you mentioned. Do you think something won't work well?

**Comment by perbruno** [comment]
I have this done till now 
![image](https://user-images.githubusercontent.com/7690429/144268121-5f9ce4ad-5299-4f5b-8ea4-29689c87261d.png)

but I'm not sure if the tiles colors must be the design system ones and which colors must be used on the avatar background on hover.

Also, I'm working with black on background while on demo it's looks like a light charcoal to make the drop shadow noticeable. Should I change to charcoal ?

**Comment by davort** [comment]
Hey @perbruno — great progress so far!

**Re: colors**
You are right, the colors aren't a perfect match to our current design system, which is unfortunate. 
Thing is, we simply don't have the capacity to work on both MyMeta and our Design System at this time. MyMeta is an absolute priority, so we're "winging it" for now, but trying to keep the look & feel as coherent as possible.

Not sure if you had the opportunity to visit the actual Figma file? Here is the link to this particular artboard:
https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/MetaMenu?node-id=709%3A58

Additionally, here you can find states for the dropdown menu links:
https://www.figma.com/file/A6Nh2tyBbRCpglAnm7JQDm/MetaMenu?node-id=1402%3A10539

Let me know if this helps, or if you have any more questions.

**Comment by peth-yursick** [comment]
Any progress on this @perbruno?
