### ISSUE TITLE
Dirty data of player 2221444218

### ISSUE THREAD

**Issue by marswong** [MetaFam/TheGame#912]
### What happened?

the player `2221444218` has no `pronouns` field and it break the `/players` page :(

### What did you expect to happen?

the player `2221444218` should have complete required fileds as others

### How can we reproduce the problem (as minimally as possible)?

clone the repo and run `yarn web:dev` with remote server https://api.metagame.wtf/v1/graphql

### Browser and operating system used (if applicable)

Firefox 94.0.1 on macOS 10.15.7

**Comment by polimyl** [comment]
the `develop` branch of the repo includes the new pronous feature, while the deployed production backend does not include it yet. you need to use a more up-to-date backend that includes the new pronouns feature (either run it yourself or use one of the pr preview ones)

**Comment by marswong** [comment]
> the `develop` branch of the repo includes the new pronouns feature, while the deployed production backend does not include it yet. you need to use a more up-to-date backend that includes the new pronouns feature (either run it yourself or use one of the pr preview ones)

shouldn't we follow the [C4](https://github.com/MetaFam/TheGame/blob/develop/guides/C4.md#25-branches-and-releases)? now the main branch (`develop`) cannot be built.

**Comment by polimyl** [comment]
the `develop` branch does indeed work. what you are trying to do is use the frontend from the `develop` branch together with the backend from the `master` branch, which doesn't work because the `develop` frontend is expecting some functionality that is in the `devleop` backend but not in the `master` backend. using either both backend and frontend from `develop` or from `master` works without any problems.

**Comment by polimyl** [comment]
try using https://api-staging.metagame.wtf/v1/graphql instead, i think that deploys from develop (didn't test it though)

**Comment by marswong** [comment]
> try using https://api-staging.metagame.wtf/v1/graphql instead, i think that deploys from develop (didn't test it though)

@polimyl it works. shall we make https://api-staging.metagame.wtf/v1/graphql as the stable synchronized environment of `develop` branch?
