### ISSUE TITLE
Seeds Page

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#925]
### What would you like to be added?

We need a page with all the info regarding Seeds:

- [What they are](https://wiki.metagame.wtf/docs/how-does-it-work/xp/)
- [Where you can claim them](https://claim.metagame.wtf/)
- [Where you can buy them](https://balancer.exchange/#/swap/ether/0x30cf203b48edaa42c3b4918e955fed26cd012a3f)
  - Along with the [Patron's path](https://meta-game.notion.site/Patron-Path-1db90c8bb4c84398a6fe1f672ea5e855)
- [Where you can plant them](https://pools.balancer.exchange/#/pool/0xea05a15dbce2eb543ffda16950e95b2bd2e40d0e/)
- [What you can do with them](https://meta-game.notion.site/Usefulness-of-Seeds-56358863654746738052ab2e1a8fdade)
  - Some of these usecases are live, we should make them easy to use

To begin with, it can be a simple page with short explanations & links to where you can read more or do actions such as buy, claim or plant.
The design of the page is the first thing needed. Need help finding a designer, a writer or writing & designing it yourself? [Ask about it here](https://discord.gg/4gfpHGgUvE)

Longer term, actions such as claim, buy/sell & plant should all be directly integrated into the page in a similar way that the [PrimeDAO did it](https://github.com/MetaFam/TheGame/issues/263) for their own balancer pool:
![image](https://user-images.githubusercontent.com/55857222/142198812-4d18b55c-d917-4edc-8ed1-dc9c6bf5ce99.png)

### Why is this needed?

Because right now info about Seeds & all of the above actions are dispersed all over the place and the "Seeds" link in the megamenu simply takes people to the "XP & Seeds" page on github.

**Comment by vidvidvid** [comment]
good idea, that would definitely be useful to have - especially the integrated ability to interact with seeds. i'm ready to work on this after we're done with building the dashboard! @davort wanna team up on that? :3

**Comment by davort** [comment]
Yes, this is a great idea, and I'd like to team up with you on this quest @vidvidvid 🤝 
Also, this might be a nice quest to take on after we have done the redesign of the new Landing page, which is currently underway.

**Comment by Udit-takkar** [comment]
> good idea, that would definitely be useful to have

Yeah this is very useful page

**Comment by FiyinOdebunmi** [comment]
Awesome! I'd also like to team up with @vidvidvid to jump on the design!!

**Comment by FiyinOdebunmi** [comment]
Is there a figma link for this project already? if yes, pls add me to it so I can start designing!

**Comment by vidvidvid** [comment]
Cool stuff. After the landing page is done, we can follow the same pattern that has lately been established by making a thread and talking about all of the technicalities. Excited to work on that!

**Comment by vidvidvid** [comment]
We have some nice info that could be included in the side here: https://meta-game.notion.site/Gnomeski-Understanding-SourceCred-937cb56b83da4e36a01c21b30aefe063

**Comment by peth-yursick** [comment]
for those who missed the thread on discord, I'm prototyping this in Notion https://meta-game.notion.site/Seeds-3a301b30f9394751b77b2450f7ae2329
all feedback welcome

**Comment by vidvidvid** [comment]
I'll de-assign myself since i'm pretty busy with implementing quests.
