### ISSUE TITLE
Fetch google calendar data and rework the dashboard calendar design

### ISSUE THREAD

**Issue by vidvidvid** [MetaFam/TheGame#932]
### What would you like to be added?

The dashboard includes a calendar section, which uses the default embeddable google calendar, that looks terrible to say the least.
In order to implement our own design, we would need to fetch the data either with some sort of api or by getting and parsing the ics format of our calendar.

### Option 1: Service account

Google services require to send authentication headers with the request, even though the calendar is public so in order to bypass every single user having to authenticate, we could make use of a service account.
Here is how to set it up: https://developers.google.com/identity/protocols/oauth2/service-account
@polimyl already set one up, so you can ping me or him and i can send you the json with all the data.

### Option 2: Fetch ics

[polimyl  suggested we could fetch the ics](https://github.com/MetaFam/TheGame/pull/902#issuecomment-970062812) (`https://calendar.google.com/calendar/ical/nih59ktgafmm64ed4qk6ue8vv4@group.calendar.google.com/public/basic.ics`) on the backend in order to work around the restrictive cors policy.

@dysbulic [suggested this solution would be similar to the implementation of the IDX cache.](https://discord.com/channels/629411177947987986/629412800346849302/910368806017306655)

### Reference for the pretty design of the calendar:
https://github.com/MetaFam/TheGame/blob/d4f0d07fba8da857f898aebe76242484be784bf2/packages/web/components/Dashboard/Calendar.tsx
In this solution I created a google sheet and a script that gets the data from the MetaGame calendar and fills out the fields in the sheet. Then I published the sheet as csv, fetched it in the web app and parsed the data. The data was being updated hourly. But this felt pretty hacky and since there are apparently better solutions available we should probably choose one of them, but I spent way too much time on trying to implement this, so I'm leaving this to someone more capable. Good luck!

### Why is this needed?

Because of this:
<img width="322" alt="Screenshot 2021-11-21 at 16 54 45" src="https://user-images.githubusercontent.com/35112939/142769197-7e396083-fd53-45c9-9f6a-cc1692ea686c.png">

**Comment by vidvidvid** [comment]
Update: after successfully pulling the data into the app with the same principle as https://github.com/MetaFam/TheGame/pull/959, I spent another unsuccessful day of trying to figure out the clustefuck of ical data format. It's beyond confusing and I will never do any work with calendars, dates or any kind of stuff that is remotely related to it until people unify under the flag of the universal time. Time zones are a display of human tendency to overcomplicate things in its purest form and I will not be an advocate for it.

Btw would anyone dare to give it a go at untangling when does the following event start based on the given data (which is the same data I receive when fetching the ical data)? Deduction from hints is not allowed, we need to be able to explain this to the computer.

```
{
    "dtstart": {
        "value": "2021-04-28T07:00:00.000Z",
        "params": {
            "tzid": "America/Los_Angeles"
        }
    },
    "dtend": {
        "value": "2021-04-28T08:00:00.000Z",
        "params": {
            "tzid": "America/Los_Angeles"
        }
    },
    "dtstamp": "2021-12-12T08:41:25.000Z",
    "uid": {
        "value": "6f5eufelsh6gohvjgoo6ojft9o_R20210428T140000@google.com"
    },
    "class": {
        "value": "PUBLIC"
    },
    "sequence": {
        "value": "2"
    },
    "status": {
        "value": "CONFIRMED"
    },
    "transp": {
        "value": "TRANSPARENT"
    },
    "recurrenceRule": {
        "_cache": null,
        "origOptions": {
            "freq": 2,
            "byweekday": [
                {
                    "weekday": 2
                }
            ],
            "dtstart": "2021-04-28T07:00:00.000Z"
        },
        "options": {
            "freq": 2,
            "dtstart": "2021-04-28T07:00:00.000Z",
            "interval": 1,
            "wkst": 0,
            "count": null,
            "until": null,
            "bysetpos": null,
            "bymonth": null,
            "bymonthday": [],
            "bynmonthday": [],
            "byyearday": null,
            "byweekno": null,
            "byweekday": [
                2
            ],
            "bynweekday": null,
            "byhour": [
                7
            ],
            "byminute": [
                0
            ],
            "bysecond": [
                0
            ],
            "byeaster": null
        }
    },
    "matchingDates": [
        "2021-12-15T07:00:00.000Z"
    ]
}
```

**Comment by vidvidvid** [comment]
If anyone is willing to continue my legacy i uploaded the stuff I was trying out here: https://github.com/MetaFam/TheGame/tree/feature/ical-mayhem

**Comment by peth-yursick** [comment]
Would it be much simpler if it just displayed all times in UTC for everyone?

**Comment by luxumbra** [comment]
> If anyone is willing to continue my poor legacy, i uploaded the stuff I was trying out here: https://github.com/MetaFam/TheGame/tree/feature/ical-mayhem

*Years later...*
I'm up for the challenge @vidvidvid. I did a basic job of it for MF2 (NextJS) and I managed to wrangle the data fairly well for this years MF site too. For this year's site (Astro SSG) I set up a little express server as a simple endpoint running on a [P2PCloud](https://p2pcloud.io/) vm, fetched the events from there and rebuilt the site every 20 mins due to the SSG. It worked well over MetaFest. Obvs we don't need to rebuild the site every 20 mins coz we're not static. 

I used the [`googleapis`](https://www.npmjs.com/package/googleapis) package and authed with a JWT token. I find the [`luxon`](https://moment.github.io/luxon/#/?id=luxon) (from Moment) package to be great for handling date/time stuff. 

![image](https://github.com/MetaFam/TheGame/assets/780350/2817a233-adea-492c-8248-fdcf4c97694a)
![image](https://github.com/MetaFam/TheGame/assets/780350/524fb826-361d-4a62-8c47-ca89da83a1a2)


I would love to take this on and build upon @vidvidvid's fine work if it is up for grabs.

**Comment by peth-yursick** [comment]
> I would love to take this on and build upon @vidvidvid's fine work if it is up for grabs. Is there a Figma for the design?
Pretty sure I saw it & it must have existed since Vid built it. But, where it actually is... That's a whole other matter 😂
Maybe @davort knows?

**Comment by peth-yursick** [comment]
There we go! https://www.figma.com/file/M3BpWO13WJVp7YivScL6K9/Dashboard?type=design&node-id=86-107&mode=design&t=0SFamW3FGnQ2vnrW-0

**Comment by luxumbra** [comment]
Awesome, thanks.

**Comment by luxumbra** [comment]
I have just pushed what should be my final commit on this issue in my PR #1626
