### ISSUE TITLE
Create A DNS Name for the Ceramic Entry

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#936]
There is now a Ceramic instance running in Kubernetes at 34.145.136.199. We would like to be able to address it as `ceramic.metagame.wtf`.

One of the possibilities this opens up in pitching ourselves to other organizations is offering to share and maintain necessary infrastructure, namely Ceramic & [IdentityLink](https://github.com/MetaFam/TheGame/issues/689).

¿Who has access to the DNS registrations? @META-DREAMER, I'm betting, right @peth-yursick?

**Comment by META-DREAMER** [comment]
Yea I can setup the DNS records. Let me know how you want it set exactly and I'll get it done.

How will we permission access to using our ceramic node? Will it be public?

**Comment by dysbulic** [comment]
> Yea I can setup the DNS records. Let me know how you want it set exactly and I'll get it done.

An A record for `ceramic` resolving to `34.145.136.199`.

> How will we permission access to using our ceramic node? Will it be public?

The current implementation is the client writes to Ceramic & triggers a Hasura action to dirty the cache entry, so it can't be restricted by IP.

I know that we gave hostnames to 3Box for whitelisting as part of the ELP, so maybe we can limit it that way.

I say we start out public & harden as necessary in response to circumstances. The only dangers I'm aware of are DoSs which shouldn't endanger data.

I like the idea of doing it as a community service, & so long as we avoid griefers, I don't think it'll take too many resources.

Asset storage — images, etc. — are *(hopefuly)* stored in [web3.storage](//web3.storage), and thus pinned in [Pinata](//pinata.cloud), so all we're storing are the stream updates which are required to be less that 256KiB apiece.

**Comment by polimyl** [comment]
should probably also create a record for the ipfs instance ceramic is using (`34.86.126.175`)
something like `ipfs.metagame.wtf` or `ceramic-ipfs.metagame.wtf` if we ever want to have a dedicated ipfs node

**Comment by dysbulic** [comment]
I vote `ipfs.metagame.wtf` both for conciseness & accuracy. It's just an IPFS daemon.

**Comment by META-DREAMER** [comment]
Both those records are now setup
