### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#938]
MetaGame is getting a better—some would even say "proper"—landing page!

This will be the new default destination for anyone who visits www.metagame.wtf and isn't logged into MyMeta. (This applies both to non-players as well as to players who just haven't connected their wallet to the website. Once signed in, they will see the new Dashboard instead.)

**Why?**
The new MyMeta Landing page will replace what is currently the Wiki's start page. It will aim to tell a compelling story about what MetaGame is, in a clear, yet effective and memorable fashion. Our goal is to attract the people whom we believe are a good fit for what we are doing, and make it effortless for them to apply to join our ranks.

**How**
The content—namely its textual component—has to be as clear as possible, in order to set the right expectations with new prospects. 
The design and implementation ought to be flawless, regardless of the level of design's complexity. As a principle, performance should always be prioritised over impressive, but perhaps overly ambitious effects.
In terms of design and composition, this will be a one-page layout, with some interesting effects that will be unveiling as the page is being scrolled.

**Who?**
Preliminary design work has already begun, but is still in a research phase. _Now is the time for an interested builder to join_, so that we build the new Landing page together and avoid having "handoffs". Content is also being reimagined, so that the design can be formed around it, and thus make it truly shine.

**When?**
ASAP! This will be the new main entrance to MyMeta, and the sooner we can build, the sooner we can hope to boost the overall MetaGame experience!

**Comment by vidvidvid** [comment]
Hello, I am interested in helping to build this! I'd really like to try my hands on building an interactive scrollable site and I think we could make something pretty great. If any other builder is interested in contributing to this task, I'm sure we can find a way to split work.

**Comment by Udit-takkar** [comment]
Yeah I am also in

**Comment by vidvidvid** [comment]
An idea for navigation through the landing page: we could make it navigatable with arrow keys, so for → and ↓ would navigate the user to the next slide and ← and ↑ to the previous.

**Comment by tommymaher15** [comment]
I'd love to help put on this too!

**Comment by FiyinOdebunmi** [comment]
Nice! I'd love to jump on this
