### ISSUE TITLE
Login fails on MyMeta with Rabby wallet.

### ISSUE THREAD

**Issue by luxumbra** [MetaFam/TheGame#945]
### What happened?

Clicked 'Connect' as usual, the Web3 modal appears, I select Metamask (Rabby is the only wallet installed and works well normally), Rabby pops up asking to connect to the site. Click OK and instead of the usual signature request, there's a console message `code: -32602, message: 'from should be same as current address'` and I am not logged in.

https://user-images.githubusercontent.com/780350/144457443-ef6a94c7-8016-40b9-b043-083da7174c09.mp4

### What did you expect to happen?

I expected for Rabby to prompt me to sign the login message and then to be logged in to MyMeta and see my Avatar, etc in the header. 

### How can we reproduce the problem (as minimally as possible)?

Install Rabby wallet extension in a browser and try to connect to MyMeta.

### Is there anything else we need to know?

Metamask has been troublesome since EIP-1559 for Trezor users (and is getting worse) and isn't a viable wallet for Trezor users who are active across many dApps and networks. Downgrading to version 9 is a workaround (😱) but that seems risky. Rabby is a new wallet that doesn't share the same issues. 90% of dApps, there is no issues with Rabby but sometimes, there are. 

*It might be worth noting that I am able to login successfully on a local build of MyMeta*

### Browser and operating system used (if applicable)

Browser: Chrome Version 94.0.4606.81 (Official Build) (64-bit) 
OS: Linux

**Comment by vvvvvv1vvvvvv** [comment]
Since MyMeta set a wrong param order of personal_sign, as https://web3js.readthedocs.io/en/v1.2.11/web3-eth-personal.html#sign said, the second param of personal_sign should be address but MyMeta set it as the first param, switch them then should be works

**Comment by luxumbra** [comment]
> Since MyMeta set a wrong param order of personal_sign, as https://web3js.readthedocs.io/en/v1.2.11/web3-eth-personal.html#sign said, the second param of personal_sign should be address but MyMeta set it as the first param, switch them then should be works

Thanks. 🙏🏻  Feel free to submit a PR and maybe hop into [our Discord](https://discord.gg/metagame) and say Hi. (If you're not already there) :)

**Comment by vvvvvv1vvvvvv** [comment]
> > Since MyMeta set a wrong param order of personal_sign, as https://web3js.readthedocs.io/en/v1.2.11/web3-eth-personal.html#sign said, the second param of personal_sign should be address but MyMeta set it as the first param, switch them then should be works
> 
> Thanks. 🙏🏻 Feel free to submit a PR and maybe hop into [our Discord](https://discord.gg/metagame) and say Hi. (If you're not already there) :)

https://github.com/MetaFam/TheGame/pull/1185
