### ISSUE TITLE
[MetaOS] Disable things when wallet not connected

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#947]
### What would you like to be added?

I think it would be good to have an option for some things to be unaccessible if the wallet is not connected & the person doesn't have at least 10xp or something.
The first thing that should become private are the forums.
The link to the forum should still remain on the menu but it should be greyed out with "log in first" pop over.

### Why is this needed?

It would be good to make the forums more private as they are now fully public & with time, there will probably be more things we might want to hide from newcomers & make them onboard to be able to unlock different pieces of MetaGame.

I understand people will still be access the forums once they have the link but at least it won't be readily available for anyone that opens the website.

**Comment by Udit-takkar** [comment]
You Mean this https://my.metagame.wtf/players . But What do you mean by link would still remain on menu but greyed out? 
<img width="1014" alt="Screenshot 2021-12-11 at 9 29 52 PM" src="https://user-images.githubusercontent.com/53316345/145683131-e7387ba4-51e2-4a67-bc28-a3b6829b6b32.png">

**Comment by peth-yursick** [comment]
> You Mean this https://my.metagame.wtf/players . But What do you mean by link would still remain on menu but greyed out? <img alt="Screenshot 2021-12-11 at 9 29 52 PM" width="1014" src="https://user-images.githubusercontent.com/53316345/145683131-e7387ba4-51e2-4a67-bc28-a3b6829b6b32.png">

Not just greyed out but not-clickable & the link not visible at the bottom of the page on hover.
