### ISSUE TITLE
Fetch metagame substack to backend to potentially bypass CORS error on frontend 

### ISSUE THREAD

**Issue by tommymaher15** [MetaFam/TheGame#948]
### What would you like to be added?

to fetch data from (https://metagame.substack.com/feed) to the backend so it can be pulled into the frontend to avoid restrictive CORS errors. 

### Why is this needed?

Currently I'm working on the Dashboard and fetching data from [metagame substack rss  feed](https://metagame.substack.com/feed) To display on the frontend but right now I'm getting cors errors. 

I haven't spent any time on the backend myself and I was wondering if there was someone able to help on this one so I can finish the feature for the dashboard.

**Comment by Udit-takkar** [comment]
I think i found a workaround for this
