### ISSUE TITLE
Several UI and Developer Experience improvements

### ISSUE THREAD

**Issue by firattale** [MetaFam/TheGame#962]
### What would you like to be added?

1-) Add a Custom 404 Page #1013 
2-) Scrolling in the Homepage creates a white blank at top and at bottom. We need to prevent that or change the color to have better color consistency. https://my.metagame.wtf/players #1104 
3-) It is good to have path aliases in the import of other components. That would save time to to copy other component's imports or changing any file location. #1082 

### Why is this needed?

1-)  We have a regular Next Js 404 Page, It would be good to use a custom 404 Page, But design needed.

<img width="1440" alt="Screenshot 2021-12-08 at 17 26 48" src="https://user-images.githubusercontent.com/34514974/145370069-053b9812-39c3-4c24-a8ed-73688f639dd2.png">
2-)
<img width="1440" alt="Screenshot 2021-12-08 at 17 26 06" src="https://user-images.githubusercontent.com/34514974/145370436-cd9fc4a2-555e-40fc-8615-a80fee08dbb7.png">
3-)

**Comment by vidvidvid** [comment]
Nice suggestions. May I ask what is the url of the 'home page' you're referring to?

**Comment by firattale** [comment]
hi @vidvidvid , it is happening here https://my.metagame.wtf/players

**Comment by vidvidvid** [comment]
ohh, but this is just standard website design, i believe. it's happening on pretty much every website on mac/chrome. we could look into how to change that, but i don't think it needs fixing. just check github, for example, same thing happens here:
![white](https://user-images.githubusercontent.com/35112939/145374357-c4c49030-f577-42fb-a328-558d657eac54.gif)

**Comment by firattale** [comment]
Yes @vidvidvid , that's true, but it is white because in light mode, when you switch to dark mode, that area becomes dark and consistent with theme UI. So we can change it to Metagame purple color.

**Comment by vidvidvid** [comment]
ahhh, true!

**Comment by vidvidvid** [comment]
the file for setting the theme can be found in `packages/design-system/src/theme/index.ts`

**Comment by mquellhorst** [comment]
Could you also look into the flickering effect the animations have in the profiles in this PR?

https://user-images.githubusercontent.com/25387592/146056177-6e5cf2b4-d0ed-4394-ba46-b79d25c5ff4a.mov

**Comment by firattale** [comment]
@mquellhorst this might happen because of my recent PR, but haven't seen anything like that in my profile, I will check that.

**Comment by firattale** [comment]
@mquellhorst I check both on my local and live and it seems fine, where did this happen like browser etc? is it possible to reproduce it?

**Comment by vidvidvid** [comment]
I'll fix 2) in #1104
