### ISSUE TITLE
[MetaOS] Changing newsfeed from read/listen/watch to core/ecosystem/meta

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#967]
### What would you like to be added?

Instead of filtering the newsfeed into read/listen/watch, a more meaningful way to split it would be into something like core/ecosystem/meta or inside/around/outside.

Core:
This feed would be about what's going on inside the core of MetaGame, currently inside MetaFam.
- Core would be the ValueFeed, a feed of all the (above ? to not make it spam, eventually user should set their own sensitivity) XP-generating events pulled from sourcecred.
- This is probably the hardest one, SourceCred team estimated $10k to build the feature for us & idk if we have anyone who knows how to do that around
- The primitive way Misanth solved it is by filtering from #didathing & #giveprops things that received above X number of octos to [#fake-valuefeed](https://discord.gg/h25EjHa4).

Ecosystem:
This implies the [guilds](https://my.metagame.wtf/guilds) of metagame 
- This would be pulling in announcements from their discord servers, enabled through me currently getting them to onboard our bot & somebody closing #894 

Meta:
This implies anything going on in the wider web3 but also regenerative or self-improvement space
- This could simply be an RSS feed of newsletters curated by the community
- We can start with well known newsletters in the Ethereum space, about DAOs, NFTs, DeFi & dApps, then expand the focus with time to anything that allows people to metagame

### Why is this needed?

Seems like a much more meaningful way to allow people to see what's going on.
Instead of having a huge feed of everything - a fast paced feed from inside metagame mixed with slower overview posts, which results in people having to scroll infinitely to get full context, even if they only want to see the "meta picture" that day instead of reading about every little things that happened & scroll infinitely.

**Comment by davort** [comment]
I see the value in bringing in a richer set of content into this section.

At the same time, I would advise against rushed judgements on "what is more meaningful" in terms of the UI design itself. That we can't possibly know before we have designed and tested with actual users.

Displaying content can be handled in many ways. We could allow for filtering the feed by content type, but then also by different other parameters. Perhaps we might wanna introduce tags as labels we could use to clearly mark if content comes from the Core, Ecosystem or Meta.

Either way, I don't think this decision per se deserves too much time or discussion. Content-wise, I welcome ideas for enriching the Dashboard in any way it makes sense, so for that please keep the ideas flowing in! 😊

**Comment by peth-yursick** [comment]
> At the same time, I would advise against rushed judgements on "what is more meaningful" in terms of the UI design itself. That we can't possibly know before we have designed and tested with actual users.

I don't think its a rushed judgement, it came after thinking about it for a long time, it came from 2 people independently (PVF came up with pretty much the exact same idea for MetaNews) & confirmed by everyone asked that it would be a great way to have visibility on what's happening at all levels - inside, around & outside MG rather than just inside MG.

I also don't think these 3 categories should just be added to a list of tags that require multiple clicking, scrolling & finding.
- Not to say we shouldn't have other filters or categories, we should.

I think its one of the crucial things to make it useful to non-players as well as more useful to players in terms of giving context of around & outside rather than just MG content, split by "read, listen & watch" - which was not great idea from the beginning.
Not to mention once we have a feed of XP-generating events, which will spam the content feed..

Willing to make a bet that having these 3 options as default tabs on top instead of what we have currently is way more meaningful but not sure how to test yet.

Either way!
I think you're right in that we're not doing enough user testing.
Also agree we shouldn't spend more time on this now, far from priorities..

**Comment by davort** [comment]
Makes sense, @peth-yursick.
Seems like you and PVF have done at least _some_ research, unlike myself, so it makes sense that we do as you propose 👍Would you need some designs for that, or can we do the "switcheroo" immediately?

**Comment by peth-yursick** [comment]
> Makes sense, @peth-yursick. Seems like you and PVF have done at least _some_ research, unlike myself, so it makes sense that we do as you propose 👍Would you need some designs for that, or can we do the "switcheroo" immediately?

I think we can "just" do the switcheroo, @vidvidvid liked the idea & wanted to do it 
He was also saying it might be a good idea to keep the current filters as well in some way. I'd personally get rid of them as they kind of complicate things + some things include text & videos. Also, for example, we publish the podcast both as a podcast which would go under listen, but we also publish it on youtube.. 
Gets tricky until we have a tagging system for this curation of content, which may be ways down the road.
Worth thinking about but not sure its worth spending time on at this point.

And not just the "what do we do with read listen & watch then?" but the whole switcheroo thing as well, the Questing system that he's currently working on is more important and there are probably other things of higher priority as well.

**Comment by vidvidvid** [comment]
I think the duplicates of video and podcasts can be fixed if all podcasts that get uploaded to youtube are added on a specific playlist and then all the videos from this playlist are not displayed in the video section.

**Comment by davort** [comment]
Sounds like a reasonably simple workaround until we get it sorted on our end (with aforementioned tagging system).

**Comment by Seroxdesign** [comment]
Disagree here. read listen and watch is way more intuitive.
