### ISSUE TITLE
[GuildBot] Allow admins to create quests through the bot

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/TheGame#972]
### What would you like to be added?

This is feature request for the bot that is being used to create guild pages based on discord servers by @alalonde 

The feature I'd want added:
- Allow guild admins & moderators to create quests through their discords

There would essentially need to be a command, the bot would check if the user has the required role, then bridge the request they have into [Quests](https://my.metagame.wtf/quests)

### Why is this needed?

I think its important to meet the users where they are - in their discord servers - before we hope to convince them our platform is useful & bring them onto it.

**Comment by mquellhorst** [comment]
I've been looking into this but for now I don't really see a way to add a complete description when adding quests with the bot. I was actually leaning onto adding through the site and completion through discord.

Maybe someone has an idea about adding descriptions through the bot

**Comment by peth-yursick** [comment]
Yeah I think this is more long term..
First, we'd need to make it possible to complete the quests & then either close #642 or implement filtering like on MyMeta so we can start migrating quests from Notion. Otherwise, allowing people to create quests through discord will be of no use..
![image](https://user-images.githubusercontent.com/55857222/146167161-600ec5db-938f-49e2-808f-14ea6af939f4.png)
