### ISSUE TITLE
Dashboard layout reset 

### ISSUE THREAD

**Issue by mquellhorst** [MetaFam/TheGame#977]
When changing the layout you can also reset the layout.
Resetting this layout resolves in the boxes becoming very small and in one column.

I'm currently on Windows using Firefox

**Comment by firattale** [comment]
Hi @mquellhorst, I have checked that page on my Macbook with Safari, Chrome, Edge, Firefox, Brave browsers, but couldn't reproduce it :( 
I don't know if it is Windows-related or not, does it happen all the time or rarely? does anyone face the same issue? Is your Firefox updated to the latest?

**Comment by vidvidvid** [comment]
True, it's happening for me as well. All of the profile hero items are flashing and availability is not even displayed. Happens both locally and in production. Probably the fields are constantly being rerendered for some reason.

**Comment by mquellhorst** [comment]
Will look further, if fixed I'll close it

**Comment by vidvidvid** [comment]
@mquellhorst any update on that one?

**Comment by mquellhorst** [comment]
The issue seems to be the screen size.
It occurs on larger screens. When resizing to a smaller window boxes act normal.
Somehow the sizes aren't correct after the last breakpoint

**Comment by firattale** [comment]
unfortunately I dont have a bigger screen :/ @vidvidvid do you have one ?

**Comment by vidvidvid** [comment]
nope

**Comment by dysbulic** [comment]
> Unfortunately, I don't have a bigger screen

@firattale, you should be able to zoom out on the page (`ctrl`+`-`) and get the same effect as being on a larger screen.
