### ISSUE TITLE
Redesign the 404 page

### ISSUE THREAD

**Issue by davort** [MetaFam/TheGame#986]
### What would you like to be added?

Currently, the 404 page leaves a lot to be desired.
<img width="1440" alt="404pageToday" src="https://user-images.githubusercontent.com/1573304/146878777-d5fff5df-6f5b-43bc-ae21-4078d9dcf910.png">

Design a better, more informative 404 error page, which will give visitors options for moving forward from this "dead-end." And all that in a way—visually and verbally—that is more in line with MetaGame's brand.

### Why is this needed?

With MetaGame as complex as it is, we want to provide new visitors guidance with every step of their journey. At the same time, it would be prudent to provide a cohesive UX in all corners of the MetaGame Universe, and this is no exception.

**Comment by davort** [comment]
@firattale I sent you an invite to the Figma file which contains the final design, with variants for all supported breakpoints. You should be able to resize the responsive artboard at the bottom of the file, and see it behave like in this video demo: 

https://user-images.githubusercontent.com/1573304/147465780-148d418c-ef32-4aea-afd9-265095e4a794.mp4

Parts of this design that should hopefully find their way to Storybook are:
1) grids
2) buttons

Let me know if you have any questions!

**Comment by firattale** [comment]
thankd @davort , I will check that!

**Comment by davort** [comment]
@firattale - when do you think you might be able to start building the design?

**Comment by firattale** [comment]
Hi @davort , I was busy this week, I believe I can start after 31st.
