### ISSUE TITLE
Dashboard should only be visible when authenticated

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#988]
### What would you like to be added?

When a user accesses `/dashboard` and is not logged in, they should be forwarded to `/players`.

### Why is this needed?

The dashboard is full of personalized content, so if there is no one to personalize to the page doesn't make sense.

**Comment by peth-yursick** [comment]
> The dashboard is full of personalized content, so if there is no one to personalize to the page doesn't make sense.

Not really full of personalized info, only number of Seeds & XP are personal.
I think at least the newsfeed & calendar should remain public as they were so far.
I'd say the whole thing should remain public so the newcomers see it & it entices them to join.

"Become a player to get personalized info & be able to customize the dashboard" 🤷‍♂️

**Comment by vidvidvid** [comment]
I agree with @peth-yursick - every section that holds personal info could just have a banner saying 'log in to display data' or we could simply hide it until the user logs in. @firattale what do you think, could you make some kind of banners or hide the personal sections instead of redirecting the person if they aren't logged in?

**Comment by firattale** [comment]
Yes, it can be done. Instead of the Seeds and XP, we can just put the connect wallet button over there. @peth-yursick and @vidvidvid but how can a user reach the dashboard instead of writing it to the browser manually? Right now we don't have any button afaik or anything to redirect users to the dashboard. @davort could you please share your thoughts design-wise on where to put the dashboard button?

**Comment by peth-yursick** [comment]
> Yes, it can be done. Instead of the Seeds and XP, we can just put the connect wallet button over there. @peth-yursick and @vidvidvid but how can a user reach the dashboard instead of writing it to the browser manually? Right now we don't have any button afaik or anything to redirect users to the dashboard. @davort could you please share your thoughts design-wise on where to put the dashboard button?

Connecting wallet still won't do much if they aren't a player. Though they may have Seeds without being a player, so in the end the only part that doesn't work is XP.. 
Instead of just "connect wallet", the XP part should maybe say something like "connect wallet or become a player". Or just "connect wallet" but if the XP count is 0, then display "you need to join MetaGame to start earning XP"? Whatever is simpler.
Alternatively, we could make it invisible when disconnected or 0 XP, but then we miss the chance to encourage them to join.
Afaik the idea was to add the dashboard button on the left side from the other buttons in the mega menu up top once its finished.

**Comment by davort** [comment]
Hey guys!
There have been some great ideas suggested here already. I love the thought about keeping the Dashboard accessible to non-players, and even retaining all elements there, as a way of getting newcomers interested in MetaGame!

IMHO, this is a great opportunity to turn the Dashboard into a discovery quest, a learning experience!
Imagine that we had a "banner" at the top of the Dash for non-connected visitors, something like this:
![DASH](https://user-images.githubusercontent.com/1573304/148547565-abbe4920-647e-46f2-84cf-f80b66ead217.png)

If they clicked the "BEGIN TOUR" button, we could offer several "coach marks" through which we could "walk them" over all key sections, and explain how they work.
An example of a [Chakra popover element](https://chakra-ui.com/docs/overlay/popover#focus-an-element-when-popover-opens), which could be used for said coach marks:
<img width="336" alt="CleanShot 2022-01-07 at 14 03 11" src="https://user-images.githubusercontent.com/1573304/148547799-acb54a35-79bb-438a-80b3-3514d8165719.png">

Even if the user didn't decide to click BEGIN TOUR, we could still keep the XP and Seeds "pills" clickable, and show these coach marks when they are clicked.

The same walkthrough, with coach marks, might be a solid idea for newly onboarded players/prospects - people who have connected their wallets and gone through the onboarding flow (a.k.a. Profile Setup flow, or internally known as "Wizard").

**Comment by davort** [comment]
@peth-yursick 
> Afaik the idea was to add the dashboard button on the left side from the other buttons in the mega menu up top once its finished.
Actually, clicking the logo would take you to "home", which to a connected user is the Dashboard. As for non-connected, this might be the Landing page, instead. I'd suggest keeping the nav bar clean, and instead add a link to the Dashboard somewhere on the Landing page, should they want to explore it.

Finally, let's not forget that we still don't have a footer, at all! And the footer is a great place to list all important pages of the website. Either way, there's a plethora of possible solutions to this challenge. I'd suggest a link on the Landing page, and making a global footer, where all important links would be clearly laid out.

**Comment by peth-yursick** [comment]
> Hey guys! There have been some great ideas suggested here already. I love the thought about keeping the Dashboard accessible to non-players, and even retaining all elements there, as a way of getting newcomers interested in MetaGame!
> 
> IMHO, this is a great opportunity to turn the Dashboard into a discovery quest, a learning experience! Imagine that we had a "banner" at the top of the Dash for non-connected visitors, something like this: ![DASH](https://user-images.githubusercontent.com/1573304/148547565-abbe4920-647e-46f2-84cf-f80b66ead217.png)
> 
> If they clicked the "BEGIN TOUR" button, we could offer several "coach marks" through which we could "walk them" over all key sections, and explain how they work. An example of a [Chakra popover element](https://chakra-ui.com/docs/overlay/popover#focus-an-element-when-popover-opens), which could be used for said coach marks: <img alt="CleanShot 2022-01-07 at 14 03 11" width="336" src="https://user-images.githubusercontent.com/1573304/148547799-acb54a35-79bb-438a-80b3-3514d8165719.png">
> 
> Even if the user didn't decide to click BEGIN TOUR, we could still keep the XP and Seeds "pills" clickable, and show these coach marks when they are clicked.
> 
> The same walkthrough, with coach marks, might be a solid idea for newly onboarded players/prospects - people who have connected their wallets and gone through the onboarding flow (a.k.a. Profile Setup flow, or internally known as "Wizard").

Love the tour idea, been thinking the same after things started coming together on the website. Would love to have something like Clippy except a cute little octo, to show you around & give you tips.
![image](https://user-images.githubusercontent.com/55857222/148611553-0c7fee4b-faf8-4551-bf0d-b0edd7eca24c.png)


> Finally, let's not forget that we still don't have a footer, at all! And the footer is a great place to list all important pages of the website. Either way, there's a plethora of possible solutions to this challenge. I'd suggest a link on the Landing page, and making a global footer, where all important links would be clearly laid out.

Just realized this for the first time a few days ago lol.
First I thought it might be a good idea to have little square shortcuts on the dashboard - thoughts on this?
But then I was scrolling another website & also realized/remembered that a lot of websites have a sitemap or at least the most useful links in the footer..

**Comment by davort** [comment]
@peth-yursick 
> First I thought it might be a good idea to have little square shortcuts on the dashboard - thoughts on this?
Can you explain—or make a sketch of—how would these "little square shortcuts" look and work?
Re: footer → let's get that thing going! I'll start a separate thread for that.

**Comment by peth-yursick** [comment]
> @peth-yursick
> 
> > First I thought it might be a good idea to have little square shortcuts on the dashboard - thoughts on this?
> 
> Can you please explain—or make a sketch of—how would these "little square shortcuts" look and work? Re: footer → let's get that thing going! I'll start a separate thread.

Something like this
![image](https://user-images.githubusercontent.com/55857222/148935635-68fd23be-7ce5-4e71-a3b2-3b93f8a9f4e7.png)
Could either be a single line with all the most important apps or a bigger multi-line section split into those "community", "learn", "contribute" & "invest" sections where each has a small shortcut to everything that's in that section.
