### ISSUE TITLE
Players Profile Loading is very slow

### ISSUE THREAD

**Issue by Udit-takkar** [MetaFam/TheGame#991]
### What happened?

The lazy loading of player profile cards on https://my.metagame.wtf/players is very very slow. As you can see time ~40s for some graphQL requests. What could be the reason for this?

<img width="678" alt="Screenshot 2021-12-26 at 11 20 23 PM" src="https://user-images.githubusercontent.com/53316345/147416403-fe1b1913-a2e5-409e-b185-eea1ccb34207.png">
 

### What did you expect to happen?

The Player profile cards to load much faster.

### How can we reproduce the problem (as minimally as possible)?

Keep Scrolling down on page https://my.metagame.wtf/players. Try after deleting cache or hard refresh.

**Comment by dysbulic** [comment]
I'm pretty sure the DAOHaus memberships are looked up each time the player description is access. Adding a cache would likely be useful. I created an issue at #997.

**Comment by dysbulic** [comment]
The pSEED lookup is similarly from The Graph each time a player record is retrieved.

**Comment by Udit-takkar** [comment]
@dysbulic  ok so should I close this issue then ?
