### ISSUE TITLE
Replace the JS-IPFS node for Ceramic with Go-IPFS

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/TheGame#999]
### What would you like to be added?

We need to migrate from the JavaScript IPFS node implementation supporting our Ceramic node to the Go version, both for performance reasons and to mitigate a memory leak (#998).

### Why is this needed?

The JS version is crashing.

**Comment by polimyl** [comment]
waiting for docker images of the go version to be released

**Comment by dysbulic** [comment]
This is done.
